### ISSUE TITLE
"Database Locked" Unhandled fatal exception

### ISSUE THREAD

**Issue by Kailoren** [EDDiscovery/EDDiscovery#3309] opened 2022-09-04 09:11 UTC
Not entirely sure what this is, sometimes EDD runs all day, sometimes it runs for 30 minutes and crashes. Perhaps its something to do with importing the databases from EDSM etc? 

An unhandled fatal exception has occurred.

```
==== BEGIN ====
SQLLiteExtensions.SQLProcessingThreadException: database is locked
database is locked ---> System.Data.SQLite.SQLiteException: database is locked
database is locked
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at EliteDangerousCore.DB.SystemsDB.GetSystemListBySqDistancesFrom(SortedListDoubleDuplicate`1 distlist, Double x, Double y, Double z, Int32 maxitems, Double mindist, Double maxdist, Boolean spherical, SQLiteConnectionSystem cn, Action`1 LookedUp) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemsDBGetByDistance.cs:line 80
   at EliteDangerousCore.DB.SystemCache.<>c__DisplayClass9_0.<GetSystemListBySqDistancesFrom>b__0(SQLiteConnectionSystem cn) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemCache.cs:line 302
   at SQLLiteExtensions.SQLAdvProcessingThread`1.<>c__DisplayClass19_0.<DBRead>b__0() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs:line 47
   at SQLLiteExtensions.Job`1.Exec() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs:line 355
   --- End of inner exception stack trace ---
   at SQLLiteExtensions.Job`1.Wait() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs:line 374
   at SQLLiteExtensions.SQLAdvProcessingThread`1.Execute[T](Func`1 func, Boolean write, UInt32 warnthreshold, String jobname) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs:line 258
   at SQLLiteExtensions.SQLAdvProcessingThread`1.DBRead(Action`1 action, UInt32 warnthreshold, String jobname) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs:line 48
   at EliteDangerousCore.DB.SystemCache.GetSystemListBySqDistancesFrom(SortedListDoubleDuplicate`1 distlist, Double x, Double y, Double z, Int32 maxitems, Double mindist, Double maxdist, Boolean spherical) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemCache.cs:line 304
   at EliteDangerousCore.StarDistanceComputer.BackgroundStardistWorkerThread() in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Computers\StarDistanceComputer.cs:line 101
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
===== END =====
```

**Comment by klightspeed** [comment] 2022-09-04 10:23
Is something outside of the program opening the database files?

**Comment by Kailoren** [comment] 2022-09-04 22:34
Not sure, I closed it because I saw someone else that had the same issue and needed to move the database files and repopulate them. When I followed the guide there was no database files in the %appdata% folder so I repopulated them from within the app and it seems to be okay now

**Comment by Eahlstan** [comment] 2022-09-04 22:50
> Not sure, I closed it because I saw someone else that had the same issue and needed to move the database files and repopulate them. When I followed the guide there was no database files in the %appdata% folder so I repopulated them from within the app and it seems to be okay now

This sounds like you're either using the portable version or defined a non-default DB folder while installing.
Please define what you mean with "repopulate from within the app". And were there any new .sqlite files in %localappdata%\EDDiscovery after doing this?

**Comment by Kailoren** [comment] 2022-09-04 23:00
within the admin menu there's two options, "rebuild user DB indexes" and "rebuild system DB indexes" and that's what I clicked.

I misread the first post and looked in %appdata% not %localappdata%. The .sqlite files are in there now so i'll move them and see if it fixes it when I reopen it tomorrow

**Comment by Eahlstan** [comment] 2022-09-04 23:17
> within the admin menu there's two options, "rebuild user DB indexes" and "rebuild system DB indexes" and that's what I clicked.
> 
> I misread the first post and looked in %appdata% not %localappdata%. The .sqlite files are in there now so i'll move them and see if it fixes it when I reopen it tomorrow

I don't follow? You said what you did already fixed it?
If it's already fixed there's no need to do anything else.

**Comment by Kailoren** [comment] 2022-09-05 07:24
I thought it had because it ran for over 10hrs without any issues (longer than it ever had), then as I was replying to you it crashed again with the same error as before.

**Comment by Eahlstan** [comment] 2022-09-05 09:51
There's a Log folder in %localappdata%\EDDiscovery please upload one from a time this crash happened ( Trace_date.0.log ).

**Comment by Kailoren** [comment] 2022-09-05 14:31
Here's the log from today, crash happened about half an hour ago. Same issue even after moving my .sqlite file and making it redownload it

[Trace_2022-05-26-12-45-29.0.log](https://github.com/EDDiscovery/EDDiscovery/files/9490577/Trace_2022-05-26-12-45-29.0.log)

**Comment by Eahlstan** [comment] 2022-09-05 15:57
It's unlikely to fix it, but you're running an old version (15.0.2) so please update.
Also a locked file most likely is caused by another app accessing the file (like klightspeed already said). This might be a second EDD running, or - what's more likely - some security program that locks the file while scanning.
I'm not going to tell you to deactivate your AV (or any other security program) because of legal reasons, but you should find a way to test this theory.

**Comment by Kailoren** [comment] 2022-09-05 17:08
I'm running version 15.1.2.0, and there is no update available for it, I could look into my AV software. Worst case I can try a complete reinstall of EDD

**Comment by Eahlstan** [comment] 2022-09-05 18:19
> I'm running version 15.1.2.0, and there is no update available for it, I could look into my AV software. Worst case I can try a complete reinstall of EDD

Well okay. I just looked inside your log file and it said you're running 12.1.5.0 - but now that you mentioned it I also looked at the name of that file. And it's from may. So even if there are errors logged regarding your problem, this is the wrong file to see them.

**Comment by Kailoren** [comment] 2022-09-05 18:43
That file I uploaded was the only Trace_date.0.log file in that folder. I didn't even think to look at the date on the file

**Comment by Eahlstan** [comment] 2022-09-05 18:44
Hm. Please sort your files by date. It might be that the .0 isn't always there. Just pick the Trace...log file from a time EDD crashed.

**Comment by robbyxp1** [comment] 2022-09-10 07:24
Closing, no more data.

**Closed by robbyxp1** 2022-09-10 07:24 UTC
Labels: Interaction with Windows System, Issue-Investigating
