### ISSUE TITLE
Unhandled UI exception

### ISSUE THREAD

**Issue by Downslide** [EDDiscovery/EDDiscovery#1502] opened 2017-11-25 22:26 UTC
### Exception Details:
>There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.Data.SQLite.SQLiteException (0x80004005): database or disk is full
>database or disk is full
>   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
>   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
>   at System.Data.SQLite.SQLiteDataReader.NextResult()
>   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
>   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
>   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
>   at EliteDangerousCore.DB.SQLiteCommandED`1.ExecuteNonQuery() in C:\Code\EDDiscovery\EliteDangerous\DB\SQLiteCommandED.cs:line 529
>   at EliteDangerousCore.JournalEntry.UpdateEDSMIDPosJump(Int64 journalid, ISystem system, Boolean jsonpos, Double dist, SQLiteConnectionUser cn, DbTransaction tn) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\JournalEntry.cs:line 563
>   at EliteDangerousCore.HistoryList.FillEDSM(HistoryEntry syspos, ISystem edsmsys, Boolean reload, SQLiteConnectionUser uconn, Boolean useedsm) in C:\Code\EDDiscovery\EliteDangerous\HistoryList\HistoryList.cs:line 474
>   at EDDiscovery.UserControls.UserControlSysInfo.Display(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlSysInfo.cs:line 145
>   at EDDiscovery.UserControls.ChangedSelectionHE.Invoke(HistoryEntry he, HistoryList hl)
>   at EDDiscovery.UserControls.UserControlTravelGrid.FireChangeSelection() in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlTravelGrid.cs:line 345
>   at EDDiscovery.UserControls.UserControlTravelGrid.AddNewEntry(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlTravelGrid.cs:line 246
>   at System.Action`2.Invoke(T1 arg1, T2 arg2)
>   at EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 643
>   at EDDiscovery.EDDiscoveryController.PlayJournalList() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 625
>   at EliteDangerousCore.EDJournalClass.ScanTickDone(List`1 entries) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\EDJournalClass.cs:line 533
>===== END =====
>```

**Comment by klightspeed** [comment] 2017-11-26 05:29
Is your disk full?

**Comment by nickfromkew** [comment] 2017-11-26 15:50
Same issue of UI exception. Disk is not full. 

### Description

Opening Elite and EDDC

### Additional Information



### Exception Details:
>There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.InvalidOperationException: This operation cannot be performed while an auto-filled column is being resized.
>   at System.Windows.Forms.DataGridView.PerformLayoutPrivate(Boolean useRowShortcut, Boolean computeVisibleRows, Boolean invalidInAdjustFillingColumns, Boolean repositionEditingControl)
>   at System.Windows.Forms.DataGridView.SetColumnHeadersHeightInternal(Int32 columnHeadersHeight, Boolean invalidInAdjustFillingColumns)
>   at System.Windows.Forms.DataGridView.AutoResizeColumnHeadersHeight(Boolean fixedRowHeadersWidth, Boolean fixedColumnsWidth)
>   at System.Windows.Forms.DataGridView.OnColumnHeadersGlobalAutoSize()
>   at System.Windows.Forms.DataGridView.set_TopLeftHeaderCell(DataGridViewHeaderCell value)
>   at System.Windows.Forms.DataGridView.get_TopLeftHeaderCell()
>   at System.Windows.Forms.DataGridView.OnCellMouseEnter(DataGridViewCellEventArgs e)
>   at System.Windows.Forms.DataGridView.UpdateMouseEnteredCell(HitTestInfo hti, MouseEventArgs e)
>   at System.Windows.Forms.DataGridView.OnColumnWidthChanged(DataGridViewColumnEventArgs e)
>   at System.Windows.Forms.DataGridView.AdjustFillingColumns()
>   at System.Windows.Forms.DataGridView.ComputeLayout()
>   at System.Windows.Forms.DataGridView.PerformLayoutPrivate(Boolean useRowShortcut, Boolean computeVisibleRows, Boolean invalidInAdjustFillingColumns, Boolean repositionEditingControl)
>   at System.Windows.Forms.DataGridView.OnHandleCreated(EventArgs e)
>   at System.Windows.Forms.Control.WmCreate(Message& m)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by klightspeed** [comment] 2017-11-26 16:59
@nickfromkew your issue is a duplicate of #1487, and should have been fixed by 8.4.2

**Comment by phroggster** [comment] 2017-11-29 21:38
@Downslide Haven't heard back, just checking in. If you out of disk space entirely, you can hold <kbd>Shift</kbd> while starting EDD. This will present you with our Safe Mode interface, and allow you to migrate the databases over to a different drive that has more space available.

**Comment by phroggster** [comment] 2017-12-04 16:24
Closing for inactivity.

**Closed** 2017-12-04 16:24 UTC
