### ISSUE TITLE
Stats by ship panel - incorrect info

### ISSUE THREAD

**Issue by Disorganise** [EDDiscovery/EDDiscovery#2167] opened 2018-10-01 09:51 UTC
I was poking around the panel and noticed it was listing a hybrid fighter - I assume this means the guardian fighter which I've yet to unlock (have been on DECE).  I  *did* get to fly one via multi-crew recently so perhaps that's where the confusion arose.
But the stats also show a T6 and T7 with the identical jumps/ly travelled etc
I had a look in the loadout section and the fighter is shown there too

![image](https://user-images.githubusercontent.com/18409322/46281516-4ce92b00-c5b2-11e8-9ff3-7eb5bc502be1.png)

![image](https://user-images.githubusercontent.com/18409322/46281752-e6184180-c5b2-11e8-9f63-7b85276ad2ae.png)

**Comment by robbyxp1** [comment] 2018-10-02 08:18
We don't have info on that ship, from coriolis or frontier data.  Not much we can do about it.

As regards the ship stats, i'll get Iain to look at it.

**Comment by iainross** [comment] 2018-10-02 10:28
I'll have a gander later.

**Comment by Disorganise** [comment] 2018-10-02 13:01
Just in case it's not obvious (re-reading now it isn't as clear as it was in my head), I don't think the fighter should be listed at all, since I've never owned one.  Not sure SLF's should even be listed tbh.  Certainly, there can be no ly travelled given there's no FSD :)

**Comment by robbyxp1** [comment] 2018-10-02 14:48
You have a loadout for that fighter.. the only thing we can do is not list fighters in the ship list..

**Comment by iainross** [comment] 2018-10-02 23:57
Bought an SLF and reproduced it showing in the stats by ship tab - I'll sort that.

Not got the duplicating thing, might be a multi-crew specific thing, I'll find an accomplice to give that a go in the next wee while.  We can probably look at whether we can exclude multi-crew fighters from the ship list, since we never actually have those.

**Comment by iainross** [comment] 2018-10-03 23:30
@Disorganise the SLFs in the stats panel bug should be fixed in this build https://ci.appveyor.com/project/EDDiscovery/eddiscovery/build/8.4.1.3282/artifacts

I tried flying someone else's in multi-crew but I didn't get the doubling thing.  Can you have a go with that portable build and see if you've still got that phantom ship thing going on?

**Comment by Disorganise** [comment] 2018-10-04 18:55
Do I need to reset something for it to re-read maybe?
![image](https://user-images.githubusercontent.com/18409322/46496115-86dc5a80-c85a-11e8-98aa-1344da6c40f8.png)

**Comment by iainross** [comment] 2018-10-04 18:57
Nope, no idea why it's not working for you - it successfully removed both my own and multi-crew SLFs from the list.

Could you zip up your edduser database and stick it somewhere I can get it from (pm me on discord or the forum if you don't want to advertise where)?

**Comment by Disorganise** [comment] 2018-10-07 03:10
I've created a new install (portable) a few times.  I've found a way to remove the duplicates.....
I used the edjp tool to create a merged journal and used it to replace all the journals except the last one.  So basically the journal folder has just the two logs plus the few jsons.

EDD has read the journals and I ended up with a 30 odd MB user db instead of 114MB.  And the duplicate ships are gone, as is the guardian fighter (I'm using the special SLF version of EDD linked above by @iainross )
So far so good.
But....I've lost my old travels using this method.  EDD seems to pull from EDSm but doesn't do anything with it except bloat the user db (now 46MB).  The EDD log says;
Retrieved 25 log entries from EDSM, from 16/08/2015 12:43:08 to 23/08/2015 12:43:08
Retrieved 1 log entries from EDSM, from 9/08/2015 12:43:08 to 16/08/2015 12:43:08
Retrieved 5 log entries from EDSM, from 19/07/2015 12:43:08 to 26/07/2015 12:43:08
for example.

but EDD doesn't seem to go back further than the journal
![image](https://user-images.githubusercontent.com/18409322/46577728-d2e4f600-ca38-11e8-8c2b-65a5458f8e34.png)

The fighter is gone, so are the duplicates.  the numbers have changed.  Interestingly, the FDL now has *more* jumps assigned to it  (82, 1134ly in screenshot in previous msg, 115, 2211ly now).
![image](https://user-images.githubusercontent.com/18409322/46577757-8fd75280-ca39-11e8-8e9c-4b06a4b6210b.png)

I didn't delete the other portable install - I have both.  Now that DECE is over, I'm happy to play around (evidently).  The 'old' one has been laggy for a while , often getting 2 or 3 systems behind - this is because cpu sits at 100%.  On my alt, I *can* use EDD voicepack as it keeps up - its user db is only 16MB which is why I've been keen to start over.  But losing the ability to display all my trips....:/

**Comment by Disorganise** [comment] 2018-10-07 12:51
Thanks.  Confirm duplicates gonesky.  Also, adjusting the history reduces the memory footprint quite a bit and seemed easier on the CPU when *not* having the game running :)   Be good to understand what is 'lost' as a result (good to know the trade off).
Did  quick test with the game, and ended up 7 mins behind.  but.....cpu at 100% and some of that is due a VM running.  Hopefully it'll be better in the morning once I can shut down the VM to free more cycles.

**Closed** 2018-11-22 16:38 UTC
Labels: EDD Bug
