### ISSUE TITLE
unhanded UI exception

### ISSUE THREAD

**Issue by MrSharku** [EDDiscovery/EDDiscovery#1700] opened 2018-02-05 20:38 UTC
### Exception Details:
>EDDiscovery v9.0.4.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>CSCore.DirectSound.DirectSoundException (0x88780096): IDirectSoundBuffer::Stop caused an error: 0x88780096, "Unknown HRESULT".
>   at CSCore.DirectSound.DirectSoundBuffer.Stop()
>   at CSCore.SoundOut.DirectSoundOut.CleanupResources()
>   at CSCore.SoundOut.DirectSoundOut.Dispose(Boolean disposing)
>   at CSCore.SoundOut.DirectSoundOut.Dispose()
>   at AudioExtensions.AudioDriverCSCore.Dispose() in C:\Code\EDDiscovery\Audio\AudioDriverCSCore.cs:line 130
>   at EDDiscovery.Actions.ActionController.CloseDown() in C:\Code\EDDiscovery\EDDiscovery\Actions\ActionController.cs:line 571
>   at EDDiscovery.EDDiscoveryForm.Controller_FinalClose() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:line 906
>===== END =====
>```

**Comment by klightspeed** [comment] 2018-02-08 06:39
Duplicate of #1603

**Closed by klightspeed** 2018-02-08 06:39 UTC

**Comment by phroggster** [comment] 2018-02-14 20:22
@MrSharku Please fill out the anonymous survey located at https://www.surveymonkey.com/r/2RJSWK7 to help us try and nail down a potential cause for this.
