### ISSUE TITLE
Unknown Unhandled Journal Event

### ISSUE THREAD

**Issue by claycle** [EDDiscovery/EDDiscovery#2389] opened 2019-01-24 05:49 UTC
{
  "timestamp": "2019-01-24T05:46:26Z",
  "event": "ReservoirReplenished",
  "FuelMain": 31.370001,
  "FuelReservoir": 0.63
}

**Comment by klightspeed** [comment] 2019-01-24 06:43
Duplicate of #2338, should be handled in 10.4.1 or later.

**Closed by klightspeed** 2019-01-24 06:43 UTC
