### ISSUE TITLE
Log Messages "unknown"

### ISSUE THREAD

**Issue by burakomurtak** [EDDiscovery/EDDiscovery#3599] opened 2024-11-25 16:44 UTC
This things fill log entries. What could cause this and how can i prevent it ? Its freeze application at startup like a minute. I dont know there is right place to write this.

![image](https://github.com/user-attachments/assets/a5472c93-b54d-4a2f-bfb1-e6a23e5c50ad)

**Comment by burakomurtak** [comment] 2024-11-25 18:19
18.1.3.0. Its getting more every login after last Powerplay update.

Rob ***@***.***>, 25 Kas 2024 Pzt, 21:09 tarihinde şunu yazdı:

**Comment by Eahlstan** [comment] 2024-11-25 18:35
There are log files in EDDs Logs folder ( `%localappdata%\EDDiscovery` ), please upload the newest one that starts with "Trace".

**Comment by burakomurtak** [comment] 2024-11-25 18:41
[Trace_2024-11-24-19-18-21.0.log](https://github.com/user-attachments/files/17907575/Trace_2024-11-24-19-18-21.0.log)

**Comment by Eahlstan** [comment] 2024-11-25 21:38
Strange.
Can you please try if reinstalling changes anything about that?
If it doesn't change anything we'd need your Elite journal files. `shell:SavedGames\Frontier Developments\Elite Dangerous`

**Comment by burakomurtak** [comment] 2024-11-26 18:15
I am uninstalled EDDiscovery and checked "C:\Program Files\EDDiscovery" folder is gone then i deleted whole folder "%localappdata%\EDDiscovery" and reinstalled latest version but logs still comes like a crazy. Here its fresh log file from EDDiscovery and journal files.
[Elite Dangerous.zip](https://github.com/user-attachments/files/17924121/Elite.Dangerous.zip)
[Trace_2024-11-26-21-06-51.0.log](https://github.com/user-attachments/files/17924127/Trace_2024-11-26-21-06-51.0.log)

**Comment by Eahlstan** [comment] 2024-11-26 19:00
I can't reproduce this.
Which language is your system set to and are you using any EDD translation?

**Comment by burakomurtak** [comment] 2024-11-26 19:25
I using EDD english and my system windows 11 turkish

**Comment by burakomurtak** [comment] 2024-11-26 19:42
i got same planets twice on my history screen. maybe should i clear my elite dangerous journal files ? or EDD store these on different location ? 

![image](https://github.com/user-attachments/assets/4eed78ee-8d06-42cd-85c5-f91eeee5f3cb)

**Comment by Eahlstan** [comment] 2024-11-26 20:30
Got it. Turkish makes it freak out.

Thanks for the report, we'll look at it.

In the meantime you could make an options.txt file in EDDs install folder and write
`culture en-GB`
in it to make EDD use English instead of your system language - but note that this will also affect your keyboard keys inside EDD.

**Comment by robbyxp1** [comment] 2024-11-26 23:03
Fixed on code base, will be in next point release.  That won't be for a week or so.

You can ignore the error or try Eahlstan's solution for now.

Thanks for the report.

**Comment by robbyxp1** [comment] 2024-11-26 23:06
Actually, its probably better to either run EDD with the -culture en-GB option (you can do that using a shortcut to the .exe if you know how), or use the options file method, just to hide the error.

**Comment by burakomurtak** [comment] 2024-11-27 05:01
Thank you, options file good enough for now.

27 Kas 2024 Çar 02:07 tarihinde Rob ***@***.***> şunu yazdı:

**Comment by Eahlstan** [comment] 2024-11-27 16:20
> i got same planets twice on my history screen. maybe should i clear my elite dangerous journal files ? or EDD store these on different location ?
> 
> ![image](https://private-user-images.githubusercontent.com/20832919/390119180-4eed78ee-8d06-42cd-85c5-f91eeee5f3cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3MjQ2MzUsIm5iZiI6MTczMjcyNDMzNSwicGF0aCI6Ii8yMDgzMjkxOS8zOTAxMTkxODAtNGVlZDc4ZWUtOGQwNi00MmNkLTg1YzUtZjkxZWVlZTVmM2NiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDE2MTg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0Y2UxMTVkYTkxOGJiM2Q2ZmZhNzIzN2VmMWVjZmNiMmY2ZTMzZGM0YmQ5MTY4NzdhMThjZDQyMmJlM2I2NTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eggb4EYTVaC9DVGbOttLZXLtcYdaO0B3a05ptjheXVk)

Good thing you shared that screenshot. This was a completely unrelated problem caused by Frontier writing bad things in one of your journals.

**Comment by robbyxp1** [comment] 2024-11-28 20:21
I think we have all the fixes for the release tomorrow. Thanks for your help.

**Closed by robbyxp1** 2024-11-28 20:21 UTC
Labels: EDD Bug, Interaction with Windows System
