### ISSUE TITLE
EDDiscovery 9.1.3.0 failing to read elite Dangerous v3 log file

### ISSUE THREAD

**Issue by daddyco01** [EDDiscovery/EDDiscovery#1817] opened 2018-03-04 16:08 UTC
History Refresh Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at EliteDangerousCore.StarScan.ProcessElements(JournalScan sc, ISystem sys, SystemNode sn, String customname, List`1 elements, ScanNodeType starscannodetype, Boolean isbeltcluster) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\StarScan.cs:line 736
   at EliteDangerousCore.StarScan.Process(JournalScan sc, ISystem sys, Boolean reprocessPrimary) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\StarScan.cs:line 323
   at EliteDangerousCore.HistoryList.ProcessUserHistoryListEntries(Func`2 hlfilter) in C:\Code\EDDiscovery\EliteDangerous\HistoryList\HistoryList.cs:line 946
   at EliteDangerousCore.HistoryList.LoadHistory(EDJournalClass journalmonitor, Func`1 cancelRequested, Action`2 reportProgress, String NetLogPath, Boolean ForceNetLogReload, Boolean ForceJournalReload, Int32 CurrentCommander, Boolean Keepuievents) in C:\Code\EDDiscovery\EliteDangerous\HistoryList\HistoryList.cs:line 915
   at EDDiscovery.EDDiscoveryController.DoRefreshHistory(RefreshWorkerArgs args) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 811

**Comment by klightspeed** [comment] 2018-03-04 16:12
Duplicate of #1762 - please see the important message in #1794 - please upgrade to 9.1.6

**Closed by klightspeed** 2018-03-04 16:12 UTC
