### ISSUE TITLE
Problem with Frontier Server using EDD CAPI 

### ISSUE THREAD

**Issue by incryptx** [EDDiscovery/EDDiscovery#3120] opened 2021-06-21 17:41 UTC
I installed and uninstalled EDD and the Frontier CAPI  does authenticate with https://auth.frontierstore.net/ but this process just opens EDD dialog >>(EDD is already running, open it anyway) over and over again, with three or four instances running.

CAPI Awaiting Callback
CAPI Require Log in

My EDD CAPI is broken and will not work. When I open EDD, it immediately opens my browser with a link to https://auth.frontierstore.net for frontier credentials. I fill them in and click on "link", and around and around we go.

**Comment by robbyxp1** [comment] 2021-06-21 17:58
Its frontier servers.  You'll have to wait until they have sorted themselves out.

**Comment by robbyxp1** [comment] 2021-06-21 18:04
Try forcing a logout via commanders settings, and try and login again. I just tried it, it works with my account. It may not work with yours, we have reports of multiple problems with CAPI in the last few weeks.

**Comment by incryptx** [comment] 2021-06-21 18:26
I don’t think so. EDDI works perfectly well. So do all my other apps which depend on Frontier’s API.

 

EDD is the only one that does not work. Since your just now implementing CAPI, may I humbly suggest that EDD does not see the authorization it generates. The app is “authorized” in Frontier’s APP, it just never makes it back to EDD.

**Comment by incryptx** [comment] 2021-06-21 19:05
In the process to authenticate an app for Frontier’s API, you first get a Frontier Login with PW. If the credentials were accepted, then you get a “link” to EDD (which sends back the successful authentication) and then you should get a change in the browser page to a dialog which asks “Approve” or “Deny” for EDD to use the Frontier API.

 

I never get the browser page to “Approve” or “Deny” EDD’s access to the Frontier API.

 

You can easily test this with the EDDI application and it’s Logon/Authentication to the Frontier API. You will get a browser “link” window which you check the approval box. Then submitting that page, you are presented with a follow on browser page to “Approve” or “Deny” EDDI’s access to the Frontier API. It seems EDD never gets to the browser page to “Approve” or “Deny” the use of the Frontier API, thus you end up opening EDD again, login again, Frontier’s API link web page, then EDD’s open it again, and back to the Frontier API login page. This is a loop which never presents the Frontier “Approve” or “Deny” page for EDD’s use of the CAPI API.

 

Now, I have been using EDD for years. It all has worked well, even the syncs to Inara, EDDN, EDSM and IGAU.

 

Frontier’s CAPI is new to EDD, but other apps which depend on it, all authenticate well with Odyssey without code updates for Frontier’s CAPI post Odyssey.

 

From: Support ***@***.***> 
Sent: Monday, June 21, 2021 11:26 AM
To: 'EDDiscovery/EDDiscovery' ***@***.***>
Subject: RE: [EDDiscovery/EDDiscovery] Problem with Frontier Server using EDD CAPI (#3120)

 

I don’t think so. EDDI works perfectly well. So do all my other apps which depend on Frontier’s API.

 

EDD is the only one that does not work. Since your just now implementing CAPI, may I humbly suggest that EDD does not see the authorization it generates. The app is “authorized” in Frontier’s APP, it just never makes it back to EDD.

**Comment by incryptx** [comment] 2021-06-21 19:29
I also get the Frontier API authentication page opening when I first open EDD. I have to close that webpage to get back to EDD.

 

When I close EDD, I get an “unhandled exception error”.

 

An unhandled fatal exception has occurred.

 

==== BEGIN ====

System.InvalidOperationException: Invoke or BeginInvoke cannot be called on a control until the window handle has been created.

   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)

   at System.Windows.Forms.Control.BeginInvoke(Delegate method, Object[] args)

   at DirectInputDevices.InputDeviceList.waitthread() in C:\Code\Examples\EDDiscovery\BaseUtilities\DirectInput\InputDeviceList.cs:line 122

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Threading.ThreadHelper.ThreadStart()

===== END =====

 

This is version 12.0.2

 

Uninstalling now and installing 12.0.3.

 

From: Support ***@***.***> 
Sent: Monday, June 21, 2021 12:05 PM
To: 'EDDiscovery/EDDiscovery' ***@***.***>
Subject: RE: [EDDiscovery/EDDiscovery] Problem with Frontier Server using EDD CAPI (#3120)

 

In the process to authenticate an app for Frontier’s API, you first get a Frontier Login with PW. If the credentials were accepted, then you get a “link” to EDD (which sends back the successful authentication) and then you should get a change in the browser page to a dialog which asks “Approve” or “Deny” for EDD to use the Frontier API.

 

I never get the browser page to “Approve” or “Deny” EDD’s access to the Frontier API.

 

You can easily test this with the EDDI application and it’s Logon/Authentication to the Frontier API. You will get a browser “link” window which you check the approval box. Then submitting that page, you are presented with a follow on browser page to “Approve” or “Deny” EDDI’s access to the Frontier API. It seems EDD never gets to the browser page to “Approve” or “Deny” the use of the Frontier API, thus you end up opening EDD again, login again, Frontier’s API link web page, then EDD’s open it again, and back to the Frontier API login page. This is a loop which never presents the Frontier “Approve” or “Deny” page for EDD’s use of the CAPI API.

 

Now, I have been using EDD for years. It all has worked well, even the syncs to Inara, EDDN, EDSM and IGAU.

 

Frontier’s CAPI is new to EDD, but other apps which depend on it, all authenticate well with Odyssey without code updates for Frontier’s CAPI post Odyssey.

 

From: Support ***@***.***> 
Sent: Monday, June 21, 2021 11:26 AM
To: 'EDDiscovery/EDDiscovery' ***@***.***>
Subject: RE: [EDDiscovery/EDDiscovery] Problem with Frontier Server using EDD CAPI (#3120)

 

I don’t think so. EDDI works perfectly well. So do all my other apps which depend on Frontier’s API.

 

EDD is the only one that does not work. Since your just now implementing CAPI, may I humbly suggest that EDD does not see the authorization it generates. The app is “authorized” in Frontier’s APP, it just never makes it back to EDD.

**Comment by Eahlstan** [comment] 2021-06-21 20:06
If I may say a word first:

We had this situation on Discord in the past. In 99% of the cases where it wasn't Frontier  it was an anti virus program running wild, so completely shut down your AV and then try it again.

And a second word: You are extremely rude, please calm down.

**Comment by incryptx** [comment] 2021-06-21 21:42
So are you.

 

I’m sorry you don’t have a handle on Frontier’s CAPI implementation. It works on all other Apps that depend on it.

 

Fix it, don’t fix it. No skin off my nose.

**Comment by Eahlstan** [comment] 2021-06-21 22:05
The only one able to fix an out-of-control AV is the company making that AV.
As there were literally never reports of the CAPI not working without Frontier failing it or an AV blocking it the burden of proof that it's not caused by on of these is quite high.
And I've spent hours on Discord with other users tracing down these things, but (and now I'm really starting to get rude) I will never do that with you as I can't stand your behaviour.

Have a nice day, I'm out on this.

**Comment by incryptx** [comment] 2021-06-21 23:39
As a fact, I have no AV on the system, except for M$ Defender and that has never caused issues with Frontier’s API. I managed to get EDD to login by changing the app focus from the browser of Frontier’s login to EDD’s login window after entering credentials to see it “actually” login. 

 

So, no AV, but a trick in a well timed app focus seems to fix this.

 

So, 99% of this is caused by AV. I’m the 1% that got by. 

 

Pardon me.

**Comment by klightspeed** [comment] 2021-06-21 23:56
The `eddiscovery://` URL launching a new EDDiscovery instance instead of passing data to the existing instance suggests that its DDE registration is broken in your current session.  You would need to either ensure all instances of EDDiscovery have been closed, or log out and back in.

**Comment by incryptx** [comment] 2021-06-22 00:25
Well phrased.

 

Then the question is “what would cause its (EDDiscovery’s) DDE registration to be broken in my current session?”

 

Can this be caused by installing/uninstalling/upgrading EDDiscovery which may leave registry artifacts?

 

I usually just install over the top of a current version. Could this break DDE registration?

**Comment by klightspeed** [comment] 2021-06-22 00:36
> Then the question is “what would cause its (EDDiscovery’s) DDE registration to be broken in my current session?”

https://devblogs.microsoft.com/oldnewthing/20070226-00/?p=27863

If there is a non-responsive program that has itself created a DDE registration, then it will cause problems with other programs that have DDE registrations.  The well-timed focus probably made it work because focusing the window brought it to the top of the stack.

**Comment by incryptx** [comment] 2021-06-22 00:57
That makes sense for what occurred.

 

Several MS updates address the DDE attack scenario. 

 

This may make it appear as an AV problem, when it’s not. 

 

I doubt EDDiscovery uses DDE.

**Comment by klightspeed** [comment] 2021-06-22 01:15
> I doubt EDDiscovery uses DDE.

EDDiscovery, EDDI, and EDMC all use DDE to register their respective protocol handlers for CAPI authentication.

**Comment by incryptx** [comment] 2021-06-22 02:14
Ah, that makes sense. 

 

Thanks.

**Comment by robbyxp1** [comment] 2021-06-22 11:15
Closing. No action to be seen on EDD.

**Closed by robbyxp1** 2021-06-22 11:15 UTC
Labels: Frontier CAPI
