### ISSUE TITLE
Issue: 6.2.0-dev shows on all virtuals desktops...

### ISSUE THREAD

**Issue by andreaspada** [EDDiscovery/EDDiscovery#880] opened 2017-03-03 17:06 UTC
After build and installed the last master branch (6.2.0) I noticed that it shows on all virtual desktops.

**Comment by klightspeed** [comment] 2017-03-04 18:06
EDDiscovery does not itself set any flag to show on all desktops.  It sounds like you have at some point right-clicked the window in the Win+Tab view and clicked "Show windows from this app on all desktops".

**Comment by andreaspada** [comment] 2017-03-04 21:29
Wow... really? This is amazing... does this is sticky? Cause I already rebooted, logged off and so on some times and it continues to behave as such.

**Comment by klightspeed** [comment] 2017-03-05 01:31
Yes, the "Show windows from this app on all desktops" is sticky.

**Comment by andreaspada** [comment] 2017-03-05 02:38
So... just checked that I **did not** set EDDiscovery to shows on all desktops... I'm using Windows 10, up to date. Any clue?

**Comment by klightspeed** [comment] 2017-03-05 04:53
I do not know - I am using Windows 10 v1607 (winver reports 10.0.14393.693), and am unable to reproduce your issue.

**Comment by andreaspada** [comment] 2017-03-06 20:44
I'm using same build as you. Windows Pro...
My EDDiscovery has not enabled to show on all desktops, yet it shows on - almost - all them. Sometime it skip, and appear after a while or after I focus another window. Weird...

**Comment by robbyxp1** [comment] 2017-03-06 21:30
We don't have any code to do anything except turn on off toolbar icon. Unless someone else can reproduce this ticket is going nowhere!

**Comment by andreaspada** [comment] 2017-03-06 21:37
Yes, I understand... I really cannot figure out what could possibly causing this behavior. I checked all options, tried the "Show All in Task Bar" on and off, also...
It just continues to appear in all desktop - although, not always as a miniature on desktops switch...

**Comment by RivieraKid** [comment] 2017-03-10 13:35
Latest git version running on Windows 10 Home 64 bit build 1607 (winver reports version 10.0.14393.726), I cannot reproduce this issue.

**Comment by gjpc** [comment] 2017-03-16 22:39
I am running EDD 6.1.2.0 and have the EDD window on all my virtual desktops. I am also running Nvidia Surround PhysX, stretching my desktop across two monitors. Do any of the non-reproducers have Nvidia Surround running?

**Comment by andreaspada** [comment] 2017-03-16 22:42
I do not use Nvidia Surround. Still have EDDiscovery on all my desktops... I'm running it minimized, cause it's quite annoying. Don't understand what can be done to solve that...

**Comment by gjpc** [comment] 2017-03-16 23:58
@andreaspada multiple screens?

**Comment by andreaspada** [comment] 2017-03-17 00:32
@gjpc nope!

**Comment by klightspeed** [comment] 2017-03-17 08:31
So:
* EDDiscovery shows on all Windows 10 virtual desktops
* It doesn't always show on the Windows+Tab virtual desktop thumbnails
* `Show windows from this app on all desktops` is not checked
* Only some people have the issue

![image](https://cloud.githubusercontent.com/assets/147116/24035010/66d73ed2-0b3f-11e7-9c86-45a2af7af4e8.png)

There is no code in EDDiscovery that interacts with the virtual desktop manager.  Windows don't inherit the `Show this window on all desktops` or `Show windows from this app on all desktops` flag from the window or process that launched them.  

This suggests that an injected DLL is registering with the `IVirtualDesktopNotificationService`, and the `IVirtualDesktopNotification.CurrentVirtualDesktopChanged` callback is calling `IVirtualDesktopManager.MoveWindowToDesktop`

If you look at the process DLLs in Process Explorer, and exclude Microsoft DLLs and "DLL"s without an image type (sort by Image Type then by Company Name), the only DLLs should be:
```
CSCore.dll
MSTTSEngine_OneCore.dll
MSTTSLoc_OneCore.dll
OpenTK.dll
EDDiscovery.exe
System.Data.SQLite.dll
Newtonsoft.Json.dll
SQLite.Interop.dll
OpenTK.GLControl.dll
```

If you have iTunes installed, you'll also have:
```
mdnsNSP.dll
```

![image](https://cloud.githubusercontent.com/assets/147116/24034757/4e3ebdd8-0b3e-11e7-99f3-ca77f76128c9.png)
![image](https://cloud.githubusercontent.com/assets/147116/24034748/3fce498a-0b3e-11e7-8c0b-598e8c1a4163.png)

Do you have any non-microsoft 32-bit or 64-bit DLLs not in this list?

**Comment by gjpc** [comment] 2017-03-17 12:27
My DLL's attached to EDD

![capture](https://cloud.githubusercontent.com/assets/1188979/24042754/9eda7db8-0ad0-11e7-9421-ce54deb2d565.PNG)
![capture](https://cloud.githubusercontent.com/assets/1188979/24042791/c781c492-0ad0-11e7-9aed-835882792260.PNG)

Show on all desktops not checked, very clever how you managed a screen shot of that dialog, Snipping tool with a delay will not do that for me.

Very bizarrely, I use 6 desktops and sometimes it is not  and sometimes it is on the immediate right desktop but always shows on the other 4.

I can only interact with the EDD window on the desktop that I started the process on. Activating it on any of the other desktops causes the EDD startup desktop to roll into place.

When I task view the active desktop, the only one that shows EDD is the desktop that it started on.

**Comment by klightspeed** [comment] 2017-03-17 14:31
Snipping tool -> Delay -> Capture, Win+Tab, right-click, wait for capture, press escape to close dropdown then to exit Win+Tab, screen at point of capture shows, select area to capture.

The fact that making the window active switches you to the desktop on which the program was started suggests that the nVidia driver is making a ghost window on other virtual desktops - that nVidia smart maximize is something I don't have installed with my nVidia driver.

**Comment by andreaspada** [comment] 2017-03-17 15:23
It is strange, indeed. But, if the nvidia driver will be the guilty, why only EDDiscovey is affected?

**Comment by klightspeed** [comment] 2017-03-17 15:38
A few possibilities:
* EDDiscovery has an option to enable a notification area icon
* Many of EDDiscovery's themes have transparency enabled
* Many of EDDiscovery's themes are borderless
* The 3D map uses an OpenGL surface

**Comment by gjpc** [comment] 2017-03-17 16:02
Went through the themes, the ghost is still on the other desktops.
Turned all transparency off, no joy.

**Comment by andreaspada** [comment] 2017-03-21 17:46
I just compiled and installed the last branch commitment, and it seems that the strange behavior has stopped. Just do not know why... 
Now, I have EDDiscovery running by a while with no trace of it on others desktops.

**Comment by gjpc** [comment] 2017-03-21 17:58
Visual Studio bug?  Will the community edition build EDD? I'll give it a go if I don't have to buy Visual Studio.

**Comment by andreaspada** [comment] 2017-03-21 18:05
I compile my branches with appveyour and travis, under continuous integration. Not sure if Visual Studio relate in some ways...

**Comment by andreaspada** [comment] 2017-03-21 20:47
Well, after a reboot, the strange ghost window returned. :-(

**Comment by gjpc** [comment] 2017-03-21 21:01
I just built master with AppVeyor and the ghost is still haunting, did not even have to re-boot.

**Comment by klightspeed** [comment] 2017-03-21 21:49
@andreaspada @gjpc So it happens with 6.2.x and not with 6.1.x?

If this is true, are you able to bisect to a commit that introduces the behaviour?

**Comment by gjpc** [comment] 2017-03-21 22:24
Forgive me @klightspeed I never have worked directly out of GitHub using AppVeyor. I am use to the command line on my own machine, but I love not needing to dirty my brand new machine with Visual Studio.   

My fork, https://github.com/gjpc/EDDiscovery says This branch is 1 commit behind EDDiscovery:master and I have no idea how to do a "git pull upstream master" into my fork through the GitHub web interface. That being said, I still have the ghost when I built and downloaded the artifact.

**Comment by RivieraKid** [comment] 2017-03-21 22:32
@gjpc I'm building in VS Community 2017 (version 15.0.0+26228.9) if it helps.

Interestingly enough, I think I can now partially reproduce the issue. 

If I have multiple virtual desktops already created when I start EDDiscovery, it's not visible on any but the desktop I started it on, however, if I press Win-Tab and then click in one of the other virtual desktop previews where the EDDiscovery window would be, Windows takes me to the primary desktop where EDDiscovery is running.

If I click outside where the EDDiscovery window would be in the virtual desktop preview, I am taken to that virtual desktop as normal.

If I add additional virtual desktops while EDDiscovery is running, the ghost is visible on the second and subsequent virtual desktops, but regardless of visibility, all virtual desktops behave as described above.

**Comment by gjpc** [comment] 2017-03-21 22:40
getting closer! My config:

```
NVIDIA System Information report created on: 03/21/2017 15:34:16
System name: I7-2017

[Display]
Operating System:	Windows 10 Pro, 64-bit
DirectX version:	12.0 
GPU processor:		GeForce GTX 1070
Driver version:		378.66
Direct3D API version:	12
Direct3D feature level:	12_1
CUDA Cores:		1920 
Core clock:		1556 MHz 
Memory data rate:	8008 MHz
Memory interface:	256-bit 
Memory bandwidth:	256.26 GB/s
Total available graphics memory:	24552 MB
Dedicated video memory:	8192 MB GDDR5
System video memory:	0 MB
Shared system memory:	16360 MB
Video BIOS version:	86.04.26.00.AE
IRQ:			Not used
Bus:			PCI Express x16 Gen3
Device Id:		10DE 1B81 37031458
Part Number:		G411 0020

[Components]

nvui.dll		8.17.13.7866		NVIDIA User Experience Driver Component
nvxdsync.exe		8.17.13.7866		NVIDIA User Experience Driver Component
nvxdplcy.dll		8.17.13.7866		NVIDIA User Experience Driver Component
nvxdbat.dll		8.17.13.7866		NVIDIA User Experience Driver Component
nvxdapix.dll		8.17.13.7866		NVIDIA User Experience Driver Component
NVCPL.DLL		8.17.13.7866		NVIDIA User Experience Driver Component
nvCplUIR.dll		8.1.930.0		NVIDIA Control Panel
nvCplUI.exe		8.1.930.0		NVIDIA Control Panel
nvWSSR.dll		6.14.13.7866		NVIDIA Workstation Server
nvWSS.dll		6.14.13.7866		NVIDIA Workstation Server
nvViTvSR.dll		6.14.13.7866		NVIDIA Video Server
nvViTvS.dll		6.14.13.7866		NVIDIA Video Server
nvLicensingS.dll		6.14.13.7866		NVIDIA Licensing Server
NVSTVIEW.EXE		7.17.13.7866		NVIDIA 3D Vision Photo Viewer
NVSTTEST.EXE		7.17.13.7866		NVIDIA 3D Vision Test Application
NVSTRES.DLL		7.17.13.7866		NVIDIA 3D Vision Module
nvDispSR.dll		6.14.13.7866		NVIDIA Display Server
NVMCTRAY.DLL		8.17.13.7866		NVIDIA Media Center Library
nvDispS.dll		6.14.13.7866		NVIDIA Display Server
PhysX		09.16.0318		NVIDIA PhysX
NVCUDA.DLL		6.14.13.7866		NVIDIA CUDA 8.0.0 driver
nvGameSR.dll		6.14.13.7866		NVIDIA 3D Settings Server
nvGameS.dll		6.14.13.7866		NVIDIA 3D Settings Server
```

**Comment by andreaspada** [comment] 2017-03-21 23:28
@klightspeed , I'll check some previous build to test if I found which first presented that behavior...

**Comment by andreaspada** [comment] 2017-03-21 23:37
@klightspeed , so far, I found that the 6.0.2 release DO NOT present such bug.

**Comment by gjpc** [comment] 2017-03-21 23:47
Not being facile with tools, @andreaspada  may I get a link to that release to confirm?

**Comment by andreaspada** [comment] 2017-03-21 23:48
@klightspeed , 6.1.0 also DO NOT present the virtual desktops bug.

**Comment by andreaspada** [comment] 2017-03-21 23:52
@gpc not sure if it works. However, here it is: https://ci.appveyor.com/project/EDDiscovery/eddiscovery/build/3.2.1.602/artifacts

A dropbox link, in the eventuality that the appveyor link do not works: 
https://www.dropbox.com/s/qqbey0lg3gk9y4y/EDDiscovery.Portable.zip?dl=0

Let me know if the first link works, I'm curious if we can share builds from appveyor...

**Comment by andreaspada** [comment] 2017-03-21 23:56
Dear fellow, I took the chance to see if previous build convert my screenshots and... drums rolling... they work. As I wrote in issue #917, screenshot conversion suddenly stop working, presenting some weird message. So, this is not something wrong on my system...

**Comment by gjpc** [comment] 2017-03-21 23:57
@andreaspada confirm, the ghost is exorcised in that version.

**Comment by andreaspada** [comment] 2017-03-21 23:59
@gjpc well, we have found something. Now, is up to you, mighty coders, unfortunately I cannot help in this regard...

**Comment by klightspeed** [comment] 2017-03-22 01:08
You have not narrowed the search parameters at all.

The build you pointed to was when development on 6.1.x *started* - i.e. when 6.0.x was split to its own branch.

There are still 180 builds between the build you linked to and the first build in which @andreaspada reported the issue (shortly after [PR 862](https://ci.appveyor.com/project/EDDiscovery/eddiscovery/build/3.2.1.782)).

In which of the following builds is the issue present:
* [Release 6.1.0](https://ci.appveyor.com/project/EDDiscovery/eddiscovery/build/3.2.1.748)
* [Before splash change](https://ci.appveyor.com/project/EDDiscovery/eddiscovery/build/3.2.1.733)
* [before audio part 4](https://ci.appveyor.com/project/EDDiscovery/eddiscovery/build/3.2.1.678)

**Comment by andreaspada** [comment] 2017-03-22 01:50
@klightspeed build 6.1.1 already is bugged in this regard. I'll check with the two build you mentioned - splash and audio - and I'll let you know.

**Comment by andreaspada** [comment] 2017-03-22 01:53
@klightspeed neither the "Before splash change" nor the "before audio part 4" seems to be affected by the desktops bugs.

**Comment by klightspeed** [comment] 2017-03-22 01:55
So Release 6.1.0 does show the issue, but the build just before PR 858 does not?

**Comment by klightspeed** [comment] 2017-03-22 01:58
Do https://ci.appveyor.com/project/EDDiscovery/eddiscovery/build/3.2.1.737 or https://ci.appveyor.com/project/EDDiscovery/eddiscovery/build/3.2.1.738 show the issue?

**Comment by gjpc** [comment] 2017-03-22 02:29
@klightspeed that build has the ghost

**Comment by klightspeed** [comment] 2017-03-22 02:31
Which one? 737 or 738?

**Comment by gjpc** [comment] 2017-03-22 02:31
Do https://ci.appveyor.com/project/EDDiscovery/eddiscovery/build/3.2.1.737 or https://ci.appveyor.com/project/EDDiscovery/eddiscovery/build/3.2.1.738 show the issue?

**Comment by klightspeed** [comment] 2017-03-22 02:33
Which of the following show the issue:
* https://ci.appveyor.com/project/EDDiscovery/eddiscovery/build/3.2.1.737
* https://ci.appveyor.com/project/EDDiscovery/eddiscovery/build/3.2.1.738
* Both of the above?

**Comment by gjpc** [comment] 2017-03-22 02:38
@klightspeed  yes, both have the ghost

**Comment by klightspeed** [comment] 2017-03-22 02:57
Does https://ci.appveyor.com/project/EDDiscovery/eddiscovery/build/3.2.1.734 have the issue?

If not, then the splash being a top-level window that is always on top and isn't shown on the taskbar could be the cause.  In this case, we'll probably have to re-arrange the `Application.Run()` to take an `ApplicationContext` that exits when the main form has closed, and close the splash where we currently hide it.

**Comment by gjpc** [comment] 2017-03-22 03:36
@klightspeed yes, you found the issue, there is no ghost in 3.2.1.734

**Comment by klightspeed** [comment] 2017-03-22 06:31
The splash was created to show that the program was running while it was migrating the old database, as the parameters required to show the window (e.g. the theme, position, etc) are stored in the database.

**Comment by klightspeed** [comment] 2017-03-22 06:40
Please confirm if #920 fixes the issue.

**Comment by gjpc** [comment] 2017-03-22 12:03
Congratulations!  Close the issue, the ghost is gone.

**Comment by andreaspada** [comment] 2017-03-22 12:57
Awesome! Ghost is gone! Kudos...

**Comment by andreaspada** [comment] 2017-03-22 18:59
@gjpc have a look at this! https://help.github.com/articles/configuring-a-remote-for-a-fork/

This is how I sync my fork with the original branch, always I want to stay even.

Inside your fork directory do: 

`git remote add upstream https://github.com/EDDiscovery/EDDiscovery `

Than, when you tel git to display the remote repositories, you'll see:

```
$ git remote -v
origin  https://github.com/"YUORNAMEHERE"/EDDiscovery.git (fetch)
origin  https://github.com/"YOURNAMEHERE"/EDDiscovery.git (push)
upstream        https://github.com/EDDiscovery/EDDiscovery (fetch)
upstream        https://github.com/EDDiscovery/EDDiscovery (push)
```




After this, you can use the following command to sync (I wrote a simple shell script to do this):

```
git fetch upstream
git checkout master
git merge upstream/master
git push
```

And, Voilá! Branch synced. When this is done, you can proceed following the wiki instructions in how to put continuous integration to work: https://github.com/EDDiscovery/EDDiscovery/wiki/Setting-up-Continuous-Integration

All the best!

**Comment by gjpc** [comment] 2017-03-22 19:35
@andreaspada so it can't be done in the web interface?

SAD ;)

**Comment by andreaspada** [comment] 2017-03-22 20:47
@gjpc never figure out if it it possible. But, it's quite simple with the CLI... you need to have bash installed (git has a version of bash which is quite useful in this regard). I use msys2 (I'm a unix power use by almost 15 years, I can't live without a properly working shell...).

After you have your git branch synced, you can use the web interface in appveyor and travis to allow for continuous building...

**Comment by gjpc** [comment] 2017-03-22 21:42
Thanks @andreaspada  I'm fine with the command line. I have been using git quite a few years.

**Comment by andreaspada** [comment] 2017-03-23 11:47
@gjpc ;-)

**Comment by andreaspada** [comment] 2017-03-23 11:47
@klightspeed, time for close this issue? ;-)

**Comment by gjpc** [comment] 2017-03-23 13:38
Yes, I think so

**Closed** 2017-03-23 13:52 UTC
