### ISSUE TITLE
Freeze shortly after startup while reading travel history

### ISSUE THREAD

**Issue by samco** [EDDiscovery/EDDiscovery#2716] opened 2020-02-06 09:58 UTC
EDDiscovery 11.2.1.0
Windows 10
Horizons

After startup, the log shows "Reading travel history" and EDDiscovery stops responding. I can't move the window, can't close it without force killing the process, current system data doesn't update, nothing.

After five minutes or so it recovers. It seems to freeze again if I leave it running for a long time but I haven't investigated further.

**Comment by klightspeed** [comment] 2020-02-06 11:08
Do you have a large travel history?  You can try reducing the amount that EDDiscovery loads by changing `Entries to read` in the `Memory` section to e.g. `>30 days old`, and trying different levels of `Essential entries` until the load time is reasonable.

If that doesn't fix it, please try the build at <https://ci.appveyor.com/project/EDDiscovery/eddiscovery/builds/30525211/artifacts> and let us know if it helps.

**Comment by samco** [comment] 2020-02-08 10:58
Changing `Entries to read` to `>30 days old` reduced the time of the freeze to around a minute.

**Comment by klightspeed** [comment] 2020-02-08 11:28
Is it running on a HDD, SSHD or a SSD?

If you look at your latest trace log in `%LOCALAPPDATA%\EDDiscovery\Log`, and search for "Job delayed for" or "Database connection held for", do you find any log entries?

**Comment by robbyxp1** [comment] 2020-02-08 17:10
Freezes can be caused by lots of factors, including if you have a lot of panels asking the internet for data (EDSM).  I'd run it in safe mode, use the clear to remove all panels and reset it back to the start state, and see if it improves

**Comment by samco** [comment] 2020-02-09 00:02
Lots and lots of "Job delayed for", mostly 500-800ms, quite a few of a few seconds, some hundreds of seconds. Here's a bad section:

```
	Line 57: [2020-02-01T23:03:52.621Z] SystemsDatabaseConnection Job delayed for 166906ms
	Line 58: [2020-02-01T23:03:52.622Z] SystemsDatabaseConnection Job delayed for 163340ms
	Line 77: [2020-02-01T23:05:55.740Z] SystemsDatabaseConnection Job delayed for 122372ms
	Line 78: [2020-02-01T23:05:55.740Z] SystemsDatabaseConnection Job delayed for 120582ms
	Line 86: [2020-02-01T23:18:02.125Z] SystemsDatabaseConnection Job delayed for 4959ms
	Line 96: [2020-02-01T23:21:20.040Z] SystemsDatabaseConnection Job delayed for 196782ms
	Line 97: [2020-02-01T23:21:20.040Z] SystemsDatabaseConnection Job delayed for 145402ms
```

The largest I found by eyeball was 238349ms.

"Database connection held for" does not appear.

I have reset all the panels, will see if that makes a difference.

**Comment by robbyxp1** [comment] 2020-02-09 13:41
If you are using the 3dmap as well as a panel which uses the system db, that will load up the usage of the system database.  Also if the system database is on a HDD, with the number of stars now, that also can slow down the program.

**Comment by samco** [comment] 2020-02-10 10:23
I did have the 3D map in a panel I never looked at, it's gone now. The database and program are both on an SSD. Everything appears to be behaving itself.

**Comment by robbyxp1** [comment] 2020-02-11 18:15
CLosing as resolved

**Closed by robbyxp1** 2020-02-11 18:15 UTC
Labels: Issue-Awaiting Details
