### ISSUE TITLE
materials filtering incorrectly

### ISSUE THREAD

**Issue by batkung** [EDDiscovery/EDDiscovery#2783] opened 2020-04-29 03:42 UTC
If I use CTRL select multiple filters in the filter field, the selected filter combination doesn't apply.

eg, I select a material type (RAW) and then combine my filter selection using CTRL to add conditions (RARE), all the rarity types still appear in the output (the filtering seems to break)

**Comment by klightspeed** [comment] 2020-04-29 17:42
Which panel is this in, and which filter are you using?

**Comment by batkung** [comment] 2020-04-30 09:51
materials tab, see attached pic

![image](https://user-images.githubusercontent.com/26521049/80697154-27643080-8b0b-11ea-9b69-216e62459bd6.png)

**Comment by klightspeed** [comment] 2020-04-30 09:59
The filters are OR, not AND.  Selecting Raw + Very Rare will select materials that are Raw OR Very Rare

**Comment by batkung** [comment] 2020-04-30 10:19
so what is the AND filter?

**Comment by robbyxp1** [comment] 2020-04-30 14:18
No its not, CTRL allows you to select multiple groups.

Closing since this is by design and not a bug, and we are not going to put AND filters in, it would be too complicated UI wise.

**Closed by robbyxp1** 2020-04-30 14:18 UTC
Labels: Help Request

**Comment by batkung** [comment] 2020-05-01 03:33
would it be easy to have the filtering split into subfilters then?..so you can filter by material type (Raw/Encoded/Manufactured or the individual materials) and then have another filter that will filter the results of the first filter by the rarity? in effect giving you  a (Raw OR Encoded OR Manufactured) AND (Rare OR Very Rare OR Common etc)
