### ISSUE TITLE
Error on Entering System LTT 4487

### ISSUE THREAD

**Issue by badbud65** [EDDiscovery/EDDiscovery#1260] opened 2017-09-09 21:49 UTC
I get this Unhandled Exception when entering this system, 'Retry' and 'Ignore' do not resolve the issue. Restarting EDDiscover reproduces the error.

<a href="https://imgur.com/agJKc2O"><img src="https://i.imgur.com/agJKc2O.png" title="source: imgur.com" /></a>

I get this error also:

<a href="https://imgur.com/QLrbiCe"><img src="https://i.imgur.com/QLrbiCe.png" title="source: imgur.com" /></a>

**VERSION 8.2.4.0

LOGS:**

[Trace_20170909224452.0.txt](https://github.com/EDDiscovery/EDDiscovery/files/1290125/Trace_20170909224452.0.txt)
[Trace_20170909175835.0.txt](https://github.com/EDDiscovery/EDDiscovery/files/1290126/Trace_20170909175835.0.txt)

**Comment by phroggster** [comment] 2017-09-09 23:11
Duplicate of #1253.

**Closed by phroggster** 2017-09-09 23:11 UTC
