### ISSUE TITLE
There was an unhandled UI exception error on startup

### ISSUE THREAD

**Issue by SusannaSaunders** [EDDiscovery/EDDiscovery#1441] opened 2017-11-05 15:57 UTC
No idea why it has started generating this error... Its worked fine up until now!
Here is the error log:

### Exception Details:
>There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
>Parameter name: index
>   at System.Collections.ArrayList.get_Item(Int32 index)
>   at System.Windows.Forms.DataGridViewRowCollection.SharedRow(Int32 rowIndex)
>   at System.Windows.Forms.DataGridViewRowCollection.get_Item(Int32 index)
>   at EDDiscovery.UserControls.UserControlEngineering.Display()
>   at EDDiscovery.UserControls.ChangedSelectionHE.Invoke(HistoryEntry he, HistoryList hl)
>   at EDDiscovery.UserControls.UserControlTravelGrid.FireChangeSelection()
>   at EDDiscovery.UserControls.UserControlTravelGrid.HistoryChanged(HistoryList hl)
>   at EDDiscovery.EDDiscoveryController.RefreshHistoryWorkerCompleted(HistoryList hist)
>===== END =====
>```

**Comment by klightspeed** [comment] 2017-11-05 16:00
Duplicate of #1435

**Closed by klightspeed** 2017-11-05 16:00 UTC
