### ISSUE TITLE
Unhandled UI Exception

### ISSUE THREAD

**Issue by Valethar** [EDDiscovery/EDDiscovery#1474] opened 2017-11-18 09:27 UTC
### Description

Closing down the program after a session.

### Exception Details:
>There was an unhandled UI exception.
>```
>==== BEGIN ====
>CSCore.DirectSound.DirectSoundException (0x88780096): IDirectSoundBuffer::Stop caused an error: 0x88780096, "Unknown HRESULT".
>   at CSCore.DirectSound.DirectSoundBuffer.Stop()
>   at CSCore.SoundOut.DirectSoundOut.CleanupResources()
>   at CSCore.SoundOut.DirectSoundOut.Dispose(Boolean disposing)
>   at CSCore.SoundOut.DirectSoundOut.Dispose()
>   at AudioExtensions.AudioDriverCSCore.Dispose()
>   at EDDiscovery.EDDiscoveryForm.Controller_FinalClose()
>===== END =====
>```

**Comment by klightspeed** [comment] 2017-11-18 09:48
Duplicate of #1470

**Closed by klightspeed** 2017-11-18 09:48 UTC

**Comment by phroggster** [comment] 2017-11-19 06:52
Duplicate of #1437, as that was reported prior to 1470.

**Comment by phroggster** [comment] 2018-02-14 20:26
@Valethar Please fill out the anonymous survey located at https://www.surveymonkey.com/r/2RJSWK7 to help us try and nail down a potential cause for this.
