### ISSUE TITLE
Window tabs resizing randomly

### ISSUE THREAD

**Issue by vidslo** [EDDiscovery/EDDiscovery#1461] opened 2017-11-12 14:53 UTC
https://imgur.com/5AXKAMk

The picture says it all. I'm running 4k on one monitor and 1280x1024 on my 2nd monitor which could be playing into it. The only way for me to fix the issue is to run in safe mode and reset window positions. However this only fixes it temporarily.

To add, this is just one example of what can happen. Often times, the 'window' tabs will resize such that i cannot even see them when I select full screen and giving me effectively a blank screen with none of the tools visible.

**Comment by robbyxp1** [comment] 2017-11-12 17:16
Acknowledged.. now have to reproduce it

**Comment by vidslo** [comment] 2017-11-16 03:30
Just for further documentation, I tried opening the program again, and this was the window orientation:
https://imgur.com/keWcSci

**Comment by phroggster** [comment] 2017-12-04 17:14
I didn't notice this issue before, but #1508 is a duplicate of this. Since we've already made progress on that ticket, I'm going to leave both open, but they are the same or similar issues.

**Comment by robbyxp1** [comment] 2017-12-14 11:45
#1508 is now closed, closing this, for 9.0

**Closed by robbyxp1** 2017-12-14 11:45 UTC
Labels: bug
