### ISSUE TITLE
Unhandled UI exception error in 9.0.1 (Updated with more error messages)

### ISSUE THREAD

**Issue by mp1963** [EDDiscovery/EDDiscovery#1577] opened 2017-12-27 16:31 UTC
### Description
Ferry trip from Deciat to Phoenix Harbour in Centralis (Colonia). Simple FSD jumps from waypoint to waypoint. Honking at every waypoint

### Exception Details:
>There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentNullException: Value cannot be null.
>Parameter name: key
>   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
>   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
>   at EliteDangerousCore.StarScan.FindSystem(ISystem sys) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\StarScan.cs:line 156
>   at EliteDangerousCore.StarScan.FindSystem(ISystem sys, Boolean useedsm) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\StarScan.cs:line 600
>   at EDDiscovery.UserControls.UserControlScan.DrawSystem() in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlScan.cs:line 268
>   at EDDiscovery.UserControls.UserControlScan.Display(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlScan.cs:line 140
>   at EDDiscovery.UserControls.ChangedSelectionHEHandler.Invoke(HistoryEntry he, HistoryList hl)
>   at EDDiscovery.UserControls.UserControlTravelGrid.FireChangeSelection() in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlTravelGrid.cs:line 346
>   at EDDiscovery.UserControls.UserControlTravelGrid.AddNewEntry(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlTravelGrid.cs:line 247
>   at System.Action`2.Invoke(T1 arg1, T2 arg2)
>   at EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 645
>   at EDDiscovery.EDDiscoveryController.PlayJournalList() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 627
>   at EliteDangerousCore.EDJournalClass.ScanTickDone(List`1 entries) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\EDJournalClass.cs:line 533
>===== END =====
>```

**Comment by mp1963** [comment] 2017-12-29 21:54
Another UI Exception Error:

>==== BEGIN ====
>System.ArgumentNullException: Value cannot be null.
>Parameter name: key
>   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
>   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
>   at EliteDangerousCore.StarScan.FindSystem(ISystem sys) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\StarScan.cs:line 156
>   at EliteDangerousCore.StarScan.FindSystem(ISystem sys, Boolean useedsm) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\StarScan.cs:line 600
>   at EDDiscovery.UserControls.UserControlScan.DrawSystem() in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlScan.cs:line 268
>   at EDDiscovery.UserControls.UserControlScan.Display(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlScan.cs:line 140
>   at EDDiscovery.UserControls.ChangedSelectionHEHandler.Invoke(HistoryEntry he, HistoryList hl)
>   at EDDiscovery.UserControls.UserControlTravelGrid.FireChangeSelection() in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlTravelGrid.cs:line 346
>   at EDDiscovery.UserControls.UserControlTravelGrid.AddNewEntry(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlTravelGrid.cs:line 247
>   at System.Action`2.Invoke(T1 arg1, T2 arg2)
>   at EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 645
>   at EDDiscovery.EDDiscoveryController.PlayJournalList() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 627
>   at EliteDangerousCore.EDJournalClass.ScanTickDone(List`1 entries) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\EDJournalClass.cs:line 533
>===== END =====

**Comment by iainross** [comment] 2017-12-31 01:37
So either StarScan.FindSystem is being called with a sys where sys.Name == null (not sure how that would have happened?) or scandataByName has got null keys in it (according to stackoverflow this can sometimes happen when adding entries to dictionaries accessed from multiple threads).

@robbyxp1 @klightspeed - do we want to put a lock on StarScan.GetOrCreateSystemNode to try and protect against this?

**Comment by iainross** [comment] 2017-12-31 01:47
Just noticed #1522 as a duplicate - I suppose a null system name in the systems db could cause the sys.Name == null.

If this is happening a lot then deleting EDDSystems.sqlite and redownloading from EDSM should sort it out if it's a systems db issue.

**Comment by klightspeed** [comment] 2017-12-31 04:54
When tracking this down about a month ago, the only way I could see this
could occur is if the NamedSystems table were out of sync with the
EdsmSystems table, though I didn't think of the possibility of a race
accessing the dictionary.

If that dictionary is indeed accessed from multiple threads, perhaps we
should replace it with a ConcurrentDictionary?

On 31 Dec 2017 12:37 PM, "Iain Ross" <notifications@github.com> wrote:

So either StarScan.FindSystem is being called with a sys where sys.Name ==
null (not sure how that would have happened?) or scandataByName has got
null keys in it (according to stackoverflow this can sometimes happen when
adding entries to dictionaries accessed from multiple threads).

@robbyxp1 <https://github.com/robbyxp1> @klightspeed
<https://github.com/klightspeed> - do we want to put a lock on
StarScan.GetOrCreateSystemNode to try and protect against this?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/EDDiscovery/EDDiscovery/issues/1577#issuecomment-354579698>,
or mute the thread

**Comment by iainross** [comment] 2017-12-31 10:23
I couldn't reproduce by manually forcing the SystemNames and EDSMSystems tables out of sync - deleted from systems from SystemNames, put non-existent EDSMId in SystemNames, pointed JournalEntries at non-existent EdsmIDs.

It can get into GetOrCreateSystemNode on the UI thread if UseEDSM is checked on one of the panels that looks up system info this way, EDSM has some bodies and a node hasn't already been created for a user scan so there is the potential for that and the Background Worker thread to both be trying something concurrently.

I'll try making it a ConcurrentDictionary and see if I notice any issues.

**Comment by robbyxp1** [comment] 2018-01-09 14:04
I'm going to close this, i've reworked the whole EDSM System lookup in PR1589/PR1606.  There were multiple issues in the system db lookup which ~may~ have been causing this.  lets see if 9.0.2 suffers any of these problems.

**Closed by robbyxp1** 2018-01-09 14:04 UTC
Labels: EDD Bug
