### ISSUE TITLE
Crash when closing EDD

### ISSUE THREAD

**Issue by JerkerPihl** [EDDiscovery/EDDiscovery#1451] opened 2017-11-08 19:41 UTC
### Exception Details:
>There was an unhandled UI exception.
>```
>==== BEGIN ====
>CSCore.DirectSound.DirectSoundException (0x88780096): IDirectSoundBuffer::Stop caused an error: 0x88780096, "Unknown HRESULT".
>   vid CSCore.DirectSound.DirectSoundBuffer.Stop()
>   vid CSCore.SoundOut.DirectSoundOut.CleanupResources()
>   vid CSCore.SoundOut.DirectSoundOut.Dispose(Boolean disposing)
>   vid CSCore.SoundOut.DirectSoundOut.Dispose()
>   vid AudioExtensions.AudioDriverCSCore.Dispose() i C:\Users\klightspeed\git\EDDiscovery\Audio\AudioDriverCSCore.cs:rad 127
>   vid EDDiscovery.EDDiscoveryForm.Controller_FinalClose() i C:\Users\klightspeed\git\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:rad 941
>===== END =====
>```

**Comment by phroggster** [comment] 2017-11-08 20:06
Duplicate of #1437.

**Closed by phroggster** 2017-11-08 20:06 UTC

**Comment by phroggster** [comment] 2018-02-14 20:27
@JerkerPihl Please fill out the anonymous survey located at https://www.surveymonkey.com/r/2RJSWK7 to help us try and nail down a potential cause for this.
