### ISSUE TITLE
Unhandled UI exception. DirectSoundException 

### ISSUE THREAD

**Issue by Gimi1967** [EDDiscovery/EDDiscovery#2616] opened 2019-10-04 20:27 UTC
Unhandled exception in 11.0.5.
I run EDD Portable  on a separate computer accessing Journals over a network.
EDD did not crash. Just the exception

`There was an unhandled UI exception.

==== BEGIN ====
CSCore.DirectSound.DirectSoundException (0x88780096): IDirectSoundBuffer::Stop caused an error: 0x88780096, "Unknown HRESULT".
   at CSCore.DirectSound.DirectSoundBuffer.Stop()
   at CSCore.SoundOut.DirectSoundOut.CleanupResources()
   at CSCore.SoundOut.DirectSoundOut.Initialize(IWaveSource source)
   at AudioExtensions.AudioDriverCSCore.Start(AudioData o, Int32 vol) in C:\Code\EDDiscovery\BaseUtilities\Audio\AudioDriverCSCore.cs:line 166
   at AudioExtensions.AudioQueue.Queue(AudioSample newdata) in C:\Code\EDDiscovery\BaseUtilities\Audio\AudioQueue.cs:line 185
   at ActionLanguage.ActionSay.ExecuteAction(ActionProgramRun ap) in C:\Code\EDDiscovery\ActionLanguage\ActionLanguage\ActionsCoreCmds\ActionSay.cs:line 307
   at ActionLanguage.ActionRun.DoExecute() in C:\Code\EDDiscovery\ActionLanguage\ActionLanguage\ActionsCore\ActionRun.cs:line 217
   at EDDiscovery.Actions.ActionController.ActionRun(ActionEvent ev, HistoryEntry he, Variables additionalvars, String flagstart, Boolean now) in C:\Code\EDDiscovery\EDDiscovery\Actions\ActionController.cs:line 552
   at EDDiscovery.EDDiscoveryForm.Controller_NewEntrySecond(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:line 671
   at EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryControllerNewEntry.cs:line 85
   at EDDiscovery.EDDiscoveryController.PlayJournalList() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryControllerNewEntry.cs:line 73
   at EliteDangerousCore.EDJournalClass.ScanTickDone(Tuple`2 entries) in C:\Code\EDDiscovery\EliteDangerous\Journal\EDJournalClass.cs:line 185
===== END =====`

**Comment by klightspeed** [comment] 2019-10-05 02:11
#1722 discusses this rare exception, though in this case it looks like the audio system is being unnecessarily re-initialised.

**Comment by robbyxp1** [comment] 2019-10-05 09:16
Hard to reproduce, if it does not happen frequently.  Is it happening all the time?

**Comment by Gimi1967** [comment] 2019-10-07 06:32
Happened only once so far. I will need to do some more testing to see if I can reproduce it, but I suspect it's going to be hard.
I use Voicemeeter to transport sound from EDD to my gaming PC. Likewise if I have video/Youtube/TV running on the second computer with EDD on. Not sure if Voicemeeter comes into this somehow.

**Comment by klightspeed** [comment] 2019-10-07 06:54
<https://stackoverflow.com/questions/55678305/idirectsound8createsoundbuffer-returns-dserr-bufferlost>

I wonder if it was a short network glitch that caused Voicemeeter to error out?

**Comment by Gimi1967** [comment] 2019-10-07 10:45
Maybe. I'll do some testing tonight and see if I can reproduce. Problem is I don't know what I did. It happened while I was playing ED, and since EDD did not crash I did not notice the error until later.

**Comment by klightspeed** [comment] 2019-10-07 10:59
If EDDiscovery didn't stop speaking, then that suggests that perhaps that sort of error is not fatal, and needs to be retried and/or logged - i.e. any method that starts or stops the audio output needs to catch `CSCore.DirectSound.DirectSoundException` exceptions, and retry and/or log as appropriate.

**Comment by Gimi1967** [comment] 2019-10-07 11:21
I don't know if EDD stopped speaking. I didn't have sound from EDD enabled at the time. It was turned off in Voicemeeter. Sorry, I'm not being helpful here.
By "not crashing", I mean that the main window didn't crash and EDD continued to read journal files and display them.

**Comment by robbyxp1** [comment] 2019-10-11 08:01
Its so rare, lets just monitor it in the background. closing

**Closed by robbyxp1** 2019-10-11 08:01 UTC
