### ISSUE TITLE
Issues when using mono on linux

### ISSUE THREAD

**Issue by galaxy119** [EDDiscovery/EDDiscovery#2663] opened 2019-12-07 21:50 UTC
Firstly, the "Settings" tab flickers violently for a good 1-5mins after program startup, eventually this stops and i'm able to edit settings normally from that point forward, until then, no elements on that tab are displayed, just the outline boxes of different areas that flicker in/out of existance rapidly.

Secondly, setting the "minimum scan value" doesn't work. It always immediately reverts back to the default "500000" once I hit OK on the popup, no matter what number I enter.

There's no console output in a terminal, and I'm not sure where the programs logs (if any) are stored so..

**Comment by klightspeed** [comment] 2019-12-08 03:21
Trace logs should be in `~/.local/share/EDDiscovery/Log`

The flickering tabs seems to be a drawing bug in Mono's Windows Forms implementation.

It is odd that your default is 500,000 when the programmed default is 50,000

**Comment by galaxy119** [comment] 2019-12-09 12:16
Maybe I misread the 0's and it is 50,000 not 500,000 
There's no EDDiscovery folder or anything similar that I can find in ~/.local/share

**Comment by galaxy119** [comment] 2019-12-09 12:38
Short update - I was able to find the -appfolder option, and setting it manually to ~/.local/share/EDDiscovery worked, but the trace log has no output when I attempt to change the minimum value option, which is default 50,000 sorry for my mistake there.

I'll continue to dig around in the code and see if I can figure anything out myself, since I'm familiar with C# and mono, but figured you might want to take a look yourself since you know the program better. Here's the trace log btw.
[Trace_2019-12-09-04-37-36.0.log](https://github.com/EDDiscovery/EDDiscovery/files/3939625/Trace_2019-12-09-04-37-36.0.log)

**Comment by galaxy119** [comment] 2019-12-09 13:20
Smol update:
I was going to just set the scan value's config setting manually, but I can't actually find that value in the user database anywhere. Is it possible the value isn't being created in the database? Or is it suppose to be in the options.txt file i seem to be missing?

**Comment by klightspeed** [comment] 2019-12-09 14:23
If using the portable version (which has the `StoreDataInProgramDirectory` setting set in `EDDiscovery.exe.config`), then the data will be stored in the `Data` directory in the directory where you extracted EDDiscovery.

The value should be saved to the database in the `Register` table under `ID=ScanPanel<n>ValueLimit`

Confirmed that switching to the settings tab results in what looks like a draw-invalidate loop.

Also confirmed that the value set in the high value threshold dialog does not stick.
Inserting some debugging trace logging, the OK button is registered, then the form closing registers a Cancel.

```
[2019-12-09T14:17:32.279Z] controlOK
[2019-12-09T14:17:32.279Z] Closing form
[2019-12-09T14:17:32.280Z] controlCancel
[2019-12-09T14:17:32.280Z] Closing Configurable Form
```

That looks a lot like mono is treating a `new` method (hiding the base method) as if it contained a call to the base method at the start of the method body.

**Comment by klightspeed** [comment] 2019-12-09 16:08
#2666 should now fix both the input box issue and the settings tab drawing issue.

**Comment by galaxy119** [comment] 2019-12-14 00:24
I was going to attempt to build the fork myself for the PR to test the fix, but when I opened the solution in Rider it had hundreds of errors for some reason. Am I missing something other than just cloning the fork to be able to actually build it?

**Comment by klightspeed** [comment] 2019-12-14 02:58
It has some git submodules - you need to run `git submodule update --init` to retrieve those submodules after initially cloning the repository (or `git clone --recurse-submodules` when cloning).

You also need the define `NO_SYSTEM_SPEECH` to exclude the speech support (which references System.Speech, which is not available under mono).

**Comment by galaxy119** [comment] 2019-12-14 06:58
After building it, the issue with the settings window has been fixed, but the issue with the minimum value remains.
[Trace_2019-12-13-22-57-44.0.log](https://github.com/EDDiscovery/EDDiscovery/files/3963554/Trace_2019-12-13-22-57-44.0.log)

**Comment by klightspeed** [comment] 2019-12-14 07:07
What branch are you building?  It looks like you're building 10.6
> [2019-12-14T06:57:44.623Z] *** Elite Dangerous Discovery Initializing - Version 10.6.0.0, Platform: Unix

It should be 11.1.2
> [2019-12-09T16:26:04.035Z] *** Elite Dangerous Discovery Initializing - Version 11.1.2.0, Platform: Unix

**Comment by klightspeed** [comment] 2019-12-14 07:15
These are the commands Travis and AppVeyor use to fetch the pull request
```
git clone https://github.com/EDDiscovery/EDDiscovery.git EDDiscovery
cd EDDiscovery
git fetch origin +refs/pull/2666/merge:
git checkout -qf FETCH_HEAD
git submodule update --init
```

These are the commands github suggests:
```
git clone https://github.com/EDDiscovery/EDDiscovery.git EDDiscovery
cd EDDiscovery
git checkout -b klightspeed-master-configform-returnresult master
git pull https://github.com/klightspeed/EDDiscovery.git master-configform-returnresult
```

**Comment by galaxy119** [comment] 2019-12-14 09:23
I simply cloned the fork, I'll try those commands and see if it gives me the proper build :shakyeyes:

**Comment by galaxy119** [comment] 2019-12-14 09:42
OK, there's some filepath naming issues I had to fix in the Icons/Controls.resx, simple matter, some of the folder and file names were lowercase instead of the PascelCase the files/folders are actually in, but it's complaining about missing a properties file:
EDDiscovery/EDDiscovery/Properties/ExtraVersion.cs, removing this from the csproj files allows the solution to build, and it did build the proper version this time. 
I can confirm both the Settings panel and the MinimumValue issues are fixed, but if you try to simply hit the 'x' on the MinimumValue popup to close it, it doesn't close, so it would appear `controlCancel` is alittle borked on that popup.

**Comment by galaxy119** [comment] 2019-12-14 10:08
Also another new issue I've found - this is likely an issue with mono itself through, if I try to use a pop-out window, EDD crashes with this error
`There was an unhandled UI exception.

==== BEGIN ====
System.EntryPointNotFoundException: GetModuleHandle assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) SharpDX.Win32Native.GetModuleHandle(string)
  at SharpDX.DirectInput.DirectInput..ctor () [0x0000b] in <4cdd20e40d4246b28b3294fba5f0faf6>:0 
  at DirectInputDevices.InputDeviceKeyboard.CreateKeyboard () [0x00001] in <10fab10e47594cd2af8c5c8ebde868b7>:0 
  at EDDiscovery.Forms.UserControlForm.Init (EDDiscovery.UserControls.UserControlCommonBase c, System.String title, System.Boolean winborder, System.String rf, System.Boolean deftopmostp, System.Boolean deftransparentp, System.Drawing.Color labelnormal, System.Drawing.Color labeltransparent) [0x00127] in <b17560c41dbf4a038e95cd0d0a4613d2>:0 
  at (wrapper remoting-invoke-with-check) EDDiscovery.Forms.UserControlForm.Init(EDDiscovery.UserControls.UserControlCommonBase,string,bool,string,bool,bool,System.Drawing.Color,System.Drawing.Color)
  at EDDiscovery.PopOutControl.PopOut (EDDiscovery.PanelInformation+PanelIDs selected) [0x000f0] in <b17560c41dbf4a038e95cd0d0a4613d2>:0 
  at EDDiscovery.UserControls.UserControlContainerSplitter+<>c__DisplayClass16_1.<MakeNode>b__4 (ExtendedControls.TabStrip tab, System.Int32 i) [0x00011] in <b17560c41dbf4a038e95cd0d0a4613d2>:0 
  at ExtendedControls.TabStrip.panelPopOut_Click (System.Object sender, System.EventArgs e) [0x0001c] in <237c8e86369a4e71a073471b5cff8620>:0 
  at System.Windows.Forms.Control.OnClick (System.EventArgs e) [0x00019] in <97cd502fc79f4ba1b2dcabac4693a0bc>:0 
  at ExtendedControls.ExtButtonDrawn.OnClick (System.EventArgs e) [0x0001d] in <237c8e86369a4e71a073471b5cff8620>:0 
  at ExtendedControls.ExtButtonDrawn.OnMouseClick (System.Windows.Forms.MouseEventArgs e) [0x00023] in <237c8e86369a4e71a073471b5cff8620>:0 
  at ExtendedControls.ExtButtonDrawn.OnMouseUp (System.Windows.Forms.MouseEventArgs mevent) [0x0000f] in <237c8e86369a4e71a073471b5cff8620>:0 
  at System.Windows.Forms.Control.WmLButtonUp (System.Windows.Forms.Message& m) [0x00078] in <97cd502fc79f4ba1b2dcabac4693a0bc>:0 
  at System.Windows.Forms.Control.WndProc (System.Windows.Forms.Message& m) [0x001b4] in <97cd502fc79f4ba1b2dcabac4693a0bc>:0 
  at System.Windows.Forms.Control+ControlWindowTarget.OnMessage (System.Windows.Forms.Message& m) [0x00000] in <97cd502fc79f4ba1b2dcabac4693a0bc>:0 
  at System.Windows.Forms.Control+ControlNativeWindow.WndProc (System.Windows.Forms.Message& m) [0x0000b] in <97cd502fc79f4ba1b2dcabac4693a0bc>:0 
  at System.Windows.Forms.NativeWindow.WndProc (System.IntPtr hWnd, System.Windows.Forms.Msg msg, System.IntPtr wParam, System.IntPtr lParam) [0x00085] in <97cd502fc79f4ba1b2dcabac4693a0bc>:0 
===== END =====`

**Comment by klightspeed** [comment] 2019-12-14 10:29
> OK, there's some filepath naming issues I had to fix in the Icons/Controls.resx, simple matter, some of the folder and file names were lowercase instead of the PascelCase the files/folders are actually in

`Icons/Controls.resx` should not be built during the normal build process - it is there simply so that Visual Studio's interface designers are able to use the icons in the EDDIcons project.  I'm guessing it was JetBrains Rider and not msbuild that was throwing the errors?  Visual Studio has a known issue where it will lower-case paths that are dragged into a resx file.

> but it's complaining about missing a properties file:
> EDDiscovery/EDDiscovery/Properties/ExtraVersion.cs, removing this from the csproj files allows the solution to build, and it did build the proper version this time.

`EDDiscovery/EDDiscovery/Properties/ExtraVersion.cs` is automatically generated during the normal build process.  If the build process is ignoring `DefaultTargets="Version;Build"`, then it won't be built.

I do have a Net Standard / Net Core branch in the pipeline, though this requires the tools be compatible with SDK projects (it looks like JetBrains Rider is compatible with SDK projects, as it can build Net Core 3.0 projects).  That takes an alternative approach to ensuring the version file is created, as SDK projects also ignore `DefaultTargets`.

> I can confirm both the Settings panel and the MinimumValue issues are fixed, but if you try to simply hit the 'x' on the MinimumValue popup to close it, it doesn't close, so it would appear controlCancel is alittle borked on that popup.

We need to handle the `Cancel` action, and explicitly have the handler return the Cancel result.  Either that, or default to returning Cancel when nothing handles the Cancel action.

>```
>System.EntryPointNotFoundException: GetModuleHandle assembly: type: member:(null)
>  at (wrapper managed-to-native) SharpDX.Win32Native.GetModuleHandle(string)
>  at SharpDX.DirectInput.DirectInput..ctor () [0x0000b] in <4cdd20e40d4246b28b3294fba5f0faf6>:0
>  at DirectInputDevices.InputDeviceKeyboard.CreateKeyboard () [0x00001] in <10fab10e47594cd2af8c5c8ebde868b7>:0
>  at EDDiscovery.Forms.UserControlForm.Init (EDDiscovery.UserControls.UserControlCommonBase c, System.String title, System.Boolean winborder, System.String rf, System.Boolean deftopmostp, System.Boolean deftransparentp, System.Drawing.Color labelnormal, System.Drawing.Color labeltransparent) [0x00127] in :0
>```

That suggests that we need to check what code paths try to use SharpDX to access the keyboard, and either replace them with `Control.OnKeyPress` etc or disable them when the platform != WindowsNT.

**Comment by klightspeed** [comment] 2019-12-14 16:45
```
git clone https://github.com/EDDiscovery/EDDiscovery.git EDDiscovery
cd EDDiscovery
git checkout -b klightspeed-master-mono-fixes master
git pull https://github.com/klightspeed/EDDiscovery.git master-configform-returnresult
git pull https://github.com/klightspeed/EDDiscovery.git master-mono-fixes
git submodule update --init
touch EDDiscovery/Properties/ExtraVersion.cs
```

**Closed** 2019-12-16 10:29 UTC

**Comment by klightspeed** [comment] 2019-12-18 12:47
> I'm also not seeing a $ sign on planet icons matching the minimum value setting, even when setting it as low as 1

Was the `Show/Hide body status icons` button checked/selected (the one that looks like a volcano)?  The status icon for valuable bodies won't show if status icons are disabled.
