### ISSUE TITLE
Logs fail to update.

### ISSUE THREAD

**Issue by 0trace0** [EDDiscovery/EDDiscovery#3005] opened 2021-02-28 16:25 UTC
I receive the following message when trying to update the history.
History Refresh Error: SQLLiteExtensions.SQLProcessingThreadException: Index was outside the bounds of the array. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at EliteDangerousCore.JournalEvents.JournalFSSSignalDiscovered.FSSSignal..ctor(JObject evt, DateTime EventTimeUTC) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\JournalEvents\JournalDiscoveryScans.cs:line 92
   at EliteDangerousCore.JournalEvents.JournalFSSSignalDiscovered..ctor(JObject evt) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\JournalEvents\JournalDiscoveryScans.cs:line 187
   at lambda_method(Closure , Object[] )
   at EliteDangerousCore.JournalEntry.CreateJournalEntry(String text, Boolean savejson, Boolean returnnullifbadjson) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Journal\JournalEntry.cs:line 237
   at EliteDangerousCore.JournalEntry.CreateJournalEntry(DbDataReader dr) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Journal\JournalEntryDB.cs:line 37
   at EliteDangerousCore.JournalEntry.GetAllByTLU(Int64 tluid, SQLiteConnectionUser cn) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Journal\JournalEntryDB.cs:line 564
   at EliteDangerousCore.JournalMonitorWatcher.<>c__DisplayClass18_0.<ProcessDetectedNewFiles>b__0(UserDatabaseConnection cn) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Journal\EDJournalMonitorWatcher.cs:line 318
   at SQLLiteExtensions.SQLProcessingThread`1.<>c__DisplayClass25_0.<ExecuteWithDatabase>b__0() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 255
   at SQLLiteExtensions.SQLProcessingThread`1.Job`1.Exec() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 68
   --- End of inner exception stack trace ---
   at SQLLiteExtensions.SQLProcessingThread`1.Job`1.Wait() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 91
   at SQLLiteExtensions.SQLProcessingThread`1.Execute[T](Func`1 func, Int32 skipframes, Int32 warnthreshold) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 239
   at SQLLiteExtensions.SQLProcessingThread`1.ExecuteWithDatabase(Action`1 action, Int32 warnthreshold) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 256
   at EliteDangerousCore.JournalMonitorWatcher.ProcessDetectedNewFiles(List`1 readersToUpdate, Action`2 updateProgress, Action`5 fireback, Int32 firebacklastn) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Journal\EDJournalMonitorWatcher.cs:line 315
   at EliteDangerousCore.EDJournalUIScanner.ParseJournalFilesOnWatchers(Action`2 updateProgress, Int32 reloadlastn, Action`5 firebacknostore, Int32 firebacklastn) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Journal\EDScanner.cs:line 311
   at EDDiscovery.EDDiscoveryController.DoRefreshHistory(RefreshWorkerArgs args) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryControllerHistory.cs:line 163
   
   Any suggestions would be greatly appreciated. Thank you for your time!

**Comment by klightspeed** [comment] 2021-02-28 16:27
Duplicate of #3002 - I'm guessing this occurred after visiting Andancan?

**Comment by robbyxp1** [comment] 2021-02-28 16:28
going to do a release in about 30 mins to fix this

**Comment by 0trace0** [comment] 2021-02-28 16:29
> 
> 
> Duplicate of #3002 - I'm guessing this occurred after visiting Andancan?

I do believe you may be right but I can't figure out how to verify. The last logs that do show are over a year ago.

**Comment by robbyxp1** [comment] 2021-02-28 16:40
Closing, new version incoming

**Closed by robbyxp1** 2021-02-28 16:40 UTC

**Comment by robbyxp1** [comment] 2021-02-28 16:50
11.10.2 is available
