### ISSUE TITLE
Feature Suggestion: Integration with INARA

### ISSUE THREAD

**Issue by andreaspada** [EDDiscovery/EDDiscovery#874] opened 2017-03-02 12:55 UTC
Just knew that it was released a tool that allow for integration with INARA from the log files. Maybe, the coders could be interested in integrate it with EDDiscovery...
https://github.com/jtickle/Picard

**Comment by robbyxp1** [comment] 2017-03-06 21:31
We are not addressing this at this time. We have enough on our plate at the moment. Closing as it's not a bug

**Comment by finwen** [comment] 2017-03-07 07:20
I will probably do this later in the future. looks like a easy  thing to add  sometime later

**Comment by AnthorNet** [comment] 2017-03-07 07:56
Not sure it is worth the time to implement something not relying on an API.

**Comment by finwen** [comment] 2017-03-07 08:01
We will see.  Might do it  and will keep this until decided.

2017-03-07 8:56 GMT+01:00 AnthorNet <notifications@github.com>:

**Comment by finwen** [comment] 2017-08-29 07:34
Inara is working on a API.  We will wait for it before doing any work.

**Comment by robbyxp1** [comment] 2017-10-05 14:47
Still no API.  No indication of timing. Closing and will reopen if it ever appears

**Closed by robbyxp1** 2017-10-05 14:47 UTC
Labels: enhancement

**Comment by pioto** [comment] 2017-11-11 01:54
Looks like there's an API now? https://inara.cz/inara-api/

**Comment by klightspeed** [comment] 2017-11-11 05:13
Docs: https://inara.cz/inara-api-docs/

It looks like INARA only uses data available in the journal - e.g. no ship modules or module engineering.
