### ISSUE TITLE
Scan window shenanigans

### ISSUE THREAD

**Issue by Tromador** [EDDiscovery/EDDiscovery#3506] opened 2024-04-28 21:46 UTC
In the Tahumbla system there are 3 stars. Bodies orbit B & C separately, whilst 8 orbit the AB pair (AB1 - AB8).

I have scanned the system using FSS. e.g.
![Screenshot 2024-04-28 223415](https://github.com/EDDiscovery/EDDiscovery/assets/38956076/24d493dc-e860-4c5e-8a81-26808af1718e)

But none of the AB planets show up on the scan window. 
![Screenshot 2024-04-28 223529](https://github.com/EDDiscovery/EDDiscovery/assets/38956076/713b7684-d301-4a7e-bd79-46b70c44fd2f)
Unless I also turn on either EDSM, Spansh, or both - at which point they appear right where they should be.
![Screenshot 2024-04-28 223624](https://github.com/EDDiscovery/EDDiscovery/assets/38956076/8bbe3026-15c4-4aa5-a823-29f507edcea9)

Here's a sample journal entry for one of the 8 planets, but I also include the whole journal for that session, in case there's other bits you need. 

```
{ "timestamp":"2024-04-28T21:02:07Z", "event":"FSSBodySignals", "BodyName":"Tahumbla AB 4", "BodyID":21, "SystemAddress":9467852498393, "Signals":[ { "Type":"$SAA_SignalType_Biological;", "Type_Localised":"Biological", "Count":1 } ] }
{ "timestamp":"2024-04-28T21:02:08Z", "event":"Scan", "ScanType":"Detailed", "BodyName":"Tahumbla AB 4", "BodyID":21, "Parents":[ {"Null":19}, {"Null":1}, {"Null":0} ], "StarSystem":"Tahumbla", "SystemAddress":9467852498393, "DistanceFromArrivalLS":1844.572484, "TidalLock":false, "TerraformState":"", "PlanetClass":"Icy body", "Atmosphere":"thin neon atmosphere", "AtmosphereType":"Neon", "AtmosphereComposition":[ { "Name":"Neon", "Percent":100.000000 } ], "Volcanism":"", "MassEM":0.185707, "Radius":4625949.000000, "SurfaceGravity":3.458876, "SurfaceTemperature":52.834679, "SurfacePressure":145.878983, "Landable":true, "Materials":[ { "Name":"sulphur", "Percent":23.014324 }, { "Name":"carbon", "Percent":19.352663 }, { "Name":"iron", "Percent":15.821336 }, { "Name":"phosphorus", "Percent":12.389908 }, { "Name":"nickel", "Percent":11.966595 }, { "Name":"chromium", "Percent":7.115380 }, { "Name":"zinc", "Percent":4.299646 }, { "Name":"germanium", "Percent":3.322960 }, { "Name":"niobium", "Percent":1.081304 }, { "Name":"yttrium", "Percent":0.944990 }, { "Name":"mercury", "Percent":0.690892 } ], "Composition":{ "Ice":0.686609, "Rock":0.210939, "Metal":0.102451 }, "SemiMajorAxis":640869617.462158, "Eccentricity":0.195235, "OrbitalInclination":-9.077229, "Periapsis":215.630745, "OrbitalPeriod":19107047.915459, "AscendingNode":-29.909921, "MeanAnomaly":307.412274, "RotationPeriod":131484.332983, "AxialTilt":-0.472121, "WasDiscovered":true, "WasMapped":true }
```

[Journal.2024-04-28T194418.01.zip](https://github.com/EDDiscovery/EDDiscovery/files/15143911/Journal.2024-04-28T194418.01.zip)

**Comment by Eahlstan** [comment] 2024-04-28 21:50
Did you already restart EDD? We had very few reports of this in the past and never found out how this is happening. Restarting EDD fixed it in the past.

Did you have EDSM or Spansh querying active at first and then deactivated it, or the other way round?

**Comment by Tromador** [comment] 2024-04-28 22:33
I fired up EDD just now and it looked fine, so possibly it's your rare hard to find bug occurring as you suggest.

I don't routinely have any external datasource on scan windows. I rather see what I've done (or need still to do) without other data confusing the issue, so I only turned it on when I noticed the error.

It's not a big deal to me, so unless you need further information or wish to investigate further, I'm happy if you close this issue.

**Comment by robbyxp1** [comment] 2024-05-01 07:51
We have this in the back of our minds, but it just isn't reproducible at the moment. Thanks for the report.

**Comment by Eahlstan** [comment] 2024-05-04 19:47
Reopening due to a breakthrough in reproducing it.
Bug confirmed.

**Comment by Tromador** [comment] 2024-05-05 04:37
> Reopening due to a breakthrough in reproducing it. Bug confirmed.

Anything I can help with, or do you have all the information you need from me?

**Comment by robbyxp1** [comment] 2024-05-05 13:47
I think we have found it.  A bug in one function when multiple scan windows were open, one with EDSM/Spansh on, the other not.

Fix will be in the next version, out next week

Thanks

Rob

**Closed** 2024-05-05 13:47 UTC
Labels: EDD Bug
