### ISSUE TITLE
unhandled UI exception CSCore.DirectSound.DirectSoundException 

### ISSUE THREAD

**Issue by b166er** [EDDiscovery/EDDiscovery#1498] opened 2017-11-24 09:38 UTC
### Description
EDDiscovery was idle for several days, after clicking to close the window, see the exception.

### Additional Information

![image](https://user-images.githubusercontent.com/679114/33202868-54973a94-d0fe-11e7-860e-7612aaca0764.png)

### Exception Details:
>There was an unhandled UI exception.
>```
>==== BEGIN ====
>CSCore.DirectSound.DirectSoundException (0x88780096): IDirectSoundBuffer::Stop caused an error: 0x88780096, "Unknown HRESULT".
>   bei CSCore.DirectSound.DirectSoundBuffer.Stop()
>   bei CSCore.SoundOut.DirectSoundOut.CleanupResources()
>   bei CSCore.SoundOut.DirectSoundOut.Dispose(Boolean disposing)
>   bei CSCore.SoundOut.DirectSoundOut.Dispose()
>   bei AudioExtensions.AudioDriverCSCore.Dispose() in C:\Code\EDDiscovery\Audio\AudioDriverCSCore.cs:Zeile 127.
>   bei EDDiscovery.EDDiscoveryForm.Controller_FinalClose() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:Zeile 943.
>===== END =====
>```

**Comment by phroggster** [comment] 2017-11-24 10:32
Duplicate of #1437.

**Closed by phroggster** 2017-11-24 10:32 UTC

**Comment by phroggster** [comment] 2018-02-14 20:23
@bi66er Please fill out the anonymous survey located at https://www.surveymonkey.com/r/2RJSWK7 to help us try and nail down a potential cause for this.
