### ISSUE TITLE
Getting ArgumentOutOfRangeException loading history

### ISSUE THREAD

**Issue by perongithub** [EDDiscovery/EDDiscovery#1878] opened 2018-03-29 07:33 UTC
History Refresh Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at EliteDangerousCore.StarScan.ProcessElements(JournalScan sc, ISystem sys, SystemNode sn, String customname, List`1 elements, ScanNodeType starscannodetype, Boolean isbeltcluster) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\StarScan.cs:line 736
   at EliteDangerousCore.StarScan.Process(JournalScan sc, ISystem sys, Boolean reprocessPrimary) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\StarScan.cs:line 323
   at EliteDangerousCore.HistoryList.ProcessUserHistoryListEntries(Func`2 hlfilter) in C:\Code\EDDiscovery\EliteDangerous\HistoryList\HistoryList.cs:line 946
   at EliteDangerousCore.HistoryList.LoadHistory(EDJournalClass journalmonitor, Func`1 cancelRequested, Action`2 reportProgress, String NetLogPath, Boolean ForceNetLogReload, Boolean ForceJournalReload, Int32 CurrentCommander, Boolean Keepuievents) in C:\Code\EDDiscovery\EliteDangerous\HistoryList\HistoryList.cs:line 915
   at EDDiscovery.EDDiscoveryController.DoRefreshHistory(RefreshWorkerArgs args) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 811
History refresh complete.

**Comment by klightspeed** [comment] 2018-03-29 08:15
Duplicate of #1760
and of #1762
and of #1763
and of #1765
and of #1767
and of #1770
and of #1772
and of #1784
and of #1785
and of #1790
and of #1791
and of #1797
and of #1817
and of #1847

Please upgrade to 9.1.8.  And, yes, we know that 9.1.3 doesn't detect the update - see #1794

**Closed by klightspeed** 2018-03-29 08:15 UTC
