### ISSUE TITLE
Unhandled UI exception

### ISSUE THREAD

**Issue by MarkSmith1974** [EDDiscovery/EDDiscovery#1470] opened 2017-11-16 19:44 UTC
### Exception Details:
>There was an unhandled UI exception.
>```
>==== BEGIN ====
>CSCore.DirectSound.DirectSoundException (0x88780096): IDirectSoundBuffer::Stop caused an error: 0x88780096, "Unknown HRESULT".
>   at CSCore.DirectSound.DirectSoundBuffer.Stop()
>   at CSCore.SoundOut.DirectSoundOut.CleanupResources()
>   at CSCore.SoundOut.DirectSoundOut.Dispose(Boolean disposing)
>   at CSCore.SoundOut.DirectSoundOut.Dispose()
>   at AudioExtensions.AudioDriverCSCore.Dispose() in C:\Users\klightspeed\git\EDDiscovery\Audio\AudioDriverCSCore.cs:line 127
>   at EDDiscovery.EDDiscoveryForm.Controller_FinalClose() in C:\Users\klightspeed\git\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:line 941
>===== END =====
>```

**Comment by robbyxp1** [comment] 2017-11-17 16:32
May be a problem in the cscore code..

**Comment by phroggster** [comment] 2017-11-18 11:38
Duplicate of #1437.

**Closed by phroggster** 2017-11-18 11:38 UTC
Labels: bug
