### ISSUE TITLE
ED Discovery 11.3.1.0 Screen refreshing issue

### ISSUE THREAD

**Issue by Phaedra-LaGrange** [EDDiscovery/EDDiscovery#2760] opened 2020-04-03 18:00 UTC
Hello,
I use ED-Discovery on my 2nd Monitor (1st Monitor Elite Dangerous) and until 3-4 days ago I hadn't any kind of issue.
But now when I jump to a new Starsystem EDD is NOT refreshing the Infos, and normaly when I move the Cursor over a Body (Planet, Moon) a Pop-up will open with all Infos in it, well this don't happen anymore. To refresh the Screen I need to click on the HISTORY-TAB, but that was NOT necessary before. 

I tryed to reinstall EDD on my external Disk (it was ALWAYS there) but it don't resolve the Issue
I'm without Ideas - Pls let me know

Best Reguards

**Comment by robbyxp1** [comment] 2020-04-04 08:28
So, I'm not sure why your program behaviour has changed.

Make sure on the travel history the cursor to top (big green up arrow) is on - this makes the cursor jump to the latest entry when received by EDD.  But it should be on when you restart the program anyway.

The popups will only occur if EDD has focus (is selected)..

otherwise, nothing about this behaviour has changed in the program.

**Comment by robbyxp1** [comment] 2020-04-07 19:56
no more feedback, closing

**Closed by robbyxp1** 2020-04-07 19:56 UTC
Labels: Issue-Investigating

**Comment by tecnosegugio** [comment] 2020-04-08 10:25
Sorry to go back on this issue but I can confirm that the Surveyor panel doesn't update his information entering a new system.
As said before, just putting the cursor on top of the travel history solve this problem but this should be done automatically at boot. 
I have enabled the "green up arrow" so the cursor is always on the latest entry of history but at boot the cursor looks like to not moving.

**Comment by tecnosegugio** [comment] 2020-04-08 20:16
Addendum: the Estimated Scan Value panel updates its information at boot correctly. 
I must cilck on the first item of the history to get Surveyor panel updated.

**Comment by robbyxp1** [comment] 2020-04-08 20:34
I think I've solved this with the next version, which should be out some time this week hopefully.
