### ISSUE TITLE
v15.0.2 Incorrect appdata location does not produce correct error output

### ISSUE THREAD

**Issue by pdario** [EDDiscovery/EDDiscovery#3265] opened 2022-05-16 19:49 UTC
![image](https://user-images.githubusercontent.com/5813131/168670908-6863e752-85a7-46fb-a535-09fe6468e9ff.png)

**Comment by Eahlstan** [comment] 2022-05-16 22:20
Please upload your log files (Trace.somenumbers.log) found in EDDs Log folder. Default location when using the installed version %localappdata%\EDDiscovery

**Comment by klightspeed** [comment] 2022-05-17 00:04
This appears to be occurring before EDDiscovery's unhandled exception handler is set up, so the trace log is unlikely to contain anything.

Please try (translate to your language):
* Open `Event Viewer`
* Expand `Windows Logs` and select `Application`
* Search for `EDDiscovery.exe`, and select the `.NET Runtime` event
* Copy and paste the contents of the General panel, which should start with something like:
```
Application: EDDiscovery.exe
```

**Comment by pdario** [comment] 2022-05-17 19:57
No, I have no recent logs in that folder.

In event viewer:

Applicazione: EDDiscovery.exe
Versione framework: v4.0.30319
Descrizione: il processo è stato terminato a causa di un'eccezione non gestita.
Informazioni sull'eccezione: System.IO.DirectoryNotFoundException
   in System.IO.__Error.WinIOError(Int32, System.String)
   in System.IO.FileSystemEnumerableIterator`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].CommonInit()
   in System.IO.FileSystemEnumerableIterator`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]..ctor(System.String, System.String, System.String, System.IO.SearchOption, System.IO.SearchResultHandler`1<System.__Canon>, Boolean)
   in System.IO.Directory.EnumerateFiles(System.String, System.String, System.IO.SearchOption)
   in EDDiscovery.EDDOptions.Init()
   in EDDiscovery.EDDOptions.get_Instance()
   in EDDiscovery.EDDApplicationContext.StartupForm()
   in EDDiscovery.EDDApplicationContext..ctor()
   in EDDiscovery.Program.Main()

**Comment by Eahlstan** [comment] 2022-05-17 21:44
I was able to reproduce it.

<details>
<summary>Proof</summary> 
```
Anwendung: EDDiscovery.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.IO.DirectoryNotFoundException
   bei System.IO.__Error.WinIOError(Int32, System.String)
   bei System.IO.FileSystemEnumerableIterator`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].CommonInit()
   bei System.IO.FileSystemEnumerableIterator`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]..ctor(System.String, System.String, System.String, System.IO.SearchOption, System.IO.SearchResultHandler`1<System.__Canon>, Boolean)
   bei System.IO.Directory.EnumerateFiles(System.String, System.String, System.IO.SearchOption)
   bei EDDiscovery.EDDOptions.Init()
   bei EDDiscovery.EDDOptions.get_Instance()
   bei EDDiscovery.EDDApplicationContext.StartupForm()
   bei EDDiscovery.EDDApplicationContext..ctor()
   bei EDDiscovery.Program.Main()
```
</details>

You might have told EDD to use your program files folder or some other especially protected folder. If you provide the content of your options.txt, optionsappdata.txt or optionsportable.txt we could confirm that.

**Comment by robbyxp1** [comment] 2022-05-18 06:49
You set up the data folder to a folder which does not exist, but its impossible to create the folder since its under a protected folder itself (such as c:\program files). Please use the default folder location or a writable other location.

**Comment by robbyxp1** [comment] 2022-05-18 06:51
I've covered up the error, it now produces:

![image](https://user-images.githubusercontent.com/6573992/168975953-9762cbd7-fc47-40ba-9925-2007b0cde511.png)

**Comment by robbyxp1** [comment] 2022-05-18 06:55
Will be fixed in 15.0.3

**Comment by Eahlstan** [comment] 2022-05-18 20:00
Most likely you didn't have any non-default appdata folder specified before so EDD used the default one (located in %localappdata%\EDDiscovery )

You might have clicked "change location" on this screen without realising what it does.

![Screenshot 2022-04-30 112249](https://user-images.githubusercontent.com/59618179/169145422-035b7c0a-b500-45ef-9e0b-7723a5d99c97.JPG)

To get EDD back to working with the default directory simply delete the optionsappdta.txt file.

**Comment by pdario** [comment] 2022-05-18 20:13
I didn't remember but it could be. I'll delete the file, thank you

**Comment by robbyxp1** [comment] 2022-05-18 21:10
Closing, thanks for your input

**Closed by robbyxp1** 2022-05-18 21:10 UTC
Labels: Interaction with Windows System
