### ISSUE TITLE
Scan panel stopped updating.

### ISSUE THREAD

**Issue by tivec** [EDDiscovery/EDDiscovery#752] opened 2017-01-26 08:12 UTC
For some reason, I no longer get updates on the Scan S-panel. Sometimes it helps restarting the program, but most often not.

The scans properly show up in a travel history window set to show scan events.

I had a lot of duplicates recently (like, everything was duplicated), this might have something to do with it.

**Comment by tivec** [comment] 2017-01-26 09:32
Addendum: I get the updates *most* of the times, but for some systems they fall out completely.

**Comment by tivec** [comment] 2017-02-02 11:28
An update to this. If I close down EDDiscovery after a finished session of exploration and it is mid system scan, the next time I take it up the scans are not updating in the scan panel.

**Comment by iainross** [comment] 2017-02-02 11:55
Not sure exactly what you mean by "mid system scan"?  You're closing EDD while the S-Panel is displaying the scan info?  While a scan is in progress in the game?

**Comment by tivec** [comment] 2017-02-02 11:56
No, let's say there are 20 planets in the system, and I scan 10 of them with the scan panel updating properly. Then I leave the game, close EDDiscovery, and later come back to scan more - and then the panel stops updating.

Could it be related to it locking itself to EDSM data?

**Comment by klightspeed** [comment] 2017-02-02 13:04
Do you have the option to automatically select the most recent journal entry enabled?

The scan panel should update every time the selected entry is changed (whether by clicking on a travel history row or having a new entry come in with automatic history scroll enabled), and every time a new Scan journal entry is logged for the currently selected system.

It looks like the body data from the journal should override any data fetched from EDSM, so there should be no problem there.

If you have enabled fetching bodies from EDSM, and all of the bodies in the system are already in EDSM, then scanning those bodies shouldn't change what is displayed in the scan panel unless the data from EDSM is wrong.

**Comment by tivec** [comment] 2017-02-02 13:07
"History cursor to new Journal Entry automatically"? No, that one is off.

Selecting another system, then selecting the misbehaving one again does not seem to clear out the issue.

Also, sometimes a full restart of EDDiscovery seems to grab the data properly... It's very intermittent.

**Comment by iainross** [comment] 2017-02-02 14:03
That sounds very odd, I'll see if I can reproduce it when I'm playing this evening.  If I can then I'll see about fixing it, if I can't then I'll be back to pump you for more details...

**Comment by tivec** [comment] 2017-02-02 14:04
Thank you, I'll see if I can reproduce it more reliably. I'll do some scans with different options on and off.

**Comment by iainross** [comment] 2017-02-02 22:46
I can't make the S-Panel stop showing the scan data by quitting and restarting.

Do you use the option to auto-load a saved set of popouts on startup?  One thing I have noticed is that every once in a while the S-Panel I load that way doesn't show on top of the game and I have to toggle that option off and on again to make it behave.  Not worked out why yet - could that be what you're seeing?

**Comment by tivec** [comment] 2017-02-03 13:22
I don't automatically load anything, I manually click "S-Panel" and then "Scan". I should note that I haven't got the system set up to be shown on top of the game at all, I run it on a separate window.

Here's a screenshot showing it. You can see my recent scan of d14-73 3 (as well as 1 and 2). The star was scanned yesterday, and that one showed up properly.

![EDDiscovery Window](http://i.imgur.com/NI8ZYEg.png)

**Comment by finwen** [comment] 2017-02-03 13:25
i have seen this problem once.  But it was 2am  2 days ago and was to tired to dig into that then.  Will keep an eye open for it again and see if i can find the cause

**Comment by klightspeed** [comment] 2017-02-03 14:20
Repro:
* Main travel control filters out scans, thus preventing it from invoking the Display method
* EDSM is checked
* system does not exist in System DB

Instances of SystemNode are compared, and since the `==` operator is not overridden, it uses the default `Object.Equals` method, which just checks if both left and right arguments are the same instance.

We probably need to check if the systems in the SystemNode are the same system if the new node doesn't have an EDSM ID.

**Comment by tivec** [comment] 2017-02-03 14:28
Awesome, glad to hear you've found the reason!

**Comment by phroggster** [comment] 2017-02-03 22:17
tivec, 5.3.4 is now out and it should address your issue. Since it sounds like an intermittent issue, I'm going to go ahead and close this ticket, but I want you to feel free to reopen it if you notice the problem again in 5.3.4 or newer. Hopefully that doesn't happen, but one never knows! o7

**Closed by phroggster** 2017-02-03 22:17 UTC
Labels: bug

**Comment by tivec** [comment] 2017-02-04 12:05
Alright, thank you. I'll take a look later tonight, see if it has been solved :)

**Comment by phroggster** [comment] 2017-02-04 14:02
By way of discord:

> Tivec said: Scan panel hasn't failed for several systems, and continued fine after a game restart where only part of the system was scanned. Seems to have solved the issue, but I'll keep my eyes open.
