### ISSUE TITLE
11.50 unhandled UI exception after complete FC jump

### ISSUE THREAD

**Issue by LethalByte** [EDDiscovery/EDDiscovery#2838] opened 2020-06-10 06:15 UTC
Fleet carries completed jump from SYNUEFE XU-N C20-1 to SYNUEFE PA-T C18-0 and when the jump was completed EDDiscovery generated an error. I re-opened and it generated another error and the History tab has a white box with a red cross.

This error copied below is the second error after re-opening EDDiscovery. The orginal error was in my clip board but I accidentally overwrite it with the second error.
![eddiscovery error](https://user-images.githubusercontent.com/36895470/84233353-17684500-aaea-11ea-8c74-6e103697415c.PNG)

`### Description

### Exception Details:
>EDDiscovery v11.5.0.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EDDiscovery.UserControls.UserControlTravelGrid.PaintEventColumn(DataGridView grid, DataGridViewRowPostPaintEventArgs e, Int32 totalentries, HistoryEntry he, Int32 hpos, Int32 colwidth, Boolean showfsdmapcolour) in C:\Code\EDDiscovery\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:line 674
>   at EDDiscovery.UserControls.UserControlTravelGrid.dataGridViewTravel_RowPostPaint(Object sender, DataGridViewRowPostPaintEventArgs e) in C:\Code\EDDiscovery\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:line 619
>   at System.Windows.Forms.DataGridView.OnRowPostPaint(DataGridViewRowPostPaintEventArgs e)
>   at System.Windows.Forms.DataGridViewRow.Paint(Graphics graphics, Rectangle clipBounds, Rectangle rowBounds, Int32 rowIndex, DataGridViewElementStates rowState, Boolean isFirstDisplayedRow, Boolean isLastVisibleRow)
>   at System.Windows.Forms.DataGridView.PaintRows(Graphics g, Rectangle boundingRect, Rectangle clipRect, Boolean singleHorizontalBorderAdded)
>   at System.Windows.Forms.DataGridView.PaintGrid(Graphics g, Rectangle gridBounds, Rectangle clipRect, Boolean singleVerticalBorderAdded, Boolean singleHorizontalBorderAdded)
>   at System.Windows.Forms.DataGridView.OnPaint(PaintEventArgs e)
>   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
>   at System.Windows.Forms.Control.WmPaint(Message& m)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>````

**Comment by klightspeed** [comment] 2020-06-10 06:17
Duplicate of #2833

**Closed by klightspeed** 2020-06-10 06:17 UTC
