### ISSUE TITLE
(A different from #1994) unhandled UI Exception

### ISSUE THREAD

**Issue by Tromador** [EDDiscovery/EDDiscovery#1995] opened 2018-06-15 00:47 UTC
### Exception Details:
>EDDiscovery v10.1.0.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at ExtendedControls.PictureBoxHotspot.AddTextFixedSizeC(Point topleft, Size size, String label, Font fnt, Color c, Color backcolour, Single backscale, Boolean centered, Object tag, String tiptext) in C:\Code\EDDiscovery\ExtendedControls\Controls\PictureBoxHotspot.cs:line 193
>   at EDDiscovery.UserControls.UserControlTrippanel.DisplayState(HistoryEntry he, HistoryEntry lastfsd) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlTrippanel.cs:line 154
>   at System.Action`2.Invoke(T1 arg1, T2 arg2)
>   at EDDiscovery.EDDiscoveryForm.<>c__DisplayClass97_0.<Init>b__6() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:line 274
>   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
>   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
>   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
>===== END =====
>```

**Comment by Tromador** [comment] 2018-06-15 00:51
It just popped up again when I refuelled. 
{"timestamp":"2018-06-15T00:48:57Z","event":"RefuelAll","Cost":15,"Amount":0.28019}

**Comment by klightspeed** [comment] 2018-06-15 01:35
This looks like a duplicate of #1976

**Comment by robbyxp1** [comment] 2018-06-15 06:20
And i wish i could reproduce..

**Comment by klightspeed** [comment] 2018-06-15 09:08
`OnEDSMSyncComplete` is subscribed to in `Init()`, but is not unsubscribed during `OnClose()`

`DiscoveryForm_OnEDSMSyncComplete` calls `DisplayState`, which calls `AddTextFixedSizeC`

**Comment by robbyxp1** [comment] 2018-06-15 09:09
okay will fix.

I have a fix for other problems being worked on .. will do that in same time.

thanks

**Comment by robbyxp1** [comment] 2018-06-15 09:58
Master updated

**Closed by robbyxp1** 2018-06-15 09:58 UTC
Labels: EDD Bug
