### ISSUE TITLE
Unhandled Exception upon start

### ISSUE THREAD

**Issue by Brokenpoet** [EDDiscovery/EDDiscovery#1458] opened 2017-11-11 02:10 UTC
### Description

Error occurred immediately following opening EDDiscovery.

### Exception Details:
>There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
>Parameter name: index
>   at System.Collections.ArrayList.get_Item(Int32 index)
>   at System.Windows.Forms.DataGridViewRowCollection.SharedRow(Int32 rowIndex)
>   at System.Windows.Forms.DataGridViewRowCollection.get_Item(Int32 index)
>   at EDDiscovery.UserControls.UserControlEngineering.Display()
>   at EDDiscovery.UserControls.ChangedSelectionHE.Invoke(HistoryEntry he, HistoryList hl)
>   at EDDiscovery.UserControls.UserControlTravelGrid.FireChangeSelection()
>   at EDDiscovery.UserControls.UserControlTravelGrid.HistoryChanged(HistoryList hl)
>   at System.Action`1.Invoke(T obj)
>   at EDDiscovery.EDDiscoveryController.RefreshHistoryWorkerCompleted(HistoryList hist)
>===== END =====
>```

**Comment by klightspeed** [comment] 2017-11-11 04:43
Duplicate of #1435

**Comment by phroggster** [comment] 2017-11-11 18:31
The fix (f7bd04cdef0e45cb7a3ea9d6c47435052e2ccf18) is already merged, should be resolved in the next release.

**Closed by phroggster** 2017-11-11 18:31 UTC
