### ISSUE TITLE
Null ref exception when clicking "New" on toolbar

### ISSUE THREAD

**Issue by benstaniford** [EDDiscovery/EDDiscovery#3472] opened 2024-01-21 11:34 UTC
### Description

I clicked on this to see what it was:

![image](https://github.com/EDDiscovery/EDDiscovery/assets/1592786/c176d772-eb80-451f-9dd4-3d99689c064f)

### Exception Details:
>EDDiscovery v17.0.1.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EDDiscovery.EDDiscoveryForm.extButtonNewFeature_Click(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\EDD\EDDiscoveryForm.cs:line 1172
>   at System.Windows.Forms.Control.OnClick(EventArgs e)
>   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
>   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
>   at System.Windows.Forms.Button.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by klightspeed** [comment] 2024-01-21 11:48
Duplicate of #3466 - fixed in 2833397

**Closed by klightspeed** 2024-01-21 11:48 UTC
