### ISSUE TITLE
Bulk deletion option for journal/history entries

### ISSUE THREAD

**Issue by CMDR-Cometborne** [EDDiscovery/EDDiscovery#1419] opened 2017-10-23 07:26 UTC
EDSM is getting somewhat sluggish on my system because I have about 280.000 entries in the history and journal.  A quick showed that about 50.000 of them are text messages from NPCs.

Right now, I can only delete them one at a time, which is not practical for 50.000 entries.  Can you please add some kind of bulk deletion, or tell me how I can delete them using third party tools.

**Comment by klightspeed** [comment] 2017-10-23 07:34
Using SQLite browser to open `EDDUser.sqlite` in `%LOCALAPPDATA%\EDDiscovery`,  you can delete NPC messages using the following query:
```
DELETE FROM JournalEntries WHERE EventType = 'ReceiveText' AND EventData LIKE '%"Channel": "npc"%'
```

**Comment by robbyxp1** [comment] 2017-10-25 08:02
The problem is, EDD is liable to pick them up again.. if you rescan the journal files 

The answer is to add a maximum age limit to entries that are read from the db into memory, via settings (I.e read all entries less than X months old).

**Comment by klightspeed** [comment] 2017-10-25 08:13
Entries that are hidden are not liable to be picked up again if the journal is re-scanned, since they are still linked to their source journal.  They are simply not included in the selection for the commander.

Limiting the journal entries read into memory to a certain age would need to make sure to include all of the necessary entries from the latest LoadGame before the start time.

**Comment by robbyxp1** [comment] 2017-10-28 16:17
I agree with Bravada thinking about it.. the best way to speed it up is just to highlight all the older ones and hide them.  Then they won't be read into memory the next time you run ED.

**Comment by robbyxp1** [comment] 2017-10-29 16:20
Closing as the hiding them is a good solution.

**Closed by robbyxp1** 2017-10-29 16:20 UTC
Labels: enhancement
