### ISSUE TITLE
Unhandled UI exeception

### ISSUE THREAD

**Issue by MarkSmith1974** [EDDiscovery/EDDiscovery#1492] opened 2017-11-20 13:34 UTC
### Description
Exiting EDD 8.4.1.0

### Additional Information
There was an unhandled UI exception.

==== BEGIN ====
CSCore.DirectSound.DirectSoundException (0x88780096): IDirectSoundBuffer::Stop caused an error: 0x88780096, "Unknown HRESULT".
   at CSCore.DirectSound.DirectSoundBuffer.Stop()
   at CSCore.SoundOut.DirectSoundOut.CleanupResources()
   at CSCore.SoundOut.DirectSoundOut.Dispose(Boolean disposing)
   at CSCore.SoundOut.DirectSoundOut.Dispose()
   at AudioExtensions.AudioDriverCSCore.Dispose() in C:\Users\klightspeed\git\EDDiscovery\Audio\AudioDriverCSCore.cs:line 127
   at EDDiscovery.EDDiscoveryForm.Controller_FinalClose() in C:\Users\klightspeed\git\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:line 941
===== END =====

### Exception Details:
>There was an unhandled UI exception.
>```
>==== BEGIN ====
>CSCore.DirectSound.DirectSoundException (0x88780096): IDirectSoundBuffer::Stop caused an error: 0x88780096, "Unknown HRESULT".
>   at CSCore.DirectSound.DirectSoundBuffer.Stop()
>   at CSCore.SoundOut.DirectSoundOut.CleanupResources()
>   at CSCore.SoundOut.DirectSoundOut.Dispose(Boolean disposing)
>   at CSCore.SoundOut.DirectSoundOut.Dispose()
>   at AudioExtensions.AudioDriverCSCore.Dispose() in C:\Users\klightspeed\git\EDDiscovery\Audio\AudioDriverCSCore.cs:line 127
>   at EDDiscovery.EDDiscoveryForm.Controller_FinalClose() in C:\Users\klightspeed\git\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:line 941
>===== END =====
>```

**Comment by klightspeed** [comment] 2017-11-20 18:29
Duplicate of #1437

**Closed by klightspeed** 2017-11-20 18:29 UTC

**Comment by phroggster** [comment] 2018-02-14 20:25
@MarkSmith1974 Please fill out the anonymous survey located at https://www.surveymonkey.com/r/2RJSWK7 to help us try and nail down a potential cause for this.
