### ISSUE TITLE
Feature Request: Allow systems with unknown coordinates in trilateration screen

### ISSUE THREAD

**Issue by mwerle** [EDDiscovery/EDDiscovery#87] opened 2016-01-27 10:16 UTC
Sometimes I want to trilaterate a (list of) different system to the one I'm in. Currently I use the EDSM website for that, but it would be great to be able to use EDDiscovery instead.

Currently the trilaterate screen only allows entering systems which have known coordinates.
If we could enter systems which don't have known coordinates, we could enter the distance from the current system to those, and eventually they will trilaterate on the EDSM servers once enough distances have been submitted for them.

**Comment by finwen** [comment] 2016-01-27 12:14
+1

**Comment by iainross** [comment] 2016-01-27 14:59
I was intending to have a poke at the available systems when trilaterating for https://github.com/EDDiscovery/EDDiscovery/issues/81 this weekend, I'll have a look at what seems sensible around this while I'm in there.

**Comment by iainross** [comment] 2016-01-31 23:07
I'm now submitting them OK - I've limited it to only allowing systems that EDSM already knows about to limit the opportunity for input errors.  Anyone (esp. @finwen, @AnthorNet) think that's a wrong route to go down?

Now I've just got to get a previously unknown system to trilaterate by adding distances like this to check the code I think will notify the EDD user that they've now fixed that system's position works as intended.  I may be some time - if it doesn't work first time I may be a very long time indeed :-\

**Comment by iainross** [comment] 2016-01-31 23:34
Take that pessimism!  Two more systems and the unknown one got a distance on EDSM, turned black on my Travel History and the status on the trilateration grid updated from "Position unknown" in orange to "Position Found" in green as hoped.

Fixing two systems' coordinates from one click of the 'Submit Distances' button is oddly satisfying - this could become a whole new game for some people, seeing how many systems they can fix from EDD at once...

I'll sort out a pull request shortly (or tomorrow).

**Closed** 2016-02-02 09:09 UTC
Labels: enhancement
