### ISSUE TITLE
unhandled UI exception.

### ISSUE THREAD

**Issue by Overcon** [EDDiscovery/EDDiscovery#2907] opened 2020-08-15 12:23 UTC
### Description
Closing 2D Map

### Additional Information
I was also manually uploading logs to Inara and EDSM

### Exception Details:
>EDDiscovery v11.6.2.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at ExtendedControls.ToolStripComboBoxCustom.get_SelectedItem() in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\ToolStrips\ToolStripComboBoxCustom.cs:line 69
>   at EDDiscovery.UserControls.UserControl2DMap.Display() in C:\Code\EDDiscovery\EDDiscovery\UserControls\ScansStars\UserControl2DMap.cs:line 111
>   at System.Action`1.Invoke(T obj)
>   at EDDiscovery.EDDiscoveryController.ForegroundHistoryRefreshCompleteonUI(HistoryList hist) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryControllerHistory.cs:line 192
>===== END =====
>```

**Comment by klightspeed** [comment] 2020-08-15 12:30
Duplicate of #2899, fixed in #2900, should be fixed in the next version.

**Closed by klightspeed** 2020-08-15 12:30 UTC
