### ISSUE TITLE
Voice Addon results in Unhandled UI Exception 

### ISSUE THREAD

**Issue by Lethann** [EDDiscovery/EDDiscovery#2350] opened 2019-01-19 03:05 UTC
### Description
Loading EDD after installing the Voice Pack v10 addon. I was laser mining asteroids for the DW2 CG. I'd get one *blah* was refined message then this exception would pop up.

### Exception Details:
```
>EDDiscovery v10.3.3.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at ActionLanguage.ActionRun.DoExecute() in C:\Code\EDDiscovery\ActionLanguage\ActionLanguage\ActionsCore\ActionRun.cs:line 209
>   at ActionLanguage.ActionRun.Tick_Tick(Object sender, EventArgs e) in C:\Code\EDDiscovery\ActionLanguage\ActionLanguage\ActionsCore\ActionRun.cs:line 235
>   at System.Windows.Forms.Timer.OnTick(EventArgs e)
>   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```
```

**Comment by klightspeed** [comment] 2019-01-19 05:34
Duplicate of #2339, fixed in 10.4

**Closed by klightspeed** 2019-01-19 05:34 UTC
