### ISSUE TITLE
EDDiscovery: error loading history v9.1.3.0

### ISSUE THREAD

**Issue by Xenserve** [EDDiscovery/EDDiscovery#1785] opened 2018-02-28 20:29 UTC
History Refresh Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at EliteDangerousCore.StarScan.ProcessElements(JournalScan sc, ISystem sys, SystemNode sn, String customname, List`1 elements, ScanNodeType starscannodetype, Boolean isbeltcluster) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\StarScan.cs:line 736
   at EliteDangerousCore.StarScan.Process(JournalScan sc, ISystem sys, Boolean reprocessPrimary) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\StarScan.cs:line 323
   at EliteDangerousCore.HistoryList.ProcessUserHistoryListEntries(Func`2 hlfilter) in C:\Code\EDDiscovery\EliteDangerous\HistoryList\HistoryList.cs:line 946
   at EliteDangerousCore.HistoryList.LoadHistory(EDJournalClass journalmonitor, Func`1 cancelRequested, Action`2 reportProgress, String NetLogPath, Boolean ForceNetLogReload, Boolean ForceJournalReload, Int32 CurrentCommander, Boolean Keepuievents) in C:\Code\EDDiscovery\EliteDangerous\HistoryList\HistoryList.cs:line 915
   at EDDiscovery.EDDiscoveryController.DoRefreshHistory(RefreshWorkerArgs args) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 811

**Comment by AndySpawn** [comment] 2018-02-28 21:44
Same issue here.  

It was working fine last night (v9.1.3.0), but then I got the "Fall Creators Update" of Windows this morning.  Tonight I started EDDiscovery to find a blank history, no Cmdrs, and the same error message as above.

**Comment by AndySpawn** [comment] 2018-02-28 21:51
Just instalied v9.1.4.0, and it's working

**Comment by klightspeed** [comment] 2018-02-28 22:46
Duplicate of #1770

**Closed by klightspeed** 2018-02-28 22:46 UTC
