### ISSUE TITLE
unhandled ui exception

### ISSUE THREAD

**Issue by rocknrollbetty** [EDDiscovery/EDDiscovery#2430] opened 2019-02-16 19:26 UTC
### Description
 flying in hyper drive. MAY have just done alt tab to check something. then noticed crash

### Exception Details:
>EDDiscovery v10.4.4.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.InvalidOperationException: Nullable object must have a value.
>   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
>   at EDDiscovery.UserControls.UserControlScanGrid.DrawSystem(HistoryEntry he, Boolean force) in C:\Code\EDDiscovery\EDDiscovery\UserControls\ScansStars\UserControlScanGrid.cs:line 197
>   at EDDiscovery.UserControls.ChangedSelectionHEHandler.Invoke(HistoryEntry he, HistoryList hl, Boolean selectedEntry)
>   at EDDiscovery.UserControls.UserControlTravelGrid.FireChangeSelection() in C:\Code\EDDiscovery\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:line 493
>   at EDDiscovery.UserControls.UserControlTravelGrid.AddNewEntry(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:line 389
>   at System.Action`2.Invoke(T1 arg1, T2 arg2)
>   at EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 454
>   at EDDiscovery.EDDiscoveryController.PlayJournalList() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 433
>   at EliteDangerousCore.EDJournalClass.ScanTickDone(List`1 entries) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\EDJournalClass.cs:line 184
>===== END =====
>```

**Comment by andrewhubb** [comment] 2019-02-17 00:58
I have the same error on startup. Clicking continue allows it to work.
This seems to have appeared since the notice about EGO.

**Comment by klightspeed** [comment] 2019-02-17 02:21
@rocknrollbetty OP is a duplicate of #2424.
@andrewhubb "nothing is updated" suggests it's a different error - please check the trace log (from `%LOCALAPPDATA%\EDDiscovery\Log` or `Data\Log` for portable versions) from when the error occurred, and report the error and stack trace in a new issue.

**Comment by andrewhubb** [comment] 2019-02-18 03:25
The error message displayed at the start is the same.

**Comment by klightspeed** [comment] 2019-02-18 04:34
If that is truly the case, then it should be fixed in the next version.  You can work around it by closing the scan grid tab.

**Comment by andrewhubb** [comment] 2019-02-18 11:29
Ok thanks I will try that.
I have That one open all the time.

**Comment by robbyxp1** [comment] 2019-02-22 13:55
Presume solved for next version.

**Closed by robbyxp1** 2019-02-22 13:55 UTC
Labels: EDD Bug
