### ISSUE TITLE
EDDiscovery not starting - stuck in "Repairing Canopy"

### ISSUE THREAD

**Issue by lemmy04** [EDDiscovery/EDDiscovery#2470] opened 2019-04-05 21:14 UTC
see subject - what do I do?

running 10.5.4 on Windows 10 Pro, didn't have problems so far, but all of a sudden it doesn't start anymore.

**Comment by lemmy04** [comment] 2019-04-05 21:26
running version 10.5.4 here.

**Comment by klightspeed** [comment] 2019-04-05 23:47
This can usually be caused by quitting the program during the system DB index rebuild, resulting in the DB library rebuilding the index during startup.

Please try removing EDDSystem.sqlite from your EDDiscovery data directory (`%LOCALAPPDATA%\EDDiscovery`, or if using the portable version then the `Data` directory in your install directory)

**Comment by robbyxp1** [comment] 2019-04-19 15:36
Closing, no more response from user

**Closed by robbyxp1** 2019-04-19 15:36 UTC
Labels: Help Request

**Comment by lemmy04** [comment] 2019-05-06 15:47
oops - forgot to update.
I just let it sit and grind over night, and next morning all was well.

**Comment by klightspeed** [comment] 2019-05-06 15:51
This suggests that indeed it was quit while rebuilding the index, and so the DB library rebuilt the library when the database was opened.
