### ISSUE TITLE
Switching to XAML/WPF?

### ISSUE THREAD

**Issue by chriszero** [EDDiscovery/EDDiscovery#1881] opened 2018-03-30 10:12 UTC
What about switching the whole UI zu XAML/WPF, using a pattern like MVVM?
Would be truly a big milestone and involve a lot of code changes.
I'm willing to help.

Chris

**Comment by andreaspada** [comment] 2018-03-30 15:16
Wow... it's not a big milestone, it's an HUGE milestone! I''m not sure it can be done, or at what extent could be done. However, I currently noticed that there are situation - Grid, Panels management, etc... - which could benefit a lot from a MVVM perspective. Personally, I'm toward a modular design.

@robbyxp1 is the guy to speak with. He is the project administrator and the bigger code contributor.

Why didn't you prepare a mockup, like a GUI suggestion, and present it to the developers team? If there are enough interested developers, you could work in a fork. Then, having some measurable benefits, I don't see why this couldn't be adopted. ;)

**Comment by klightspeed** [comment] 2018-03-30 15:35
I think the first step before any alternate UI framework would be converting the controls, forms and main container to MVVM (much like what is done with e.g. Xamarin.Forms).  After that, it might be possible to plug different UI views onto the underlying view models.

The MVVM conversion would be on a similar sort of scope to the separation of logic and UI we did in 8.2

**Comment by robbyxp1** [comment] 2018-03-30 16:03
The answer is, not by me ;-)  We have this thing working fine, with transparency etc.  

There is no reason someone could not make another EDDiscovery??? project  and use the common DLLs to do something like that.

But since maintaining the current stuff, keeping up with Frontier, takes a great portion of my time as it is i'm not going to be joining in.  

The main EDDiscovery will stay a Windows Forms program, which as we have it now presents a good visual appearance.

I suggest we continue concentrating on adding features to the current program rather than re-engineering it.

Closing as its not a bug or an enhancement - its a new project!

**Closed by robbyxp1** 2018-03-30 16:03 UTC

**Comment by klightspeed** [comment] 2018-03-30 16:24
Also, playing on the other side of the fence to a WPF conversion, System.Windows.Forms is currently supported to some extent by all desktop platforms for which either DotNET is supported (whether through the DotNET framework or through Mono).

Still, I don't think migrating at least some controls to MVVM is out of the question.  With that, we could replace the old EDDiscovery.Mac project with a Xamarin.Mac port of EDDiscovery.

**Comment by andreaspada** [comment] 2018-03-30 16:34
Maybe, does not the containers could be better as a WPF? The already implemented tiling and dockable features are very useful...
