### ISSUE TITLE
Small improvement in floating panel/windows

### ISSUE THREAD

**Issue by andreaspada** [EDDiscovery/EDDiscovery#1147] opened 2017-07-31 16:37 UTC
I fly using mouse and keyboard. I like to have a Summary panel on my left side of the screen which gave me just the distance to my target and which shows scan information. I left it transparent and on top.

Sometime, my mouse pointer goes on that windows, which highlight it, which is quite annoying. I understand that we need to properly highlight a panel if we need to move or change it's setup, but I would suggest to let it be unresponsive to mouse hover unless we click on it (or, better, unless we select it by task selector or windows switch hotkeys).

What do you think about?

**Comment by phroggster** [comment] 2017-08-01 16:56
I agree that something needs to be done about this. However, it's quite complicated, as the mouse capture gets stolen from EliteDangerous if it enters another window, even if it's a transparent window on top of Elite. Not sure that it's even possible to implement something to solve this, but I'll do some research and see.

**Comment by klightspeed** [comment] 2017-08-01 17:05
As in WM_NCHITTEST returns HT_TRANSPARENT?

**Comment by robbyxp1** [comment] 2017-08-01 20:40
We need a way of activating the spanel ;-)  If you flying with your mouse, ED should have captured it and the mouse pointer will not be moving around. In a station, you can minimise the panel (dock option) to stop the mouse pointer in the station getting caught by the window.

**Comment by phroggster** [comment] 2017-08-01 20:50
ED running in full-screen borderless does capture the mouse, and it works perfectly fine. The problem is when a window gets placed over the top of it, then capturing gets to be problematic.

HT_TRANSPARENT and WS_LAYERED / WS_TRANSPARENT might be part of a solution, but it's only a part. Some clever hacks will probably need to be employed to have it behave sensibly.

Again, I do feel that this is a problem, but any solution has a high chance of making a slightly different problem worse.

**Comment by klightspeed** [comment] 2017-08-01 22:39
This gets a form that is completely transparent to mouse input:

```
    public partial class Form1 : Form
    {
        const int WS_EX_TRANSPARENT = 0x00000020;

        public Form1()
        {
            InitializeComponent();
            this.AllowTransparency = true;
            this.TransparencyKey = this.BackColor;
            this.TopMost = true;
        }

        protected override CreateParams CreateParams
        {
            get
            {
                CreateParams p = base.CreateParams;
                p.ExStyle |= WS_EX_TRANSPARENT;
                return p;
            }
        }
    }
```

Unfortunately setting and resetting this after window creation requires a call to GetWindowLong and SetWindowLong, as System.Windows.Forms provides no way to change extended styles after window creation.

**Comment by andreaspada** [comment] 2017-08-01 22:56
Maybe, an additional/alternative Spanel which is always transparent could solve that. 

Quoting Ben Peddell:

> This gets a form that is completely transparent to mouse input:
> 
> ```
>     public partial class Form1 : Form
>     {
>         const int WS_EX_TRANSPARENT = 0x00000020;
> 
>         public Form1()
>         {
>             InitializeComponent();
>             this.AllowTransparency = true;
>             this.TransparencyKey = this.BackColor;
>             this.TopMost = true;
>         }
> 
>         protected override CreateParams CreateParams
>         {
>             get
>             {
>                 CreateParams p = base.CreateParams;
>                 p.ExStyle |= WS_EX_TRANSPARENT;
>                 return p;
>             }
>         }
>     }
> ```
> Unfortunately setting and resetting this after window creation requires a call to GetWindowLong and SetWindowLong, as System.Windows.Forms provides no way to change extended styles after window creation.

So, if we have an additional spanel which is coded to be only transparent, it could solve one problem without create other troubles. I'm correct or I totally misunderstood everything? lol

**Comment by klightspeed** [comment] 2017-08-01 23:53
In order to do anything with the panel once it is made transparent, we would need to either have a Window menu to select and focus panel windows, or have a timer that polls the mouse position and clears WS_EX_TRANSPARENT if the mouse hovers over part of the panel.

**Comment by andreaspada** [comment] 2017-08-02 01:35
How about a definable hotkey to select and focus panel windows? Kind of a an Alt+Tab which scroll through the opened panel...

**Comment by phroggster** [comment] 2017-08-03 01:14
It's not terribly informative, but I put together an app to test various opacity options for forms appearing over the top of EliteDangerous. https://youtu.be/lG-4FAnJt7Q The way to go seems to be to keep the transparency key, even on mouse over, and not change it like we do presently. The sub-controls will still get clicks and behave normally, provided that the cursor is over a colour that isn't the transparency key. A border colour will have to be used for resizing the form, but that's trivial.

**Comment by andreaspada** [comment] 2017-08-03 01:50
Wow, that's pretty amazing... seems very promising! Thanks for the time and effort you put on that test.

**Comment by robbyxp1** [comment] 2017-09-01 14:07
Lets not change anything. The reason for transparency off during mouse over is due to being able to see the forms for ones with minimal visible icons on there.  I don't want that turned off.  This is the only report of people having problems with this feature, unless there is a mass of complaints lets leave it all alone.

**Comment by robbyxp1** [comment] 2017-09-11 13:36
Committed a version which addresses this. For 8.3 Use mode 'Tf' to select a completely inert view.

**Closed** 2017-09-13 14:47 UTC
Labels: enhancement, For 8.3
