### ISSUE TITLE
v6.1.1.0 announcing unscanned planets

### ISSUE THREAD

**Issue by Disorganise** [EDDiscovery/EDDiscovery#879] opened 2017-03-03 09:29 UTC
For some reason, when jumping into a system, EDD is now telling me all the body names and whether they a landable or not.  It is probably off the ADS scan, but definitely I have not DSS'd and so they appear as unexplored in the nav panel etc.  If I do a DSS, then that gets read and it stops the previous notification.

Personally I would prefer to not have this read out as it does not match the in-game gui which says unexplored until we detail scan

**Comment by klightspeed** [comment] 2017-03-03 11:29
Is this in the E:D 2.3 beta, or in E:D 2.2.03?

Do you have the EDSM button enabled on the Scan panel?

**Comment by Disorganise** [comment] 2017-03-03 12:24
2.2.03.  I do have beta access and downloaded it, but I haven't actually tried playing it yet.

The EDSM button is black background which I assume is 'off' - population wise it shows the main star and any very near stars.  I've been doing the current CG and everytime I enter prism it rattles off the bodies.  In this case they're named (without scanning).

[img]http://i.imgur.com/e8IKndw.png[/img]

**Comment by klightspeed** [comment] 2017-03-03 12:38
The presence of the unscanned "Main Body" placeholder suggests that the EDSM button has been toggled during the current session while the Prism system was selected.

The TTS is probably not filtering out EDSM bodies when the EDSM button on the scan panel is off.

Clicking refresh should clear out the fetched data from EDSM - it is not persisted.

**Comment by Disorganise** [comment] 2017-03-03 23:55
The main body had disappeared overnight, but nonetheless I hit refresh
http://i.imgur.com/BFMReFh.png

Confirming still 'blank' on re-entry
http://i.imgur.com/qPntrd9.png[/img]

but the reading begins.  Timing wise I'm thinking the passive scan triggers it?
https://youtu.be/SASNWorBBgE

**Comment by klightspeed** [comment] 2017-03-04 18:10
The delay sounds like it fetched the bodies from EDSM.

**Comment by klightspeed** [comment] 2017-03-04 18:29
https://github.com/EDDiscovery/EDDiscoveryData/blob/master/ActionFiles/V1/VoicePackV2.act#L3736 requests a scan of the system, requesting info from EDSM.  If you don't want it to request info from EDSM, I would guess you would remove the `EDSM  ` from the program step.

**Comment by Disorganise** [comment] 2017-03-05 20:03
Still happening in 6.1.2.   I switched off the voicepack in 6.1.1 as I was playing with HCS voice.  Downloaded 6.1.2 this morning and installed.  Did not touch any buttons (I haven't knowingly selected show bodies from EDSM anyway aside from when it first became an option and wanted to see what it did).

Got to head to work but hopefully the video will upload in the meantime.  There were a few 1st visits
https://youtu.be/hjfFNWIJxMc

out of curiosity, should this be unticked?  I always assumed it was to keep the travel log in sync (I occasionally move PC's

trace associated with the video
[2017-03-06 06:43:00Z] New entry 5/03/2017 7:42:59 PM Undocked
[2017-03-06 06:43:18Z] New entry 5/03/2017 7:43:17 PM ReceiveText
[2017-03-06 06:43:57Z] New entry 5/03/2017 7:43:56 PM FSDJump
[2017-03-06 06:43:57Z] Arrived at system: Core Sys Sector ZJ-R a4-2 1:th visit.
[2017-03-06 06:43:58Z] Update sync flag ID 36992 with 1
[2017-03-06 06:44:43Z] New entry 5/03/2017 7:44:42 PM FSDJump
[2017-03-06 06:44:44Z] Arrived at system: ICZ EB-X c1-28 1:th visit.
[2017-03-06 06:44:45Z] Update sync flag ID 36993 with 1
[2017-03-06 06:45:12Z] New entry 5/03/2017 7:45:10 PM FuelScoop
[2017-03-06 06:45:40Z] New entry 5/03/2017 7:45:40 PM FSDJump
[2017-03-06 06:45:40Z] Arrived at system: Cemiess 5:th visit.
[2017-03-06 06:45:41Z] Update sync flag ID 36995 with 1
[2017-03-06 06:46:11Z] New entry 5/03/2017 7:46:10 PM FuelScoop
[2017-03-06 06:46:45Z] New entry 5/03/2017 7:46:44 PM FSDJump
[2017-03-06 06:46:45Z] Arrived at system: Liabeze 14:th visit.
[2017-03-06 06:46:46Z] Update sync flag ID 36997 with 1
[2017-03-06 06:48:47Z] New entry 5/03/2017 7:48:46 PM SupercruiseExit
[2017-03-06 06:48:58Z] New entry 5/03/2017 7:48:56 PM DockingRequested
[2017-03-06 06:49:00Z] New entry 5/03/2017 7:48:56 PM ReceiveText
[2017-03-06 06:49:02Z] New entry 5/03/2017 7:48:58 PM ReceiveText
[2017-03-06 06:49:02Z] New entry 5/03/2017 7:48:58 PM DockingGranted
[2017-03-06 06:49:06Z] New entry 5/03/2017 7:49:05 PM ReceiveText
[2017-03-06 06:49:40Z] New entry 5/03/2017 7:49:39 PM ReceiveText
[2017-03-06 06:49:59Z] New entry 5/03/2017 7:49:58 PM Docked

http://i.imgur.com/JpyaBxB.png

**Comment by klightspeed** [comment] 2017-03-05 21:42
It is requesting bodies from EDSM.
https://www.edsm.net/en/system/bodies/id/21012/name/Core+Sys+Sector+ZJ-R+a4-2
https://www.edsm.net/en/system/bodies/id/30414/name/ICZ+EB-X+c1-28
https://www.edsm.net/en/system/bodies/id/2670/name/Cemiess
https://www.edsm.net/en/system/bodies/id/11255/name/Liabeze

If you don't want the program to announce system data from EDSM, then:
* From the Add-Ons menu, click Edit Add-On Action Files
* From the Program dropdown, select `SaySystemInfo`
* Find the `Scan` line, and remove the `EDSM` prefix
* Click OK
* Click OK

**Comment by robbyxp1** [comment] 2017-03-06 21:35
Or set verbose number to zero. Next version will have more control! The delay is intentional to stop too much voice immediately after arriving.

Closing as working as intended

**Closed by robbyxp1** 2017-03-06 21:35 UTC
