### ISSUE TITLE
EDDiscovery v12.0.2.0 There was an unhandled UI exception.

### ISSUE THREAD

**Issue by Brunhine** [EDDiscovery/EDDiscovery#3084] opened 2021-05-21 00:07 UTC
### Description
I clicked the clear button on the shopping list window after dragging some things around.

### Exception Details:
>EDDiscovery v12.0.2.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
>Parameter name: index
>   at System.Collections.ArrayList.get_Item(Int32 index)
>   at System.Windows.Forms.DataGridViewRowCollection.SharedRow(Int32 rowIndex)
>   at System.Windows.Forms.DataGridViewRowCollection.get_Item(Int32 index)
>   at EDDiscovery.UserControls.UserControlEngineering.buttonClear_Click(Object sender, EventArgs e) in C:\Code\Examples\EDDiscovery\EDDiscovery\UserControls\EngineeringSynthesis\UserControlEngineering.cs:line 447
>   at System.Windows.Forms.Control.OnClick(EventArgs e)
>   at System.Windows.Forms.Button.OnClick(EventArgs e)
>   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
>   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
>   at System.Windows.Forms.Button.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by robbyxp1** [comment] 2021-05-23 08:59
Found, thanks

**Comment by robbyxp1** [comment] 2021-05-23 11:38
Can't reproduce after 1 go.

Fixed number of rows in the DGV (visible is used to hide them).

**Comment by robbyxp1** [comment] 2021-06-03 20:22
Closing as currently unreproduceable.

**Closed by robbyxp1** 2021-06-03 20:22 UTC
Labels: EDD Bug
