### ISSUE TITLE
CAPI not responding to user login- Console Commander, 12.0.2.0

### ISSUE THREAD

**Issue by elinielsen13** [EDDiscovery/EDDiscovery#3071] opened 2021-05-14 21:10 UTC
Hi,  

I can't seem to get any statistics to display for any period of time on the Stats Panel other than my number of jumps. It does seem to be able to read my jump history mostly correctly, with everything displaying correctly on the "General" tab. However, just moving over to the "Travel" tab, and the only stat that's apparently counted is the "Jumps". It has not counted jet cone boosts, scans, mapped, or scan value. Similarly, the "Scan" tab only displays zeroes. The "In-Game" and "By Ship" tabs are completely blank. 

I'm unsure if this is intended behavior for these tabs for console commanders. I play on Xbox, and have synced correctly with the Frontier CAPI, and have had no issues with the API keys for EDSM and Inara. If EDDI cannot support counting these statistics,I understand, and I apologize for the issue report. However, if it's meant to work for console commanders as well, I was hoping to be able to use EDDI for easier access to some stats. I'm not sure if the Stats Panel is just trying to look for journals on my PC that I don't have instead of looking at the EDSM/CAPI data or if there's something else going on.

**Comment by Eahlstan** [comment] 2021-05-14 21:14
Please send a screenshot of your statistics panel.

**Comment by elinielsen13** [comment] 2021-05-14 21:27
Sure thing, here's all my tabs of the statistics panel:

![image](https://user-images.githubusercontent.com/36246270/118333296-b058ca80-b4c8-11eb-9ae1-c7e73a61a364.png)
![image](https://user-images.githubusercontent.com/36246270/118333318-b8b10580-b4c8-11eb-9267-f5be24a48dde.png)
![image](https://user-images.githubusercontent.com/36246270/118333328-be0e5000-b4c8-11eb-8f66-762c6360bf99.png)
![image](https://user-images.githubusercontent.com/36246270/118333349-c797b800-b4c8-11eb-9d5c-5321ca012832.png)
![image](https://user-images.githubusercontent.com/36246270/118333368-d2524d00-b4c8-11eb-8c2f-2340b877dfcf.png)

And here's the history panel when searching for 'jet':

**Comment by Eahlstan** [comment] 2021-05-14 21:30
Ok, so one thing is sure: You don't have any jet cone boosts stored in your history, so they can't be counted.
Now please do a search for 'scan' on your history tab and screenshot that.

**Comment by elinielsen13** [comment] 2021-05-14 21:32
Sure.
![image](https://user-images.githubusercontent.com/36246270/118333753-82c05100-b4c9-11eb-9aea-872add50e85c.png)

Also seemingly not stored in my history.

**Comment by Eahlstan** [comment] 2021-05-14 21:42
So, no scan events either...

Thanks for those infos, now we have to wait for @robbyxp1 as he knows if the CAPI should import those things.

Also please screenshot your history tab one last time (at least for me) without any searches.

**Comment by elinielsen13** [comment] 2021-05-14 21:43
Alrighty, no problem.
![image](https://user-images.githubusercontent.com/36246270/118334585-22321380-b4cb-11eb-8b43-7bdf5497ab66.png)

**Comment by iainross** [comment] 2021-05-14 21:48
On the `Settings` tab, what do you have in the two dropdowns in the box labelled `Memory`?

**Comment by elinielsen13** [comment] 2021-05-14 21:49
Here's what I've got:
![image](https://user-images.githubusercontent.com/36246270/118335033-f6635d80-b4cb-11eb-864e-b1164056b354.png)

**Comment by iainross** [comment] 2021-05-14 21:51
OK, so you're not unloading all the journals it needs to compile the rest of the stats so it's not that.

**Comment by elinielsen13** [comment] 2021-05-14 21:53
Is there something else I can get a screenshot of to help on your end?

**Comment by Eahlstan** [comment] 2021-05-14 22:05
> OK, so you're not unloading all the journals it needs to compile the rest of the stats so it's not that.

Just as an info:

The statistics panel is independent of this settings since a while now, so even if he filtered those in the settings they would be missing everywhere except the statistics panel :)

**Comment by klightspeed** [comment] 2021-05-15 07:33
> Alrighty, no problem.
> ![image](https://user-images.githubusercontent.com/36246270/118334585-22321380-b4cb-11eb-8b43-7bdf5497ab66.png)

That looks like it only includes the travel history imported from EDSM, and not any data from the Companion API.

Could you please check if any other commanders have been created?  As the CAPI import does not directly import the journal, but rather dumps them into the journals directory and has the normal journal reading code process them, the commander won't have the `[C]` prefix unless you actually have that in your commander name.

One weakness in the above is that any sessions that go past midnight UTC will be broken, as CAPI journals are divided by date and not by session.

**Comment by robbyxp1** [comment] 2021-05-15 07:47
Just a little correction. The CAPI read journals are dumped into appdata\eddiscovery\capi.  The commander name in the journal entries is replaced by the name assigned to commander in EDD, so if you've called it [C] Fred in EDD, that is what ends up in the journal logs stored in \capi.  

See if there are any journal logs in the %appdata%\eddiscovery\capi folder.

**Comment by klightspeed** [comment] 2021-05-15 08:14
> See if there are any journal logs in the %appdata%\eddiscovery\capi folder.

I think that should be `%LOCALAPPDATA%\EDDiscovery\CAPI`

**Comment by elinielsen13** [comment] 2021-05-16 18:26
I apologize it's taken me so long to get back to y'all, things have been a bit hectic around here.

As far as I can tell, there's no other created commanders:

![image](https://user-images.githubusercontent.com/36246270/118407890-0ef48480-b640-11eb-859e-a4868355d669.png)
![image](https://user-images.githubusercontent.com/36246270/118407950-6561c300-b640-11eb-99e5-a9d63d88ded2.png)
I believe this is also the journal file, though I admit I'm not familiar with CRED files, so I'm unsure if this what you'd expect to find in `%LOCALAPPDATA%\EDDiscovery\CAPI` normally.

I'm not entirely clear why the [C] was added to the name, I did not manually put that in. I'd just assumed it was a function of EDD. This is what I have just looking at the commander profile on EDD.
![image](https://user-images.githubusercontent.com/36246270/118408148-65ae8e00-b641-11eb-8bb7-6130b642effa.png)

**Comment by Eahlstan** [comment] 2021-05-16 18:40
"[C]" is just a hint that this is a console commander.
The bad thing is that we didn't have any console commanders during the beta so this whole thing could still be buggy.

Could you please scan your whole PC for *.log files? Maybe they were written to the wrong directory.
(Most likely you will find many log files, the one we're looking for should start with "journal".)

**Comment by elinielsen13** [comment] 2021-05-16 19:11
> "[C]" is just a hint that this is a console commander.

Gotcha.

Did a search for *.log, didn't end up coming up with any journals as far as I could tell, going through the results.

Followed that up with a search for journal*.log, came up with nothing.
Searching for my commander name only resulted with CRED file from above.

**Comment by Eahlstan** [comment] 2021-05-16 19:14
Hm.
There's a hlog file in EDDs log folder. In theory it contains all outgoing requests and the answers. So it might contain infos about the CAPI request. The problem is that it contains all your API keys in plain text so uploading it here wouldn't be good.
Are you on Discord?

**Comment by elinielsen13** [comment] 2021-05-16 19:15
I am, yes.

**Comment by Eahlstan** [comment] 2021-05-16 19:16
Please join the EDDiscovery Discord and ping me.

https://discord.gg/uBq3UHq

**Comment by Eahlstan** [comment] 2021-05-16 19:49
TIE sent me the credential file.
That's what I get when I use it:
![Screenshot 2021-05-16 214619](https://user-images.githubusercontent.com/59618179/118410598-8520d780-b690-11eb-8903-5a69597260a8.JPG)

And that's when I use my non console commander:
![Screenshot 2021-05-16 214716](https://user-images.githubusercontent.com/59618179/118410607-92d65d00-b690-11eb-8fd9-b9b30e54eea4.JPG)

So the service  is up.

**Comment by robbyxp1** [comment] 2021-05-16 19:59
[2021-05-16T03:09:42.652Z] Journal Check day 2021-04-18 @ 2021-05-16T03:09:41.391Z
[2021-05-16T03:09:42.652Z]   No response to 2021-04-18 will try again

The capi server is not talking to you, for some reason, although you are logged in.

Are you a EPIC account btw? Bought thru EPIC?

**Comment by elinielsen13** [comment] 2021-05-16 20:16
Could be. I'll try what @Eahlstan suggested to me, and leave EDSM closed for several hours then try and boot up EDD again and see what happens.

**Comment by elinielsen13** [comment] 2021-05-17 00:16
Well, I gave it about four hours, but I'm not sure if anything's changed. I did notice, though, that the log on the history tab sometimes gives this when re-authorizing.

> CAPI Awaiting Callback
CAPI Require Log in
CAPI Awaiting Callback
CAPI Authorized
CAPI Authorization Failed

Other times, though, there's no "Authorization Failed" text. 

Refreshing the history doesn't seem to be changing anything, the latest entry is where I left off with EDSM several hours ago.

**Comment by robbyxp1** [comment] 2021-05-17 07:27
Most likely due to Frontier rejecting your login. That would produce an authentication failed message.

I'm not sure how to solve it from our end, Frontier is rejecting your login attempts from EDD or not serving you journals.  You can try deleting the .cred files in the CAPI folder, but i'm not sure that will make a difference.

**Comment by elinielsen13** [comment] 2021-05-17 14:45
Hm, I'll give it a shot. I've not had any issues logging into Frontier, and I'm able to pull my journal with an API request through Insomnia just fine, so I wonder why it's acting so strange with EDD.

Well, I'll try deleting the .cred and log back in to see if that makes any difference.

**Comment by elinielsen13** [comment] 2021-05-17 14:51
Well, like you suspected, that didn't seem to make much of a difference.

But something I noticed when going to delete the .cred, there were two journals for 4/19 and 4/20, and it seems EDD is reading them just fine. Judging by the time the files were created, they got pulled the last time I tried opening EDD. No idea why it pulled those two particular dates and not anything before or after them.

**Comment by elinielsen13** [comment] 2021-05-17 14:57
Wait, I'm not exactly sure what changed, but I tried re-authorizing again, and it seems the CAPI is pulling my journals now. Will update in a bit.

**Comment by elinielsen13** [comment] 2021-05-17 15:09
Alright, it seems that EDD has pulled all my journals from 4/19 til the present and EDD is showing them like it ought to. 

![image](https://user-images.githubusercontent.com/36246270/118511668-5e45be00-b6ef-11eb-862d-949735f5b1e1.png)
![image](https://user-images.githubusercontent.com/36246270/118511699-67cf2600-b6ef-11eb-8426-ef63ddc9cf03.png)

Still not exactly sure what did the trick. Is there any kind of info you'd like me to pass on like the logs? I understand there weren't any console commanders to beta test, so I'm happy to offer any help or suggestions I can.

**Comment by Eahlstan** [comment] 2021-05-17 17:17
Frontier only stores journals for about a month, so there simply aren't more stored journal to pull.
We do have your logs from the times it failed, so there's no benefit in sending logs where everything works, but thank you :)

Glad it works now.

**Comment by elinielsen13** [comment] 2021-05-17 17:28
Gotcha. 

Well, I hope I can keep it working! 
If I can offer a suggestion, I do think I would find it helpful if there were a polling rate faster than every 30 minutes. I know it obviously can't be equal to how EDD works for PC commanders, but even if it were similar to EDSM in polling the CAPI every 3 minutes, that'd make it all the more useful. :)

**Comment by robbyxp1** [comment] 2021-05-18 07:26
I've experimented with the frontier servers, and seen journals taking a long time to appear on it from the point of creation.

I'll discuss that idea with the powers that be.

**Comment by robbyxp1** [comment] 2021-05-18 11:58
Since it seems to work, closing

**Closed by robbyxp1** 2021-05-18 11:58 UTC
Labels: Frontier Journal Error
