### ISSUE TITLE
Exception:Newtonsoft.Json.JsonReaderException:Unexpected character

### ISSUE THREAD

**Issue by Ohmegalisk** [EDDiscovery/EDDiscovery#1413] opened 2017-10-20 08:51 UTC
Got an Error after running the Program for 10sec
[Trace_20171020104505.0.log](https://github.com/EDDiscovery/EDDiscovery/files/1401275/Trace_20171020104505.0.log)

**Comment by AnthorNet** [comment] 2017-10-20 08:52
Duplicate of #1412

**Closed** 2017-10-20 08:53 UTC
