### ISSUE TITLE
Startup settings lost, left hand panel disappears

### ISSUE THREAD

**Issue by DRY411S** [EDDiscovery/EDDiscovery#1508] opened 2017-11-29 20:24 UTC
Sometimes starting up, EDDiscovery just shows the right hand grids.

Once it does, I can find no way of getting the left hand panel back except uninstalling and reinstalling.

**Comment by phroggster** [comment] 2017-11-29 21:34
Can you provide a screen shot of that occurring? Odd that reinstalling the application resolves this. Not sure what's going on here.

**Comment by DRY411S** [comment] 2017-11-29 21:38
Uninstalling and clearing all settings did the trick last time. This time
it hasn't. The left hand panel can be seen here with minimal width. I
cannot widen it

[image: Inline images 1]


Dave Ryalls
Mobile: 07753 366478
Email: dsryalls@gmail.com

**Comment by phroggster** [comment] 2017-11-29 21:40
Images from email replies don't transfer over. Probably easiest to post a link to it elsewhere, or open the reply form in the web browser and drag and drop the image in.

**Comment by DRY411S** [comment] 2017-11-29 23:30
![image](https://user-images.githubusercontent.com/19732374/33404713-46e88336-d55d-11e7-880a-0d797c3379bf.png)

**Comment by iainross** [comment] 2017-11-29 23:35
There's definitely no grabby doodad appearing as the mouse pointer if you hover just to the right of the scroll bar to let you drag it to the right?

Have you tried launching in safe mode and resetting window positions - https://github.com/EDDiscovery/EDDiscovery/wiki/Safe-Mode ?

**Comment by phroggster** [comment] 2017-11-29 23:35
Just to the right of the vertical scroll bar, you can resize the panels. Click and drag it to the right, and this should hopefully be resolved.

I've seen this occur after starting EDD up on a different monitor then normal.

**Comment by DRY411S** [comment] 2017-11-29 23:50
> There's definitely no grabby doodad appearing as the mouse pointer if you hover just to the right of the scroll bar to let you drag it to the right?

Yes there is!

> Have  you tried launching in safe mode and resetting window positions - 

That works thanks

> I've seen this occur after starting EDD up on a different monitor then normal.

I have 4 monitors. It's possible that I start it on one monitor, then move it, then close it down on the 2nd monitor. Could that be the cause?

**Comment by phroggster** [comment] 2017-11-30 01:11
Without finding the exact line of code that's causing the problem, I can only speculate. But I imagine that something is using screen coordinates instead of client coordinates to compute where the slider should be positioned (or where the slider is positioned, if the problem is during saving instead of loading). Screen coordinates can be negative numbers, or particularly large, and the application just kind of freaks out when loading with an odd value.

**Comment by phroggster** [comment] 2017-11-30 02:01
Can you provide a screenshot of the entire window, or a description of which sub-panels you're using and where? I'm wondering if it's one of the individual sub-panels that is causing the problem, not the `UserControlHistory` that is responsible for the layout of the sub-panels.

**Comment by DRY411S** [comment] 2017-11-30 02:07
I'll do screengrabs the next time it happens.

**Comment by phroggster** [comment] 2017-11-30 02:20
It doesn't *need* to be occurring in the screenshot, I just want to know which sub-panels you're using since that may be what is causing (or exacerbating) this issue. I've personally seen it occur with the default layout, but it may occur more frequently with a certain panel type in the top-right, or bottom-left, or ... There's just a lot of variables at play, and I'd like to try and pin a few of them down to help narrow down the source.

And it's because I can't get it to occur for me now, despite aggressively trying to trigger it. ;-)

**Comment by Taomyn** [comment] 2017-12-03 10:51
This happens to me every time I restart now, happened ages ago then it stopped for a few months, but the past week it's each time I start the application. Here is my normal layout.

![image](https://user-images.githubusercontent.com/4365929/33524587-32f5c04e-d820-11e7-9b00-a467541bf2b5.png)

**Comment by DRY411S** [comment] 2017-12-03 13:02
It's just happened to me again. I note 2 things.

1) The 'Fill screen' option isn't available top right of the application window.
2) Dragging the window to the top of the monitor doesn't make the window resize to fill the monitor.

![image](https://user-images.githubusercontent.com/19732374/33525475-2a63bf50-d828-11e7-8c7d-8c5162acfb9c.png)

If it helps diagnosis, it is the right-most monitor (identified by Windows as monitor 3) of 3 all running as separate monitors, all at resolution of 1920 x 1200.

**Comment by phroggster** [comment] 2017-12-03 15:30
@Taomyn How many monitors are you running, and what are the resolutions and virtual layout of them (side-by-side, top-to-bottom, etc.)?

@DRY411S  Yeah, I never got around to adding the maximise/restore button when themed without the window frame (as visible in Taomyn's screenshot above), and Windows's Aerosnap functionality (the drag-to-top to maximise, or drag-to-left-or-right-side to panelize) also doesn't work without this frame. However, if the window is already maximised, you should be able to drag the window down from the top edge in order to restore it. Basically Microsoft's way of saying "You should always have the 'ugly' window frame because it's virtually impossible to mimic all of the interface functionality without it." Well, we've gotten about as close as we can, but there's still some rough spots that'll probably never get sorted out.
For both of you: I've gone over this code with a fine-toothed comb since this issue was created, and I don't see what could be causing these problems. That's not to say that there isn't a problem, just that it's not clear what the problem could be. I'll post a diagnostic build link here in a couple of hours. If you could try it out and let me know if the problem is still evident, or provide the logging information back to me, it would be of tremendous help.

**Comment by DRY411S** [comment] 2017-12-03 15:33
Happy to help. Already looked for some logging information, couldn't see anything of any use.

**Comment by Taomyn** [comment] 2017-12-03 15:54
Single single screen, my TV (although I play using a Rift), at 1080p

Also happy to test

**Comment by phroggster** [comment] 2017-12-03 16:28
Ok. Grab one of the zip files from [AppVeyor](https://ci.appveyor.com/project/phroggie/eddiscovery/build/8.4.2.212/artifacts). The "NonPortable" zip will use your existing app data, behaving exactly as if it were an installed version, while the "Portable" zip will behave just like the typical portable zip files, keeping the data alongside the application. NonPortable is probably what you want, so just download, extract to say your desktop or something, double-click, and report if it still has this problem, or if it displays any diagnostic information in a popup.

For a changelog, if you want to know what software you're running, [here's the source code comparison to the release of 8.4.2](https://github.com/EDDiscovery/EDDiscovery/compare/Release_8.4.2...phroggster:8.4.2_issue1508). Most of the changes are actually to provide you with the "NonPortable" zip that doesn't require actually being installed to use your existing data.

**Comment by Taomyn** [comment] 2017-12-03 17:33
Well that was interesting, an error pops up, I hit retry, an other error, retry again and then the application starts and this time the problem is reversed

![clipboard01](https://user-images.githubusercontent.com/4365929/33527880-6b0d942e-d858-11e7-94de-c22ffeba9de8.jpg)
![clipboard02](https://user-images.githubusercontent.com/4365929/33527881-6e043110-d858-11e7-88ab-d744cb2eb766.jpg)
![clipboard03](https://user-images.githubusercontent.com/4365929/33527882-710452c8-d858-11e7-8e12-f480cfcd860b.jpg)

**Comment by phroggster** [comment] 2017-12-03 17:42
Ok, then. ∞ is pretty large, and not really suitable to be used with this. I'll see if I can figure out where that's coming from. Meanwhile, you can go back to your regular build, and thank you.

**Comment by klightspeed** [comment] 2017-12-03 17:43
That suggests a divide by zero when storing the splitter position at https://github.com/EDDiscovery/EDDiscovery/blob/ca340444d1d88fca1be10bbf5aeb77361dace991/BaseUtils/WinForms/ControlHelpers.cs#L209

**Comment by phroggster** [comment] 2017-12-03 17:59
It at least looks like we're doing the right thing during close:
https://github.com/EDDiscovery/EDDiscovery/blob/23ac31df8ba2cdc961ae8dcbc9fb41e1503df28a/EDDiscovery/EDDiscoveryForm.cs#L892

**Comment by phroggster** [comment] 2017-12-04 17:11
This issue is a duplicate of #1461, but there's already more progress made here than on that ticket. Hence, I'm going to tag @vidslo to monitor this issue while I close that ticket.

**Comment by phroggster** [comment] 2017-12-04 17:32
I've got a new build up on [AppVeyor](https://ci.appveyor.com/project/phroggie/eddiscovery/build/artifacts) that should help nail down when the divide by zero is occurring. If one of y'all could give this build a go, and let me know what dialog pops up first.

**Comment by phroggster** [comment] 2017-12-04 17:35
Oh, and the same [source code comparison link](https://github.com/EDDiscovery/EDDiscovery/compare/Release_8.4.2...phroggster:8.4.2_issue1508) as above is still valid if you want to know what has changed.

**Comment by Taomyn** [comment] 2017-12-04 19:23
I tried it a few times but no pop up and everything looks correct now - I'll keep giving it a retry over the next few nights to see if I manage to get anything.

**Comment by robbyxp1** [comment] 2017-12-08 17:49
Well, the move to store percentages instead of absolute values did not fix everything. I suggest we use a min max and protect against divide zero.

**Comment by Taomyn** [comment] 2017-12-09 18:50
This happened as I exited the program, the layout was messed up when I started it then I re-sized the left side, everything ran fine but then I got the errors on exit.

![clipboard01](https://user-images.githubusercontent.com/4365929/33798511-0e6bbe1e-dd1a-11e7-98ea-3bef5b4bfb09.jpg)

![clipboard02](https://user-images.githubusercontent.com/4365929/33798516-27925498-dd1a-11e7-8482-c4a4c95b8a54.jpg)

**Comment by phroggster** [comment] 2017-12-10 04:22
Thanks @Taomyn. Doesn't look out of the ordinary, except that the width should not be zero (which is what triggered the previous "value is positive infinity" assertion). Wonder if we've hidden split panel panes or something, if that would even trigger this. I'll see if I can get you a new build to try out in the next ~12 hours or so.

My best guess at this point is to just use a second layer for setting values at startup: if positive infinity, or some other unacceptable value, return some default value supplied by the caller multiplied by the parent's dimension (width/height). Still, it's odd why this would not be giving valid dimensions as-is.

**Comment by Taomyn** [comment] 2017-12-10 09:18
Is it possible that shutting down Windows with program still running and minimised is causing things not to save correctly? Perhaps getting killed by the OS or being minimised is throwing the panel values out.  I usually try to exit it manually when I'm done but sometimes I forget.

**Comment by klightspeed** [comment] 2017-12-10 10:07
It's possible that having it minimised, or having the tab deselected could cause the width to be read as 0.

I don't know how System.Windows.Forms handles the WM_QUERYENDSESSION and WM_ENDSESSION messages.  Windows will typically terminate the process after it processes the WM_ENDSESSION message (see https://blogs.msdn.microsoft.com/oldnewthing/20130627-00/?p=3973).

**Comment by Taomyn** [comment] 2017-12-10 12:24
Well I don't hear the voice saying "Farewell" etc so whether that's because by that time the audio is shutdown or the program terminated I can't say. I do hear a "ding ding" from Steam if I shutdown with it still running and needs to complete a sync, but it tends to hold up the shutdown when that happens.

**Comment by phroggster** [comment] 2017-12-10 19:14
Sure enough, if the application is **minimized** when closed, *sometimes* it will show a size of {0,0}.
![untitled](https://user-images.githubusercontent.com/14035789/33808425-9c6b84c4-ddab-11e7-9a39-28d6cf5541ba.png)

**Comment by phroggster** [comment] 2017-12-11 12:40
All right. I think that we should have it licked, now. Grab the build from [AppVeyor](https://ci.appveyor.com/project/phroggie/eddiscovery/build/8.4.2.219/artifacts), and close it while minimized to your heart's content. It should behave properly in all scenarios, but note that it may slightly be resized when first starting up. Simply resize to your satisfaction and it should save and recall properly.

If no one sees any problems with this approach, I'll get a clean patch pushed in to master within a few days.

**Comment by Taomyn** [comment] 2017-12-11 18:56
Just downloaded the non-portable version, will give it a whirl the next couple of evenings leaving it minimised when I close it and let you know.

**Comment by robbyxp1** [comment] 2017-12-13 12:59
I've protected ControlHelpers.cs from zero sized control.. goes back to a default splitter size.

**Closed by robbyxp1** 2017-12-13 12:59 UTC
Labels: bug

**Comment by DRY411S** [comment] 2017-12-13 19:04
Thanks for the focus on this. Sorry I wasn't around to test.
