### ISSUE TITLE
Scan Panel - Body Mapped status icon missing on some bodies

### ISSUE THREAD

**Issue by hokm** [EDDiscovery/EDDiscovery#2983] opened 2021-01-06 20:48 UTC
If the planet has been mapped : An outline globe icon should be displayed. 
For some mapped bodies the icon is not displayed. See image:

![image](https://user-images.githubusercontent.com/20743490/103818402-c19c5100-5068-11eb-99c8-873019b46f81.png)

**Comment by robbyxp1** [comment] 2021-01-07 10:04
A detailed scan does not mean its mapped.  You need to use your probes to map it.

**Comment by robbyxp1** [comment] 2021-01-07 10:05
Did you map it with probes?

**Comment by klightspeed** [comment] 2021-01-07 10:19
The mapped icon depends on the `SAAScanComplete` event.  Does such an event exist in your journal for that planet?

**Comment by hokm** [comment] 2021-01-07 20:35
@robbyxp1 yes I mapped this planet by firing probes using Detailed Surface Scanner here's the screenshot, you can see there "Phanes 1 100% Percentage Mapped"
![image](https://user-images.githubusercontent.com/20743490/103942033-0939e000-5130-11eb-8956-ae55b2909dc4.png)

**Comment by klightspeed** [comment] 2021-01-07 20:49
Is there a `SAAScanComplete` event in your journal for Phanes 1?

If such an event is not in the journal in EDDiscovery, does the event exist in the journal file in `savedgames:Frontier Developments\Elite Dangerous` associated with the session when that planet was scanned?

**Comment by hokm** [comment] 2021-01-07 20:51
@klightspeed yes, I have it in the journal. Here are two lines related to mapping of this planet:
```json
{ "timestamp":"2021-01-02T21:39:57Z", "event":"SAAScanComplete", "BodyName":"Phanes 1", "SystemAddress":1458242097866, "BodyID":13, "ProbesUsed":6, "EfficiencyTarget":6 }
{ "timestamp":"2021-01-02T21:39:57Z", "event":"Scan", "ScanType":"Detailed", "BodyName":"Phanes 1", "BodyID":13, "Parents":[ {"Star":0} ], "StarSystem":"Phanes", "SystemAddress":1458242097866, "DistanceFromArrivalLS":23.358852, "TidalLock":true, "TerraformState":"", "PlanetClass":"High metal content body", "Atmosphere":"", "AtmosphereType":"None", "Volcanism":"", "MassEM":0.426256, "Radius":4695493.500000, "SurfaceGravity":7.705788, "SurfaceTemperature":885.235474, "SurfacePressure":0.000000, "Landable":true, "Materials":[ { "Name":"iron", "Percent":22.790216 }, { "Name":"nickel", "Percent":17.237564 }, { "Name":"sulphur", "Percent":16.140144 }, { "Name":"carbon", "Percent":13.572189 }, { "Name":"chromium", "Percent":10.249517 }, { "Name":"phosphorus", "Percent":8.689149 }, { "Name":"vanadium", "Percent":5.596484 }, { "Name":"arsenic", "Percent":2.144651 }, { "Name":"cadmium", "Percent":1.769763 }, { "Name":"mercury", "Percent":0.995211 }, { "Name":"technetium", "Percent":0.815114 } ], "Composition":{ "Ice":0.000000, "Rock":0.670732, "Metal":0.329268 }, "SemiMajorAxis":7002790987.491608, "Eccentricity":0.000003, "OrbitalInclination":0.000035, "Periapsis":24.713585, "OrbitalPeriod":357059.556246, "RotationPeriod":357131.858353, "AxialTilt":-0.115228, "WasDiscovered":false, "WasMapped":true }
```
![image](https://user-images.githubusercontent.com/20743490/103943428-5cad2d80-5132-11eb-9855-235a8ddb41fc.png)

**Comment by hokm** [comment] 2021-01-07 21:02
[Journal.210102221649.01.log](https://github.com/EDDiscovery/EDDiscovery/files/5783932/Journal.210102221649.01.log)
here's the full log file

**Comment by klightspeed** [comment] 2021-01-07 22:34
I think the issue is due to processing history in a single pass.  The SAAScanComplete isn't kept by the scan structure for processing by a following Scan event, so if the SAAScanComplete comes through before you have scanned the system (e.g. in this case where it's a pre-scanned system where you did not scan the nav beacon beforehand), then the SAAScanComplete does not yet have a body to attach to.

**Comment by robbyxp1** [comment] 2021-01-08 08:26
We will have to look at the logic of this, thanks.  Normally you have a scan in the database due to the DSS of a body.

**Comment by robbyxp1** [comment] 2021-01-08 16:13
Now fixed on branch, your log showing correctly. Thanks you for the report, this will be in the next EDD

**Closed by robbyxp1** 2021-01-08 16:13 UTC
Labels: EDD Bug
