### ISSUE TITLE
unhandled UI exception when starting up and at various other points

### ISSUE THREAD

**Issue by HillADev** [EDDiscovery/EDDiscovery#2690] opened 2019-12-28 04:22 UTC
First, thank for all your great work!

I am on Windows 7 Pro, below the diagnostic info:

### Exception Details:
>EDDiscovery v11.1.4.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>code = Error (1), message = System.Data.SQLite.SQLiteException (0x800007BF): SQL logic error
>no such column: s.edsmid
>   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
>   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
>   at System.Data.SQLite.SQLiteDataReader.NextResult()
>   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
>   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
>   at EliteDangerousCore.DB.SystemsDB.FindStar(String name, SQLiteConnectionSystem cn) in C:\Code\EDDiscovery\EliteDangerous\SystemDB\SystemsDBGetStars.cs:line 47
>   at EliteDangerousCore.DB.SystemCache.FindSystem(ISystem find, SystemsDatabaseConnection cn) in C:\Code\EDDiscovery\EliteDangerous\SystemDB\SystemCache.cs:line 110
>   at SQLLiteExtensions.SQLProcessingThread`1.Job`1.Exec() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 66
>===== END =====
>```

**Comment by robbyxp1** [comment] 2019-12-28 10:42
For some reason we can't find, this is happening.

Either the FindStar is being called on a DB not set up properly, or being called before we set SystemsDatabase.Instance.RebuildRunning=true when the db not right.

Two way to try and fix this.

1) Use safe mode, Reset Tabs/Popouts, see if it starts up.  Let it build the system db fully (look for signs in the log/bottom of the window thats its populating the system db)

or 

2) Use safe mode, delete the system db, let it rebuild.

**Comment by klightspeed** [comment] 2019-12-28 18:10
This is always when upgrading the system database from the pre-11.0 format to the 11.x format.

Steps to reproduce:
* Run EDDiscovery Portable 10.6 from a SSD, and select None when asked what systems to import.
  - Expect to wait for 10s of minutes if running from a HDD, as the bookmark import was very inefficient
  - Expect to wait a long time if you don't choose None early enough, or don't choose None.
* Exit EDDiscovery
* Extract and run EDDiscovery Portable 11.x in the same directory (or run from Visual Studio with `-AppFolder <path-to-portable-data>`)

**Comment by HillADev** [comment] 2019-12-28 23:10
thanks @robbyxp1, your first solution worked for me

**Comment by robbyxp1** [comment] 2019-12-29 10:45
See my dev comment, we will try and mask this.

**Comment by robbyxp1** [comment] 2020-01-10 08:56
The Fill EDSM is causing it..  due to not deleting the old systems table from pre 102. Fixed on tip

**Closed by robbyxp1** 2020-01-10 08:56 UTC
Labels: EDD Bug
