### ISSUE TITLE
unhandled fatal exception in EDD 17.0.1.0 - System DB gets locked

### ISSUE THREAD

**Issue by StarsamMike** [EDDiscovery/EDDiscovery#3464] opened 2024-01-12 21:16 UTC
EDD 17.0.1.0 crashing after plotting in Nav Route and jumping

```
An unhandled fatal exception has occurred.

==== BEGIN ====
code = Busy (5), message = System.Data.SQLite.SQLiteException (0x800007AF): database is locked
database is locked
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteConnection.Open()
   at SQLLiteExtensions.SQLExtConnection..ctor(String dbfile, Boolean utctimeindicator, AccessMode mode, JournalModes journalmode, Boolean disallow_xthreading) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLConnection.cs:line 67
   at EliteDangerousCore.DB.SystemsDatabase.CreateConnection() in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemsDatabase.cs:line 56
   at SQLLiteExtensions.SQLAdvProcessingThread`1.SqlThreadProc() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs:line 191
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
===== END =====
```

have reinstalled the update, still same result, unusable, happens every time after plotting nav route and jumping.. exiting the fatal error closes EDD.

**Comment by Eahlstan** [comment] 2024-01-12 22:32
Can you please upload the Trace*.log file from EDDs Log folder (usually in %localappdata%\EDDiscovery )?

**Comment by robbyxp1** [comment] 2024-01-12 23:11
This is noted, and is most likely a very unlikely transient issue with SQLLite. Please continuing using and we will look into it.

**Comment by Eahlstan** [comment] 2024-01-12 23:27
Also please state which type of drive your system DB is on - HDD, SSD, we even had someone using an SD card.

**Comment by StarsamMike** [comment] 2024-01-13 11:38
Hi Eahlstan

Thanks for reply, using win 11 x64 on standard HDD, sata, Toshiba HDWR440 4
Tb. No events or errors on drive reported.

Regards
Mike

**Comment by StarsamMike** [comment] 2024-01-13 11:58
Hi Eahlstan

I stopped and started EDD several times hence multiple files, also saw the
HTTP log as well. I am playing the steam version of ED Oddessy

Regards
Mike

**Comment by Eahlstan** [comment] 2024-01-13 12:24
Please upload the Trace*.log file from one of the sessions that crashed.

**Comment by StarsamMike** [comment] 2024-01-13 13:35
Hi Eahlstan

This is the log of the session that crashed last night 12/1/24. I have used
it this afternoon 13/1/24 with no issues.
Thanks for your efforts in looking into this.

Regards
Mike

**Comment by Eahlstan** [comment] 2024-01-13 13:37
You can't upload files using e-mail to answer...

**Comment by StarsamMike** [comment] 2024-01-13 14:29
okay ive attached trace log
[Trace_2024-01-12-21-22-09.0.log](https://github.com/EDDiscovery/EDDiscovery/files/13928309/Trace_2024-01-12-21-22-09.0.log)

**Comment by StarsamMike** [comment] 2024-01-13 14:35
... and the settings panel
![EDD_settings_#3464](https://github.com/EDDiscovery/EDDiscovery/assets/156474683/09821a0a-e82c-404e-8254-b8b6b381a16a)

**Comment by Eahlstan** [comment] 2024-01-13 15:09
> ... and the settings panel

I deleted that screenshot.
Not only were it your commanders settings and not the global settings, it also contained an uncensored API key.

**Comment by robbyxp1** [comment] 2024-01-13 15:12
I removed the log, unfort it also has PII

**Comment by Eahlstan** [comment] 2024-01-13 15:14
> I removed the log, unfort it also has PII

But we saved it, so it was the correct upload.
Now the correct screenshot would be nice.

**Comment by StarsamMike** [comment] 2024-01-13 18:20
right not those settings - how about these ones from the settings tab
![settings2_EDD_#3464](https://github.com/EDDiscovery/EDDiscovery/assets/156474683/2a110146-0754-4573-8d36-6dc6d8787a98)

**Comment by Eahlstan** [comment] 2024-01-13 19:08
Well here's the thing: You enabled the star data download and your system DB is on a HDD. It's as the warning you got when setting it up said:
HDDs and the system DB don't work very well. HDDs are way to slow ( IOPS wise ) to handle it.

Although we will put in a speculative fix for that crash (we can't reproduce it no matter how we torture our DBs) that setup will never work very well. Having star data download enabled and the HDD makes queries so slow that they collide and error out.

**Comment by StarsamMike** [comment] 2024-01-13 19:42
Thanks very much for your efforts, i'll stop downloading the star DB. I do
notice a resource issue with cpu and memory on my machine.

**Comment by Eahlstan** [comment] 2024-01-13 23:19
Stopping to maintain it won't fix it. You have to delete EDDSystem.sqlite (while EDD is closed) to get a new empty DB that won't react to queries (well it will get queried, but when it's empty those queries should be too fast to cause troubles).

To reduce the used memory see https://github.com/EDDiscovery/EDDiscovery/wiki/Reducing-Memory-Usage

**Comment by robbyxp1** [comment] 2024-01-27 10:59
17.0.2 has more defense, we wait to see if it works

**Closed by robbyxp1** 2024-01-27 10:59 UTC
Labels: Issue-Investigating
