### ISSUE TITLE
Duplicate history entry

### ISSUE THREAD

**Issue by andreaspada** [EDDiscovery/EDDiscovery#1317] opened 2017-09-29 17:07 UTC
Just noticed that my history is being duplicate.
Each and every system I enter is marked twice, and the visit counts is marked twice too...

> [2017-09-29 14:02:34Z] EDSM Fetch logs start with cmdr 3
> [2017-09-29 14:02:35Z] New entry 9/29/2017 5:02:00 PM Music
> [2017-09-29 14:02:35Z] New entry 9/29/2017 5:02:13 PM FuelScoop
> [2017-09-29 14:02:35Z] New entry 9/29/2017 5:02:31 PM StartJump
> [2017-09-29 14:02:37Z] New entry 9/29/2017 5:02:36 PM Music
> [2017-09-29 14:02:38Z] New entry 9/29/2017 5:02:00 PM Music
> [2017-09-29 14:02:38Z] New entry 9/29/2017 5:02:13 PM FuelScoop
> [2017-09-29 14:02:38Z] New entry 9/29/2017 5:02:31 PM StartJump
> [2017-09-29 14:02:38Z] New entry 9/29/2017 5:02:36 PM Music
> [2017-09-29 14:02:50Z] New entry 9/29/2017 5:02:50 PM FSDJump
> [2017-09-29 14:02:51Z] Arrived at system: Pyroifoea OJ-X d2-76 1:th visit.
> [2017-09-29 14:02:51Z] Arrived at system: Pyroifoea OJ-X d2-76 2:th visit.
> [2017-09-29 14:02:51Z] New entry 9/29/2017 5:02:50 PM Music
> [2017-09-29 14:02:52Z] New entry 9/29/2017 5:02:50 PM FSDJump
> [2017-09-29 14:02:52Z] New entry 9/29/2017 5:02:50 PM Music
> [2017-09-29 14:03:05Z] New entry 9/29/2017 5:03:05 PM Music
> [2017-09-29 14:03:13Z] New entry 9/29/2017 5:03:13 PM Scan

**Comment by klightspeed** [comment] 2017-09-29 17:53
That sounds like you are monitoring the journals using two separate directories (either differing only in case, or that are linked together).

**Comment by phroggster** [comment] 2017-09-30 18:43
Is it possible that the ED journal event was also duplicated somehow, or multiple instances of EDD were interacting, or the swamp gases reflected light from Venus? In other words, I don't think that we're doing anything wrong on our end, but do admit that it's possible even if it requires an obscure state to be hit.

I'm going to leave this issue open for a week. If you see any further occurrences, or have any additional information to add, please do.

**Comment by Kalpa2** [comment] 2017-09-30 19:45
Allright, here is my take on the issue, except it's slightly different... I'm not getting duplicate entries per se, rather the viewer is showing duplicate lines - sometimes. 

From a cursory look at both frontier's journal & the trace log of EDD, I can't figure out what's wrong. But I include the files here so you fellas can take a look. Also @phroggster told me to. :p
[Trace_20170930202556.0.log](https://github.com/EDDiscovery/EDDiscovery/files/1346719/Trace_20170930202556.0.log)
[Journal.170930163453.01.log](https://github.com/EDDiscovery/EDDiscovery/files/1346721/Journal.170930163453.01.log)

**Comment by klightspeed** [comment] 2017-10-01 07:12
That looks like logs from EDSM are not being properly matched to their existing entries in the journal.  It also appears that those duplicates where the matching system was not found are also causing some scans to be sent to EDDN without coordinates and thus being rejected.

**Comment by andreaspada** [comment] 2017-10-03 01:04
Last build seems to solved that. Anyone still having issues with that?

**Comment by EoD** [comment] 2017-10-05 20:55
I still have the issue with EDD 8.3.2.0, but it only happened on the first jump after starting ED 2.4 for the first time.

**Comment by klightspeed** [comment] 2017-10-05 21:59
@EoD please attach the trace log and journal for the affected period.

**Comment by iainross** [comment] 2017-10-10 23:43
I saw this on my dev build tonight - it looks like EDD can be made to count both the 'StartJump' and 'FSDJump' events as jumps when it should only be the latter.  Struggling to work out how - or even make it repeat what I initially saw by reprocessing the same journals.  Buggered if I can see why it's happening though.

**Comment by Kalpa2** [comment] 2017-10-11 01:58
Just to update, I still see this occasionally as well (EDD 8.3.3.0) - I have no clue how to reproduce. It just seems to occur sometimes.

Logs attached, screenshot at this link (because github refuses to accept either my .png or .jpg file, what gives?) https://cdn.discordapp.com/attachments/344940473149816832/367491073347551252/unknown.png

[Trace_20171010160745.0.log](https://github.com/EDDiscovery/EDDiscovery/files/1373954/Trace_20171010160745.0.log)
[Journal.171010160348.01.log](https://github.com/EDDiscovery/EDDiscovery/files/1373955/Journal.171010160348.01.log)

**Comment by klightspeed** [comment] 2017-10-11 03:08
The problem seems to be from when you have both Sync to EDSM and Sync from EDSM enabled.

Realistically, you should only need Sync from EDSM if you don't need the original logs any more, and should be able to turn it off once your travel history has been pulled from EDSM.

**Comment by EoD** [comment] 2017-10-11 11:12
I also have both sync to and sync from EDSM enabled. 

As far as I understand you, you want us to disable the "sync from EDSM" once we pulled it, don't you? 

I play on different computers and I like it that I don't need to worry about which computer I played last on, because the sync will take care of it. This would remove all the convenience we currently have.

**Comment by iainross** [comment] 2017-10-11 18:38
@EoD I am looking into fixing this but as it seems related to the sync from we're just suggesting that you turn it off until we have a fix released.  We're not looking to take it away forever.

It also does not appear to happen if you run a full sync with from enabled while not playing ED so in the short term, if you want to avoid the duplicating, then turn off "from" while playing and when you switch computers enable it while you do a manual sync before playing.

**Comment by iainross** [comment] 2017-10-11 21:56
@klightspeed has made a change that appears to have solved this (at least for me) before I got round to looking myself.  Should be resolved in next release, until then the workaround of not syncing from while you play should do the trick.

**Closed** 2017-10-29 16:19 UTC
Labels: 8.4 Fixed, bug
