### ISSUE TITLE
Error when closing EDD

### ISSUE THREAD

**Issue by St3vet** [EDDiscovery/EDDiscovery#1440] opened 2017-11-05 09:12 UTC
I got the following error when closing EDD.

### Exception Details:
>There was an unhandled UI exception.
>```
>==== BEGIN ====
>CSCore.DirectSound.DirectSoundException (0x88780096): IDirectSoundBuffer::Stop caused an error: 0x88780096, "Unknown HRESULT".
>   at CSCore.DirectSound.DirectSoundBuffer.Stop()
>   at CSCore.SoundOut.DirectSoundOut.CleanupResources()
>   at CSCore.SoundOut.DirectSoundOut.Dispose(Boolean disposing)
>   at CSCore.SoundOut.DirectSoundOut.Dispose()
>   at AudioExtensions.AudioDriverCSCore.Dispose() in C:\Code\EDDiscovery\Audio\AudioDriverCSCore.cs:line 127
>   at EDDiscovery.EDDiscoveryForm.Controller_FinalClose() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:line 941
>===== END =====
>```

**Comment by phroggster** [comment] 2017-11-05 10:12
Duplicate of #1437.

**Closed by phroggster** 2017-11-05 10:12 UTC

**Comment by phroggster** [comment] 2018-02-14 20:27
@St3vet Please fill out the anonymous survey located at https://www.surveymonkey.com/r/2RJSWK7 to help us try and nail down a potential cause for this.
