### ISSUE TITLE
EDDiscovery v10.6.0.0 Database Locked Exception

### ISSUE THREAD

**Issue by bazza14** [EDDiscovery/EDDiscovery#2503] opened 2019-05-24 16:53 UTC
### Exception Details:
>EDDiscovery v10.6.0.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>code = Busy (5), message = System.Data.SQLite.SQLiteException (0x800007AF): database is locked
>database is locked
>   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
>   at System.Data.SQLite.SQLiteDataReader.NextResult()
>   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
>   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
>   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
>   at System.Data.SQLite.SQLiteTransaction.Begin(Boolean deferredLock)
>   at System.Data.SQLite.SQLiteConnection.BeginDbTransaction(IsolationLevel isolationLevel)
>   at SQLLiteExtensions.SQLExtConnectionWithLock`1.BeginTransaction() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLConnectionLock.cs:line 117
>   at EliteDangerousCore.HistoryList.FillEDSM(HistoryEntry syspos) in C:\Code\EDDiscovery\EliteDangerous\HistoryList\HistoryList.cs:line 579
>   at EDDiscovery.UserControls.UserControlSysInfo.Display(HistoryEntry he, HistoryList hl, Boolean selectedEntry) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Overlays\UserControlSysInfo.cs:line 197
>   at EDDiscovery.UserControls.ChangedSelectionHEHandler.Invoke(HistoryEntry he, HistoryList hl, Boolean selectedEntry)
>   at EDDiscovery.UserControls.UserControlTravelGrid.FireChangeSelection() in C:\Code\EDDiscovery\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:line 546
>   at EDDiscovery.UserControls.UserControlTravelGrid.AddNewEntry(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:line 442
>   at System.Action`2.Invoke(T1 arg1, T2 arg2)
>   at EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 447
>   at EDDiscovery.EDDiscoveryController.PlayJournalList() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 434
>   at EliteDangerousCore.EDJournalClass.ScanTickDone(Tuple`2 entries) in C:\Code\EDDiscovery\EliteDangerous\Journal\EDJournalClass.cs:line 186
>===== END =====
>```

**Comment by klightspeed** [comment] 2019-05-25 05:14
Duplicate of #2501

**Comment by klightspeed** [comment] 2019-05-25 10:47
Would it please be possible to get the trace log from when this occurred?

**Closed** 2019-05-30 07:04 UTC
