### ISSUE TITLE
Crash when jumping in v18.1.0 and v18.1.1

### ISSUE THREAD

**Issue by InodoroPereyra** [EDDiscovery/EDDiscovery#3583] opened 2024-11-08 19:51 UTC
### Additional Information
Jump with Mandalay... 
I have 2 popups Scan & Nearest Star. Ledger was active in the main window
### Exception Details:
>EDDiscovery v18.1.0.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EliteDangerousCore.JournalEvents.JournalScan.HabZoneText_Hab(HabZones hz, StringBuilder sb) in C:\Code\EDDiscovery2\EliteDangerousCore\EliteDangerous\JournalEvents\JournalScan_Subclasses.cs:line 185
>   at EDDiscovery.UserControls.UserControlScanGrid.<DrawSystem>d__9.MoveNext() in C:\Code\EDDiscovery2\EDDiscovery\UserControls\ScansStars\UserControlScanGrid.cs:line 251
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>===== END =====
>```

### Exception Details:
>EDDiscovery v18.1.1.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EliteDangerousCore.JournalEvents.JournalScan.HabZoneText_Hab(HabZones hz, StringBuilder sb) in C:\Code\EDDiscovery2\EliteDangerousCore\EliteDangerous\JournalEvents\JournalScan_Subclasses.cs:line 185
>   at EDDiscovery.UserControls.UserControlScanGrid.<DrawSystem>d__9.MoveNext() in C:\Code\EDDiscovery2\EDDiscovery\UserControls\ScansStars\UserControlScanGrid.cs:line 251
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>===== END =====
>```

**Comment by Eahlstan** [comment] 2024-11-08 20:06
I can't reproduce that. Can you please send me your journal files so I can test it with data that actually caused it?
Are you using any translations?

**Comment by InodoroPereyra** [comment] 2024-11-08 22:20
Hi Eahlstan!
No translation. 
Seems it was a corrupted Scan pop-up (that was like completelly transparent and the planets and symbols were surrounded by a thin green line). After the update 18.1.1 it keept doing it, so I deleted and re-created the pop-up and seems to be working now.

[Journal.2024-11-08T163255.01.log](https://github.com/user-attachments/files/17684647/Journal.2024-11-08T163255.01.log)

**Comment by Eahlstan** [comment] 2024-11-08 22:27
Closing a panel and reopening it uses the same settings as the previously closed one, so that shouldn't change anything.
Thanks for the journal and please alert us if it happens again.

**Comment by Eahlstan** [comment] 2024-11-08 23:00
And scratch that I just got the error.

**Comment by robbyxp1** [comment] 2024-11-09 09:01
I've put more defenses in against this habzone = null problem, probably caused by missing data

thanks for the report.

**Closed by robbyxp1** 2024-11-09 09:01 UTC
Labels: Checked and can't find any problem, Issue-Investigating

**Comment by InodoroPereyra** [comment] 2024-11-09 09:20
Hi Guys,
FYI
Started EDD today and appeared to have the issue (the backgound of the Scan pop-up (that was set to opacity 50% and "On Top") got completelly transparent and the content was surrounded by a green line...), but didnt get the green error window. 
I went to Tools-Pop-Outs, on the main window, and set all transparency off, and the Scan pop-out got "sane" again and havent failed, even after setting the Opacity and On-Top again.
Thanks you!!
Facundo
