### ISSUE TITLE
Compass not working as expected

### ISSUE THREAD

**Issue by Disorganise** [EDDiscovery/EDDiscovery#1980] opened 2018-06-05 21:56 UTC
What I did....
Entered a bookmark by searching for the system, them using the dropdown in the surface bookmarks section.  entering a name, lat and longitude and tick saveable (not sure what that does).  Then right click, send to compass.  Co-ord are 62.4/-70.4

I followed the compass but overshot a little
![img](https://i.imgur.com/rc7BNl0.png)

![img](https://i.imgur.com/JiDfeFm.png)

So I backed up.  And fiddled to try and get the game and compass onscreen together
![img](https://i.imgur.com/7iF12be.png)

It looks to me like it has brought me to the latitude and ignore the longitude.  Perhaps because the longitude is negative?

**Comment by robbyxp1** [comment] 2018-06-05 22:17
I'll have to check.. Iain is the man who knows most about this..

**Comment by iainross** [comment] 2018-06-06 00:37
Odd, I'm sure I've tested this with -ve longitudes and latitudes.  I'll have to check if Robby doesn't get there first.

(Saveable is supposed to tick itself when you've put enough info on the bookmark that it can be saved as a valid entry, you shouldn't be able to edit the state manually)

**Comment by Disorganise** [comment] 2018-06-06 09:19
I *think* maybe you're generating two possible locations.  When I came back this arvo, the compass was correct.  I flew out at an angle of 270ish, and the distance first grew and then started shrinking - I'm pretty sure it swapped around at longitude -90 but when I tried to reverse course to check I got confused :/
The intended location was -70 but I was originally sent to -110 - add the two together and you get -180 which is the wraparound point.  If this is indeed some weird maths oopsie, I assume it would only affect you coming from one 'side' and presumably if co-ord is negative - and I just happened to have that the couple of times I tried it :(  but it would explain why it works for everyone else - likely they don't fly half way around the planet 'cos they got the approach all wrong :)

**Comment by robbyxp1** [comment] 2018-06-06 11:43
Most strange.. i flew just now to -60 -40, and it worked perfectly.  Guided me to it, flew past and around a few times, always back to it.

Maybe it does not work if your approaching from the back of the planet?

**Comment by klightspeed** [comment] 2018-06-06 13:32
https://github.com/EDDiscovery/EDDiscovery/blob/master/EDDiscovery/UserControls/UserControlCompass.cs#L280

`Math.Sin(deltaLat)` should be `Math.Sin(deltaLon / 2)`

**Comment by robbyxp1** [comment] 2018-06-06 13:33
Okay.. will fix

**Comment by robbyxp1** [comment] 2018-06-06 13:37
as shown by https://www.movable-type.co.uk/scripts/latlong.html

Bearing appears correct

**Comment by klightspeed** [comment] 2018-06-06 13:58
Bearing is correct, but distance calculation was ignoring latitude due to a typo.

**Comment by robbyxp1** [comment] 2018-06-06 14:06
Pushed a fix for the distance, hold this for a while to see if any other stuff comes up

**Comment by Abulion** [comment] 2018-06-10 20:40
Today when I use the compass on a couple of planets it been capable to give me directions and distance of my bookmarks.

later not.
Only directions on a different planet.

And when i was in the dweller hide, i have tried to bookmark this, but it give me an error

**Comment by Abulion** [comment] 2018-06-13 18:53
I can confirm that when I am at a planet base and try to bookmark my location it give an error

System.ArgumentException; Valore di DataGridViewComboBox non valido. Per sostituire questa finestra di dialogo gestire l'evento Data Error.

**Comment by spadino** [comment] 2018-06-13 20:08
Ciao @abulion, è davvero strana questa cosa. Non ho ancora avuto problemi di questo tipo, sebbene lo usi molto poco. Darò un'occhiata più tardi per vedere se trovo qualcosa nel codice. Comunque, i ragazzi qui sono genial, sono sicuro che verrà scoperto il problema. Considera però che il programma è cresciuto pazzescamente negli ultimi due anni, già che abbiamo incluso una quantità davvero astronomica di cose... ;)

**Comment by Abulion** [comment] 2018-06-14 14:03
In pratica ho cercato di creare un bookmark all'interno di un avamposto su un pianeta in cui ero ormeggiato :P 

Probabilmente è una cosa che NON fa nessuno, e quindi è un errore non gestito dal programma.

Magari basta solo una finestrella che dice, "non posso creare il bookmark all'interno di una base"

o qualcosa del genere :P 

(Prova magari anche a farlo te)

**Comment by robbyxp1** [comment] 2018-06-21 07:10
Need to double check bookmarking on planet.

**Comment by robbyxp1** [comment] 2018-07-03 13:18
Crash has been fixed in 10.1.4

**Closed by robbyxp1** 2018-07-03 13:18 UTC
Labels: EDD Bug
