### ISSUE TITLE
Objects in 3d map out of place?

### ISSUE THREAD

**Issue by Gopher-nz** [EDDiscovery/EDDiscovery#3302] opened 2022-08-19 00:42 UTC
Hi, I am using version 15.1.1.0 When I right click on some of the small icons in Outer Orion-Perseus Conflux, I get the drop down menu and the option to select information. When I do so, a small window detailing the star is presented. When I click on goto it takes me to a star on the other side of the galaxy. Is this how the map should work?

**Comment by robbyxp1** [comment] 2022-08-19 07:31
No. I'll check

**Comment by Gopher-nz** [comment] 2022-08-19 09:15
Cheers mate - I have reinstalled it with no effect

**Comment by Eahlstan** [comment] 2022-08-19 10:41
I can't reproduce this. Please provide screenshots.

**Comment by Gopher-nz** [comment] 2022-08-19 11:24
Will do tomorrow. Just off to bed.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by robbyxp1** [comment] 2022-08-19 11:30
I also can't reproduce this either.

**Comment by Gopher-nz** [comment] 2022-08-20 03:09
See attached
[3d map.docx](https://github.com/EDDiscovery/EDDiscovery/files/9386150/3d.map.docx)

**Comment by klightspeed** [comment] 2022-08-20 07:01
![image](https://user-images.githubusercontent.com/147116/185733099-0ff18664-95d3-4809-9b3a-f87e4b66564f.png)

Does every object take you to this one nebula (which happens to have index 0 in the `galmap.VisibleMapObjects` list)?

Aside:
In investigating this, I just discovered that panning is inverted, and right-click / two-button panning are swapped.

In my instance, the nebula you checked the info on was `Hypoea Gria UU-X e1-0 Nebula`.

**Comment by Gopher-nz** [comment] 2022-08-20 07:35
Yes it does

**Comment by Gopher-nz** [comment] 2022-08-20 08:22
Should I just do a complete uninstall of everything and reinstall EDSM? Seems like not everyone gets this problem.

**Comment by klightspeed** [comment] 2022-08-20 08:45
What graphics card do you have?
I'm wondering if in your particular case the search shader is returning a zero vertex as the second item in the array it returns (the first being the vertex count)?
Re-installing EDDiscovery is unlikely to resolve the issue, as is re-downloading the system database or EDSM POIs.

**Comment by Gopher-nz** [comment] 2022-08-20 08:52
I have a MSI Radeon RX 6800 XT Gaming Trio. I don't have the radeon software installed and prefer to use the windows GPU drivers instead. I also noticed that I don't have the same issues with the old 3d map.

**Comment by klightspeed** [comment] 2022-08-20 08:56
The old 3D map uses graphics primitives that were available in OpenGL 1.5 (released in 2003).
The new 3D map uses graphics primitives available in OpenGL 4.5 (released in 2014), and makes use of shaders.

**Comment by Gopher-nz** [comment] 2022-08-20 08:59
Okay - is there anything I can do about it so the new 3d map is usable for me?

**Comment by klightspeed** [comment] 2022-08-20 10:29
Replicated on my work computer, which has dual AMD R5 430 adaptors.
All of the vertexes returned by the shader have Y=0

**Comment by robbyxp1** [comment] 2022-08-20 14:29
OpenGL 4.6 actually.

If your not using AMD drivers who knows what implementation of openGL that it is using.  I've no idea how good the stock windows openGL is.

I think that without using official drivers we can't do anything more and your out of luck.

Note the old 3dmap using very out of date technology will be removed in 15.2.

**Comment by Eahlstan** [comment] 2022-08-20 14:56
> Replicated on my work computer, which has dual AMD R5 430 adaptors. All of the vertexes returned by the shader have Y=0

Could you please tell us about the drivers this machine is using?

**Comment by klightspeed** [comment] 2022-08-20 15:54
Debugging the pipeline, somehow the `instance` output from the TessEvaluationShader isn't making it to the GeometryShader `instance` input.

i.e. the shader program in `GLPLTesselationEvaluateSinewave` sets its output `instance` correctly, but the shader program in `GLPLGeoShaderFindTriangles` sees its input `instance[0]` as `0`

Driver version is 27.20.20904.4000
Version  4.6.14830
Version  4.6.14830 Core Profile Context 21.09.04.04 27.20.20904.4000
Vendor  ATI Technologies Inc.
Shading lang 4.60

I'll see how it goes once I have installed the latest Adrenaline drivers.

**Comment by robbyxp1** [comment] 2022-08-20 17:53
OpenGL is fun to debug.. i.e you can't directly.

When I wrote it I used side output buffers to dump stuff to see what was happening... or maybe used colour to show what was going on.

**Closed by robbyxp1** 2022-08-20 17:53 UTC
Labels: Issue-Investigating

**Comment by klightspeed** [comment] 2022-08-20 17:58
Getting rid of `gl_CullDistance` from the `in gl_PerVertex` stops the driver from stomping on the inputs.

**Comment by klightspeed** [comment] 2022-08-20 18:32
Reading <https://registry.khronos.org/OpenGL-Refpages/gl4/html/gl_CullDistance.xhtml>:
> As an output variable, gl_CullDistance provides the place for the shader to write these distances. **As an input in all but the fragment language, it reads the values written in the previous shader stage.**

Adding `gl_CullDistance` to the `out gl_PerVertex` of the tesselation phase also stops the driver from stomping on the geometry shader inputs.

**Comment by klightspeed** [comment] 2022-08-20 18:47
Now, do I do a force-push to fix the extra `r` in the `geometry` in the above pull request?
