### ISSUE TITLE
EDD app lagging and crashing

### ISSUE THREAD

**Issue by SgtEpsilon** [EDDiscovery/EDDiscovery#3187] opened 2021-10-16 16:08 UTC
I've been using EDD for a couple of days and it likes to lag out a lot and has crashed on me twice, is there any way to stop the lagging? 

Also while attempting to log into EDSM via the program it lagged too much to allow me to log in

**Comment by klightspeed** [comment] 2021-10-16 16:38
Would it please be possible to get the `Trace_*.log` files from when the program crashed in order to identify the cause of the crash?

Please also try disabling downloading all star data in the settings panel.  If you have slow storage, then it can cause issues.

**Comment by Eahlstan** [comment] 2021-10-16 17:30
It's this:

```
[2021-10-10T14:07:11.583Z] ==== UNHANDLED EXCEPTION ====
[2021-10-10T14:07:11.583Z] CSCore.DirectSound.DirectSoundException (0x88780096): IDirectSoundBuffer::Stop caused an error: 0x88780096, "Unknown HRESULT".

[2021-10-10T14:07:11.583Z]    at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)

[2021-10-10T14:07:11.583Z]    at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)

[2021-10-10T14:07:11.583Z]    at BaseUtils.Threads.TaskQueue.ProcessQueuedItems(Object ignored) in C:\Code\Examples\EDDiscovery\BaseUtilities\BaseUtilities\Threads\TaskQueue.cs:line 62

[2021-10-10T14:07:11.583Z]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

[2021-10-10T14:07:11.583Z]    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

[2021-10-10T14:07:11.583Z]    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()

[2021-10-10T14:07:11.583Z]    at System.Threading.ThreadPoolWorkQueue.Dispatch()
[2021-10-10T14:07:11.583Z] ==== cut ====
```

Did you activate any voice pack or anything else that uses the sound card?

**Comment by SgtEpsilon** [comment] 2021-10-16 17:35
I was using the voice control plugin "FreeVoiceControlV3" but I disabled it due to it not being compatible while on comms with my wing however I do still have it installed

**Comment by Eahlstan** [comment] 2021-10-16 17:38
Could you go to %localappdata%\EDDiscovery\Actions and upload every file that's in there so we can have a look at it?
Then delete all files in that folder and start EDD to see if that fixes it until a fix has been made to the code.

**Comment by SgtEpsilon** [comment] 2021-10-16 17:39
github is saying that it doesn't support the file types, give me two minutes and I'll send a dropbox folder with the files

**Comment by klightspeed** [comment] 2021-10-17 03:46
0x88780096 (DSERR_BUFFERLOST) is a thorn in DirectSound.

Unfortunately because the error logger didn't log the inner exception, we don't know where exactly the error would be, but there is currently only one user of `BaseUtils.Threads.TaskQueue`, so the error would likely be somewhere in <https://github.com/EDDiscovery/BaseUtilities/blob/master/Audio/AudioQueue.cs#L123-L194>, either at `ad.Stop()` or `ad.Start()`

**Comment by robbyxp1** [comment] 2021-10-17 07:51
If DirectSound is excepting, my thoughts are there is something up with your sound system.  I've got no idea what to do to fix it though.

**Comment by robbyxp1** [comment] 2021-10-17 07:52
This <https://superuser.com/questions/573678/error-creating-directsound-buffer-error-code-88780096> says to restart the windows audio service.

**Comment by robbyxp1** [comment] 2021-10-17 07:52
See if you have an updated driver for your sound system available as well.

**Comment by Eahlstan** [comment] 2021-10-17 09:13
It might also be a good idea to see if you got more errors in the log of Windows at the times EDD crashed.
https://www.howtogeek.com/123646/htg-explains-what-the-windows-event-viewer-is-and-how-you-can-use-it/

**Comment by robbyxp1** [comment] 2021-10-18 20:49
Now closing, no more from user.

**Closed by robbyxp1** 2021-10-18 20:49 UTC
Labels: Interaction with Windows System
