### ISSUE TITLE
Searched for "Mission" and a ton of these came up. All the same. It said to notify you.

### ISSUE THREAD

**Issue by Jibsman** [EDDiscovery/EDDiscovery#3126] opened 2021-07-04 05:09 UTC
{"timestamp":"2021-07-04T03:50:14Z","event":"ShipLocker","Items":[{"Name":"personaldocuments","Name_Localised":"Personal Documents","OwnerID":0,"MissionID":788637005,"Count":1},{"Name":"weaponschematic","Name_Localised":"Weapon Schematic","OwnerID":0,"MissionID":788637249,"Count":1},{"Name":"biochemicalagent","Name_Localised":"Biochemical Agent","OwnerID":0,"Count":8},{"Name":"gmeds","Name_Localised":"G-Meds","OwnerID":0,"Count":2},{"Name":"healthmonitor","Name_Localised":"Health Monitor","OwnerID":0,"Count":4},{"Name":"healthmonitor","Name_Localised":"Health Monitor","OwnerID":4117573,"Count":4},{"Name":"insight","OwnerID":0,"Count":2},{"Name":"insightdatabank","Name_Localised":"Insight Data Bank","OwnerID":0,"Count":3},{"Name":"personalcomputer","Name_Localised":"Personal Computer","OwnerID":0,"Count":2},{"Name":"compactlibrary","Name_Localised":"Compact Library","OwnerID":0,"Count":3},{"Name":"hush","OwnerID":0,"Count":10},{"Name":"infinity","OwnerID":0,"Count":5},{"Name":"insightentertainmentsuite","Name_Localised":"Insight Entertainment Suite","OwnerID":0,"Count":1},{"Name":"lazarus","OwnerID":0,"Count":7},{"Name":"nutritionalconcentrate","Name_Localised":"Nutritional Concentrate","OwnerID":0,"Count":1},{"Name":"personaldocuments","Name_Localised":"Personal Documents","OwnerID":0,"Count":1},{"Name":"push","OwnerID":0,"Count":50},{"Name":"syntheticpathogen","Name_Localised":"Synthetic Pathogen","OwnerID":0,"Count":31},{"Name":"universaltranslator","Name_Localised":"Universal Translator","OwnerID":0,"Count":1},{"Name":"weaponschematic","Name_Localised":"Weapon Schematic","OwnerID":0,"Count":9},{"Name":"degradedpowerregulator","Name_Localised":"Degraded Power Regulator","OwnerID":0,"Count":1},{"Name":"largecapacitypowerregulator","Name_Localised":"Power Regulator","OwnerID":0,"Count":2}],"Components":[{"Name":"memorychip","Name_Localised":"Memory Chip","OwnerID":0,"MissionID":787999146,"Count":1},{"Name":"graphene","OwnerID":0,"Count":2},{"Name":"circuitswitch","Name_Localised":"Circuit Switch","OwnerID":0,"Count":6},{"Name":"encryptedmemorychip","Name_Localised":"Encrypted Memory Chip","OwnerID":0,"Count":1},{"Name":"epoxyadhesive","Name_Localised":"Epoxy Adhesive","OwnerID":0,"Count":2},{"Name":"memorychip","Name_Localised":"Memory Chip","OwnerID":0,"Count":3},{"Name":"metalcoil","Name_Localised":"Metal Coil","OwnerID":0,"Count":1},{"Name":"microsupercapacitor","Name_Localised":"Micro Supercapacitor","OwnerID":0,"Count":3},{"Name":"microtransformer","Name_Localised":"Micro Transformer","OwnerID":0,"Count":2},{"Name":"opticalfibre","Name_Localised":"Optical Fibre","OwnerID":0,"Count":2},{"Name":"microelectrode","OwnerID":0,"Count":2},{"Name":"ionbattery","Name_Localised":"Ion Battery","OwnerID":0,"Count":3}],"Consumables":[{"Name":"healthpack","Name_Localised":"Medkit","OwnerID":0,"Count":68},{"Name":"energycell","Name_Localised":"Energy Cell","OwnerID":0,"Count":39},{"Name":"amm_grenade_emp","Name_Localised":"Shield Disruptor","OwnerID":0,"Count":89},{"Name":"amm_grenade_frag","Name_Localised":"Frag Grenade","OwnerID":0,"Count":64},{"Name":"amm_grenade_shield","Name_Localised":"Shield Projector","OwnerID":0,"Count":58},{"Name":"bypass","Name_Localised":"E-Breach","OwnerID":0,"Count":79}],"Data":[{"Name":"internalcorrespondence","Name_Localised":"Internal Correspondence","OwnerID":0,"Count":3},{"Name":"nocdata","Name_Localised":"NOC Data","OwnerID":0,"Count":1},{"Name":"censusdata","Name_Localised":"Census Data","OwnerID":0,"Count":1},{"Name":"chemicalinventory","Name_Localised":"Chemical Inventory","OwnerID":4117573,"Count":1},{"Name":"combatantperformance","Name_Localised":"Combatant Performance","OwnerID":4117573,"Count":10},{"Name":"explorationjournals","Name_Localised":"Exploration Journals","OwnerID":0,"Count":1},{"Name":"extractionyielddata","Name_Localised":"Extraction Yield Data","OwnerID":4117573,"Count":5},{"Name":"manufacturinginstructions","Name_Localised":"Manufacturing Instructions","OwnerID":0,"Count":2},{"Name":"operationalmanual","Name_Localised":"Operational Manual","OwnerID":0,"Count":2},{"Name":"radioactivitydata","Name_Localised":"Radioactivity Data","OwnerID":0,"Count":2},{"Name":"stellaractivitylogs","Name_Localised":"Stellar Activity Logs","OwnerID":0,"Count":2},{"Name":"surveilleancelogs","Name_Localised":"Surveillance Logs","OwnerID":0,"Count":2},{"Name":"topographicalsurveys","Name_Localised":"Topographical Surveys","OwnerID":0,"Count":1},{"Name":"weaponinventory","Name_Localised":"Weapon Inventory","OwnerID":4117573,"Count":2}]}

**Comment by klightspeed** [comment] 2021-07-04 05:21
Duplicate of #3088

**Closed by klightspeed** 2021-07-04 05:21 UTC
